# Code generated by `ubx sdk gen` from azurerm_backup_policy_file_share. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class PolicyFileShare_Backup_Hourly:
    interval: Any = None
    start_time: Any = None
    window_duration: Any = None

@dataclasses.dataclass
class PolicyFileShare_Backup:
    frequency: Any = None
    time: Any = None
    hourly: Any = None

@dataclasses.dataclass
class PolicyFileShare_RetentionDaily:
    count: Any = None

@dataclasses.dataclass
class PolicyFileShare_RetentionMonthly:
    count: Any = None
    days: Any = None
    include_last_days: Any = None
    weekdays: Any = None
    weeks: Any = None

@dataclasses.dataclass
class PolicyFileShare_RetentionWeekly:
    count: Any = None
    weekdays: Any = None

@dataclasses.dataclass
class PolicyFileShare_RetentionYearly:
    count: Any = None
    days: Any = None
    include_last_days: Any = None
    months: Any = None
    weekdays: Any = None
    weeks: Any = None

@dataclasses.dataclass
class PolicyFileShare_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_PolicyFileShare_Backup_HourlyFields = {
    "interval": sdk.FieldSpec(wire_name="interval"),
    "start_time": sdk.FieldSpec(wire_name="start_time"),
    "window_duration": sdk.FieldSpec(wire_name="window_duration"),
}

_PolicyFileShare_BackupFields = {
    "frequency": sdk.FieldSpec(wire_name="frequency"),
    "time": sdk.FieldSpec(wire_name="time"),
    "hourly": sdk.FieldSpec(
        wire_name="hourly",
        kind="list",
        fields=_PolicyFileShare_Backup_HourlyFields,
    ),
}

_PolicyFileShare_RetentionDailyFields = {
    "count": sdk.FieldSpec(wire_name="count"),
}

_PolicyFileShare_RetentionMonthlyFields = {
    "count": sdk.FieldSpec(wire_name="count"),
    "days": sdk.FieldSpec(wire_name="days"),
    "include_last_days": sdk.FieldSpec(wire_name="include_last_days"),
    "weekdays": sdk.FieldSpec(wire_name="weekdays"),
    "weeks": sdk.FieldSpec(wire_name="weeks"),
}

_PolicyFileShare_RetentionWeeklyFields = {
    "count": sdk.FieldSpec(wire_name="count"),
    "weekdays": sdk.FieldSpec(wire_name="weekdays"),
}

_PolicyFileShare_RetentionYearlyFields = {
    "count": sdk.FieldSpec(wire_name="count"),
    "days": sdk.FieldSpec(wire_name="days"),
    "include_last_days": sdk.FieldSpec(wire_name="include_last_days"),
    "months": sdk.FieldSpec(wire_name="months"),
    "weekdays": sdk.FieldSpec(wire_name="weekdays"),
    "weeks": sdk.FieldSpec(wire_name="weeks"),
}

_PolicyFileShare_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PolicyFileShareConfig:
    backup_tier: Any = None
    id: Any = None
    name: Any = None
    recovery_vault_name: Any = None
    resource_group_name: Any = None
    snapshot_retention_in_days: Any = None
    timezone: Any = None
    backup: Any = None
    retention_daily: Any = None
    retention_monthly: Any = None
    retention_weekly: Any = None
    retention_yearly: Any = None
    timeouts: Any = None

PolicyFileShare = sdk.ResourceBinding(
    wire_type="azurerm_backup_policy_file_share",
    fields={
        "backup_tier": sdk.FieldSpec(wire_name="backup_tier"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "recovery_vault_name": sdk.FieldSpec(wire_name="recovery_vault_name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "snapshot_retention_in_days": sdk.FieldSpec(wire_name="snapshot_retention_in_days"),
        "timezone": sdk.FieldSpec(wire_name="timezone"),
        "backup": sdk.FieldSpec(
            wire_name="backup",
            kind="list",
            fields=_PolicyFileShare_BackupFields,
        ),
        "retention_daily": sdk.FieldSpec(
            wire_name="retention_daily",
            kind="list",
            fields=_PolicyFileShare_RetentionDailyFields,
        ),
        "retention_monthly": sdk.FieldSpec(
            wire_name="retention_monthly",
            kind="list",
            fields=_PolicyFileShare_RetentionMonthlyFields,
        ),
        "retention_weekly": sdk.FieldSpec(
            wire_name="retention_weekly",
            kind="list",
            fields=_PolicyFileShare_RetentionWeeklyFields,
        ),
        "retention_yearly": sdk.FieldSpec(
            wire_name="retention_yearly",
            kind="list",
            fields=_PolicyFileShare_RetentionYearlyFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PolicyFileShare_TimeoutsFields,
        ),
    },
)
