# Code generated by `ubx sdk gen` from azurerm_cognitive_account_project. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AccountProject_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class AccountProject_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AccountProject_IdentityFields = {
    "identity_ids": ubx.FieldSpec(wire_name="identity_ids"),
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_AccountProject_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AccountProjectConfig:
    cognitive_account_id: Any = None
    description: Any = None
    display_name: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    tags: Any = None
    identity: Any = None
    timeouts: Any = None

AccountProject = ubx.ResourceBinding(
    wire_type="azurerm_cognitive_account_project",
    fields={
        "cognitive_account_id": ubx.FieldSpec(wire_name="cognitive_account_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_AccountProject_IdentityFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AccountProject_TimeoutsFields,
        ),
    },
)
