# Code generated by `ubx sdk gen` from azurerm_kusto_cluster_customer_managed_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ClusterCustomerManagedKey_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ClusterCustomerManagedKey_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ClusterCustomerManagedKeyConfig:
    cluster_id: Any = None
    id: Any = None
    key_name: Any = None
    key_vault_id: Any = None
    key_version: Any = None
    managed_hsm_key_id: Any = None
    user_identity: Any = None
    timeouts: Any = None

ClusterCustomerManagedKey = ubx.ResourceBinding(
    wire_type="azurerm_kusto_cluster_customer_managed_key",
    fields={
        "cluster_id": ubx.FieldSpec(wire_name="cluster_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "key_name": ubx.FieldSpec(wire_name="key_name"),
        "key_vault_id": ubx.FieldSpec(wire_name="key_vault_id"),
        "key_version": ubx.FieldSpec(wire_name="key_version"),
        "managed_hsm_key_id": ubx.FieldSpec(wire_name="managed_hsm_key_id"),
        "user_identity": ubx.FieldSpec(wire_name="user_identity"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ClusterCustomerManagedKey_TimeoutsFields,
        ),
    },
)
