# Code generated by `ubx sdk gen` from azurerm_api_management_identity_provider_facebook. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagementIdentityProviderFacebook_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagementIdentityProviderFacebook_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagementIdentityProviderFacebookConfig:
    api_management_name: Any = None
    app_id: Any = None
    app_secret: Any = None
    id: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

ManagementIdentityProviderFacebook = sdk.ResourceBinding(
    wire_type="azurerm_api_management_identity_provider_facebook",
    fields={
        "api_management_name": sdk.FieldSpec(wire_name="api_management_name"),
        "app_id": sdk.FieldSpec(wire_name="app_id"),
        "app_secret": sdk.FieldSpec(wire_name="app_secret"),
        "id": sdk.FieldSpec(wire_name="id"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementIdentityProviderFacebook_TimeoutsFields,
        ),
    },
)
