# Code generated by `ubx sdk gen` from azurerm_api_management_notification_recipient_user. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagementNotificationRecipientUser_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_ManagementNotificationRecipientUser_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class ManagementNotificationRecipientUserConfig:
    api_management_id: Any = None
    id: Any = None
    notification_type: Any = None
    user_id: Any = None
    timeouts: Any = None

ManagementNotificationRecipientUser = sdk.ResourceBinding(
    wire_type="azurerm_api_management_notification_recipient_user",
    fields={
        "api_management_id": sdk.FieldSpec(wire_name="api_management_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "notification_type": sdk.FieldSpec(wire_name="notification_type"),
        "user_id": sdk.FieldSpec(wire_name="user_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementNotificationRecipientUser_TimeoutsFields,
        ),
    },
)
