# Code generated by `ubx sdk gen` from azurerm_api_management_named_value. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagementNamedValue_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class ManagementNamedValue_ValueFromKeyVault:
    identity_client_id: Any = None
    secret_id: Any = None

_ManagementNamedValue_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

_ManagementNamedValue_ValueFromKeyVaultFields = {
    "identity_client_id": sdk.FieldSpec(wire_name="identity_client_id"),
    "secret_id": sdk.FieldSpec(wire_name="secret_id"),
}

@dataclasses.dataclass
class ManagementNamedValueConfig:
    api_management_name: Any = None
    display_name: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    secret: Any = None
    tags: Any = None
    value: Any = None
    timeouts: Any = None
    value_from_key_vault: Any = None

ManagementNamedValue = sdk.ResourceBinding(
    wire_type="azurerm_api_management_named_value",
    fields={
        "api_management_name": sdk.FieldSpec(wire_name="api_management_name"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "secret": sdk.FieldSpec(wire_name="secret"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "value": sdk.FieldSpec(wire_name="value"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementNamedValue_TimeoutsFields,
        ),
        "value_from_key_vault": sdk.FieldSpec(
            wire_name="value_from_key_vault",
            kind="list",
            fields=_ManagementNamedValue_ValueFromKeyVaultFields,
        ),
    },
)
