# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .manager_azure_endpoint import ManagerAzureEndpoint, ManagerAzureEndpointConfig
from .manager_external_endpoint import ManagerExternalEndpoint, ManagerExternalEndpointConfig
from .manager_nested_endpoint import ManagerNestedEndpoint, ManagerNestedEndpointConfig
from .manager_profile import ManagerProfile, ManagerProfileConfig
