# Code generated by `ubx sdk gen` from azurerm_stream_analytics_stream_input_eventhub_v2. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AnalyticsStreamInputEventhubV2_Serialization:
    encoding: Any = None
    field_delimiter: Any = None
    type: Any = None

@dataclasses.dataclass
class AnalyticsStreamInputEventhubV2_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsStreamInputEventhubV2_SerializationFields = {
    "encoding": sdk.FieldSpec(wire_name="encoding"),
    "field_delimiter": sdk.FieldSpec(wire_name="field_delimiter"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_AnalyticsStreamInputEventhubV2_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsStreamInputEventhubV2Config:
    authentication_mode: Any = None
    eventhub_consumer_group_name: Any = None
    eventhub_name: Any = None
    id: Any = None
    name: Any = None
    partition_key: Any = None
    servicebus_namespace: Any = None
    shared_access_policy_key: Any = None
    shared_access_policy_name: Any = None
    stream_analytics_job_id: Any = None
    serialization: Any = None
    timeouts: Any = None

AnalyticsStreamInputEventhubV2 = sdk.ResourceBinding(
    wire_type="azurerm_stream_analytics_stream_input_eventhub_v2",
    fields={
        "authentication_mode": sdk.FieldSpec(wire_name="authentication_mode"),
        "eventhub_consumer_group_name": sdk.FieldSpec(wire_name="eventhub_consumer_group_name"),
        "eventhub_name": sdk.FieldSpec(wire_name="eventhub_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "partition_key": sdk.FieldSpec(wire_name="partition_key"),
        "servicebus_namespace": sdk.FieldSpec(wire_name="servicebus_namespace"),
        "shared_access_policy_key": sdk.FieldSpec(wire_name="shared_access_policy_key"),
        "shared_access_policy_name": sdk.FieldSpec(wire_name="shared_access_policy_name"),
        "stream_analytics_job_id": sdk.FieldSpec(wire_name="stream_analytics_job_id"),
        "serialization": sdk.FieldSpec(
            wire_name="serialization",
            kind="list",
            fields=_AnalyticsStreamInputEventhubV2_SerializationFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsStreamInputEventhubV2_TimeoutsFields,
        ),
    },
)
