# Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_powerbi. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AnalyticsOutputPowerbi_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsOutputPowerbi_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsOutputPowerbiConfig:
    dataset: Any = None
    group_id: Any = None
    group_name: Any = None
    id: Any = None
    name: Any = None
    stream_analytics_job_id: Any = None
    table: Any = None
    token_user_display_name: Any = None
    token_user_principal_name: Any = None
    timeouts: Any = None

AnalyticsOutputPowerbi = sdk.ResourceBinding(
    wire_type="azurerm_stream_analytics_output_powerbi",
    fields={
        "dataset": sdk.FieldSpec(wire_name="dataset"),
        "group_id": sdk.FieldSpec(wire_name="group_id"),
        "group_name": sdk.FieldSpec(wire_name="group_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "stream_analytics_job_id": sdk.FieldSpec(wire_name="stream_analytics_job_id"),
        "table": sdk.FieldSpec(wire_name="table"),
        "token_user_display_name": sdk.FieldSpec(wire_name="token_user_display_name"),
        "token_user_principal_name": sdk.FieldSpec(wire_name="token_user_principal_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsOutputPowerbi_TimeoutsFields,
        ),
    },
)
