# Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_function. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AnalyticsOutputFunction_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsOutputFunction_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsOutputFunctionConfig:
    api_key: Any = None
    batch_max_count: Any = None
    batch_max_in_bytes: Any = None
    function_app: Any = None
    function_name: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    stream_analytics_job_name: Any = None
    timeouts: Any = None

AnalyticsOutputFunction = ubx.ResourceBinding(
    wire_type="azurerm_stream_analytics_output_function",
    fields={
        "api_key": ubx.FieldSpec(wire_name="api_key"),
        "batch_max_count": ubx.FieldSpec(wire_name="batch_max_count"),
        "batch_max_in_bytes": ubx.FieldSpec(wire_name="batch_max_in_bytes"),
        "function_app": ubx.FieldSpec(wire_name="function_app"),
        "function_name": ubx.FieldSpec(wire_name="function_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "stream_analytics_job_name": ubx.FieldSpec(wire_name="stream_analytics_job_name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsOutputFunction_TimeoutsFields,
        ),
    },
)
