# Code generated by `ubx sdk gen` from azurerm_stream_analytics_output_servicebus_queue. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AnalyticsOutputServicebusQueue_Serialization:
    encoding: Any = None
    field_delimiter: Any = None
    format: Any = None
    type: Any = None

@dataclasses.dataclass
class AnalyticsOutputServicebusQueue_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsOutputServicebusQueue_SerializationFields = {
    "encoding": ubx.FieldSpec(wire_name="encoding"),
    "field_delimiter": ubx.FieldSpec(wire_name="field_delimiter"),
    "format": ubx.FieldSpec(wire_name="format"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_AnalyticsOutputServicebusQueue_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsOutputServicebusQueueConfig:
    authentication_mode: Any = None
    id: Any = None
    name: Any = None
    property_columns: Any = None
    queue_name: Any = None
    resource_group_name: Any = None
    servicebus_namespace: Any = None
    shared_access_policy_key: Any = None
    shared_access_policy_name: Any = None
    stream_analytics_job_name: Any = None
    system_property_columns: Any = None
    serialization: Any = None
    timeouts: Any = None

AnalyticsOutputServicebusQueue = ubx.ResourceBinding(
    wire_type="azurerm_stream_analytics_output_servicebus_queue",
    fields={
        "authentication_mode": ubx.FieldSpec(wire_name="authentication_mode"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "property_columns": ubx.FieldSpec(wire_name="property_columns"),
        "queue_name": ubx.FieldSpec(wire_name="queue_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "servicebus_namespace": ubx.FieldSpec(wire_name="servicebus_namespace"),
        "shared_access_policy_key": ubx.FieldSpec(wire_name="shared_access_policy_key"),
        "shared_access_policy_name": ubx.FieldSpec(wire_name="shared_access_policy_name"),
        "stream_analytics_job_name": ubx.FieldSpec(wire_name="stream_analytics_job_name"),
        "system_property_columns": ubx.FieldSpec(wire_name="system_property_columns"),
        "serialization": ubx.FieldSpec(
            wire_name="serialization",
            kind="list",
            fields=_AnalyticsOutputServicebusQueue_SerializationFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsOutputServicebusQueue_TimeoutsFields,
        ),
    },
)
