# Code generated by `ubx sdk gen` from azurerm_application_load_balancer_frontend. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class LoadBalancerFrontend_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_LoadBalancerFrontend_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class LoadBalancerFrontendConfig:
    application_load_balancer_id: Any = None
    id: Any = None
    name: Any = None
    tags: Any = None
    timeouts: Any = None

LoadBalancerFrontend = sdk.ResourceBinding(
    wire_type="azurerm_application_load_balancer_frontend",
    fields={
        "application_load_balancer_id": sdk.FieldSpec(wire_name="application_load_balancer_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LoadBalancerFrontend_TimeoutsFields,
        ),
    },
)
