# Code generated by `ubx sdk gen` from azurerm_resource_policy_assignment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class PolicyAssignment_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class PolicyAssignment_NonComplianceMessage:
    content: Any = None
    policy_definition_reference_id: Any = None

@dataclasses.dataclass
class PolicyAssignment_Overrides_Selectors:
    in_: Any = None
    kind: Any = None
    not_in: Any = None

@dataclasses.dataclass
class PolicyAssignment_Overrides:
    value: Any = None
    selectors: Any = None

@dataclasses.dataclass
class PolicyAssignment_ResourceSelectors:
    name: Any = None
    selectors: Any = None

@dataclasses.dataclass
class PolicyAssignment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_PolicyAssignment_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_PolicyAssignment_NonComplianceMessageFields = {
    "content": sdk.FieldSpec(wire_name="content"),
    "policy_definition_reference_id": sdk.FieldSpec(wire_name="policy_definition_reference_id"),
}

_PolicyAssignment_Overrides_SelectorsFields = {
    "in_": sdk.FieldSpec(wire_name="in"),
    "kind": sdk.FieldSpec(wire_name="kind"),
    "not_in": sdk.FieldSpec(wire_name="not_in"),
}

_PolicyAssignment_OverridesFields = {
    "value": sdk.FieldSpec(wire_name="value"),
    "selectors": sdk.FieldSpec(
        wire_name="selectors",
        kind="list",
        fields=_PolicyAssignment_Overrides_SelectorsFields,
    ),
}

_PolicyAssignment_ResourceSelectorsFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "selectors": sdk.FieldSpec(
        wire_name="selectors",
        kind="list",
        fields=_PolicyAssignment_Overrides_SelectorsFields,
    ),
}

_PolicyAssignment_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PolicyAssignmentConfig:
    description: Any = None
    display_name: Any = None
    enforce: Any = None
    id: Any = None
    location: Any = None
    metadata: Any = None
    name: Any = None
    not_scopes: Any = None
    parameters: Any = None
    policy_definition_id: Any = None
    resource_id: Any = None
    identity: Any = None
    non_compliance_message: Any = None
    overrides: Any = None
    resource_selectors: Any = None
    timeouts: Any = None

PolicyAssignment = sdk.ResourceBinding(
    wire_type="azurerm_resource_policy_assignment",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "enforce": sdk.FieldSpec(wire_name="enforce"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "metadata": sdk.FieldSpec(wire_name="metadata"),
        "name": sdk.FieldSpec(wire_name="name"),
        "not_scopes": sdk.FieldSpec(wire_name="not_scopes"),
        "parameters": sdk.FieldSpec(wire_name="parameters"),
        "policy_definition_id": sdk.FieldSpec(wire_name="policy_definition_id"),
        "resource_id": sdk.FieldSpec(wire_name="resource_id"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_PolicyAssignment_IdentityFields,
        ),
        "non_compliance_message": sdk.FieldSpec(
            wire_name="non_compliance_message",
            kind="list",
            fields=_PolicyAssignment_NonComplianceMessageFields,
        ),
        "overrides": sdk.FieldSpec(
            wire_name="overrides",
            kind="list",
            fields=_PolicyAssignment_OverridesFields,
        ),
        "resource_selectors": sdk.FieldSpec(
            wire_name="resource_selectors",
            kind="list",
            fields=_PolicyAssignment_ResourceSelectorsFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PolicyAssignment_TimeoutsFields,
        ),
    },
)
