# Code generated by `ubx sdk gen` from azurerm_automation_connection_certificate. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ConnectionCertificate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ConnectionCertificate_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConnectionCertificateConfig:
    automation_account_name: Any = None
    automation_certificate_name: Any = None
    description: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    subscription_id: Any = None
    timeouts: Any = None

ConnectionCertificate = sdk.ResourceBinding(
    wire_type="azurerm_automation_connection_certificate",
    fields={
        "automation_account_name": sdk.FieldSpec(wire_name="automation_account_name"),
        "automation_certificate_name": sdk.FieldSpec(wire_name="automation_certificate_name"),
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "subscription_id": sdk.FieldSpec(wire_name="subscription_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ConnectionCertificate_TimeoutsFields,
        ),
    },
)
