# Code generated by `ubx sdk gen` from azurerm_automation_job_schedule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class JobSchedule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_JobSchedule_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class JobScheduleConfig:
    automation_account_name: Any = None
    id: Any = None
    job_schedule_id: Any = None
    parameters: Any = None
    resource_group_name: Any = None
    run_on: Any = None
    runbook_name: Any = None
    schedule_name: Any = None
    timeouts: Any = None

JobSchedule = sdk.ResourceBinding(
    wire_type="azurerm_automation_job_schedule",
    fields={
        "automation_account_name": sdk.FieldSpec(wire_name="automation_account_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "job_schedule_id": sdk.FieldSpec(wire_name="job_schedule_id"),
        "parameters": sdk.FieldSpec(wire_name="parameters"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "run_on": sdk.FieldSpec(wire_name="run_on"),
        "runbook_name": sdk.FieldSpec(wire_name="runbook_name"),
        "schedule_name": sdk.FieldSpec(wire_name="schedule_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_JobSchedule_TimeoutsFields,
        ),
    },
)
