# Code generated by `ubx sdk gen` from azurerm_automation_powershell72_module. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Powershell72Module_ModuleLink_Hash:
    algorithm: Any = None
    value: Any = None

@dataclasses.dataclass
class Powershell72Module_ModuleLink:
    uri: Any = None
    hash: Any = None

@dataclasses.dataclass
class Powershell72Module_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Powershell72Module_ModuleLink_HashFields = {
    "algorithm": ubx.FieldSpec(wire_name="algorithm"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_Powershell72Module_ModuleLinkFields = {
    "uri": ubx.FieldSpec(wire_name="uri"),
    "hash": ubx.FieldSpec(
        wire_name="hash",
        kind="list",
        fields=_Powershell72Module_ModuleLink_HashFields,
    ),
}

_Powershell72Module_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class Powershell72ModuleConfig:
    automation_account_id: Any = None
    id: Any = None
    name: Any = None
    tags: Any = None
    module_link: Any = None
    timeouts: Any = None

Powershell72Module = ubx.ResourceBinding(
    wire_type="azurerm_automation_powershell72_module",
    fields={
        "automation_account_id": ubx.FieldSpec(wire_name="automation_account_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "module_link": ubx.FieldSpec(
            wire_name="module_link",
            kind="list",
            fields=_Powershell72Module_ModuleLinkFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Powershell72Module_TimeoutsFields,
        ),
    },
)
