# Code generated by `ubx sdk gen` from azurerm_automation_variable_object. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VariableObject_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VariableObject_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VariableObjectConfig:
    automation_account_name: Any = None
    description: Any = None
    encrypted: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    value: Any = None
    timeouts: Any = None

VariableObject = ubx.ResourceBinding(
    wire_type="azurerm_automation_variable_object",
    fields={
        "automation_account_name": ubx.FieldSpec(wire_name="automation_account_name"),
        "description": ubx.FieldSpec(wire_name="description"),
        "encrypted": ubx.FieldSpec(wire_name="encrypted"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "value": ubx.FieldSpec(wire_name="value"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VariableObject_TimeoutsFields,
        ),
    },
)
