# Code generated by `ubx sdk gen` from azurerm_api_management_email_template. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagementEmailTemplate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagementEmailTemplate_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagementEmailTemplateConfig:
    api_management_name: Any = None
    body: Any = None
    id: Any = None
    resource_group_name: Any = None
    subject: Any = None
    template_name: Any = None
    timeouts: Any = None

ManagementEmailTemplate = ubx.ResourceBinding(
    wire_type="azurerm_api_management_email_template",
    fields={
        "api_management_name": ubx.FieldSpec(wire_name="api_management_name"),
        "body": ubx.FieldSpec(wire_name="body"),
        "id": ubx.FieldSpec(wire_name="id"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "subject": ubx.FieldSpec(wire_name="subject"),
        "template_name": ubx.FieldSpec(wire_name="template_name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementEmailTemplate_TimeoutsFields,
        ),
    },
)
