# Code generated by `ubx sdk gen` from azurerm_api_management_gateway_api. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagementGatewayApi_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_ManagementGatewayApi_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class ManagementGatewayApiConfig:
    api_id: Any = None
    gateway_id: Any = None
    id: Any = None
    timeouts: Any = None

ManagementGatewayApi = ubx.ResourceBinding(
    wire_type="azurerm_api_management_gateway_api",
    fields={
        "api_id": ubx.FieldSpec(wire_name="api_id"),
        "gateway_id": ubx.FieldSpec(wire_name="gateway_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementGatewayApi_TimeoutsFields,
        ),
    },
)
