# Code generated by `ubx sdk gen` from azurerm_api_management_standalone_gateway. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagementStandaloneGateway_Sku:
    capacity: Any = None
    name: Any = None

@dataclasses.dataclass
class ManagementStandaloneGateway_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagementStandaloneGateway_SkuFields = {
    "capacity": sdk.FieldSpec(wire_name="capacity"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_ManagementStandaloneGateway_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagementStandaloneGatewayConfig:
    backend_subnet_id: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    virtual_network_type: Any = None
    sku: Any = None
    timeouts: Any = None

ManagementStandaloneGateway = sdk.ResourceBinding(
    wire_type="azurerm_api_management_standalone_gateway",
    fields={
        "backend_subnet_id": sdk.FieldSpec(wire_name="backend_subnet_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "virtual_network_type": sdk.FieldSpec(wire_name="virtual_network_type"),
        "sku": sdk.FieldSpec(
            wire_name="sku",
            kind="list",
            fields=_ManagementStandaloneGateway_SkuFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementStandaloneGateway_TimeoutsFields,
        ),
    },
)
