# Code generated by `ubx sdk gen` from azurerm_api_management_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagementGroup_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagementGroup_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagementGroupConfig:
    api_management_name: Any = None
    description: Any = None
    display_name: Any = None
    external_id: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    type: Any = None
    timeouts: Any = None

ManagementGroup = sdk.ResourceBinding(
    wire_type="azurerm_api_management_group",
    fields={
        "api_management_name": sdk.FieldSpec(wire_name="api_management_name"),
        "description": sdk.FieldSpec(wire_name="description"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "external_id": sdk.FieldSpec(wire_name="external_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "type": sdk.FieldSpec(wire_name="type"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagementGroup_TimeoutsFields,
        ),
    },
)
