# Code generated by `ubx sdk gen` from azurerm_application_insights_workbook. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class InsightsWorkbook_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class InsightsWorkbook_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_InsightsWorkbook_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_InsightsWorkbook_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class InsightsWorkbookConfig:
    category: Any = None
    data_json: Any = None
    description: Any = None
    display_name: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    source_id: Any = None
    storage_container_id: Any = None
    tags: Any = None
    identity: Any = None
    timeouts: Any = None

InsightsWorkbook = sdk.ResourceBinding(
    wire_type="azurerm_application_insights_workbook",
    fields={
        "category": sdk.FieldSpec(wire_name="category"),
        "data_json": sdk.FieldSpec(wire_name="data_json"),
        "description": sdk.FieldSpec(wire_name="description"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "source_id": sdk.FieldSpec(wire_name="source_id"),
        "storage_container_id": sdk.FieldSpec(wire_name="storage_container_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_InsightsWorkbook_IdentityFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_InsightsWorkbook_TimeoutsFields,
        ),
    },
)
