# Code generated by `ubx sdk gen` from azurerm_logic_app_action_http. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AppActionHttp_RunAfter:
    action_name: Any = None
    action_result: Any = None

@dataclasses.dataclass
class AppActionHttp_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppActionHttp_RunAfterFields = {
    "action_name": sdk.FieldSpec(wire_name="action_name"),
    "action_result": sdk.FieldSpec(wire_name="action_result"),
}

_AppActionHttp_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppActionHttpConfig:
    body: Any = None
    headers: Any = None
    id: Any = None
    logic_app_id: Any = None
    method: Any = None
    name: Any = None
    queries: Any = None
    uri: Any = None
    run_after: Any = None
    timeouts: Any = None

AppActionHttp = sdk.ResourceBinding(
    wire_type="azurerm_logic_app_action_http",
    fields={
        "body": sdk.FieldSpec(wire_name="body"),
        "headers": sdk.FieldSpec(wire_name="headers"),
        "id": sdk.FieldSpec(wire_name="id"),
        "logic_app_id": sdk.FieldSpec(wire_name="logic_app_id"),
        "method": sdk.FieldSpec(wire_name="method"),
        "name": sdk.FieldSpec(wire_name="name"),
        "queries": sdk.FieldSpec(wire_name="queries"),
        "uri": sdk.FieldSpec(wire_name="uri"),
        "run_after": sdk.FieldSpec(
            wire_name="run_after",
            kind="set",
            fields=_AppActionHttp_RunAfterFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppActionHttp_TimeoutsFields,
        ),
    },
)
