# Code generated by `ubx sdk gen` from azurerm_hdinsight_spark_cluster. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class SparkCluster_ComponentVersion:
    spark: Any = None

@dataclasses.dataclass
class SparkCluster_ComputeIsolation:
    compute_isolation_enabled: Any = None
    host_sku: Any = None

@dataclasses.dataclass
class SparkCluster_DiskEncryption:
    encryption_algorithm: Any = None
    encryption_at_host_enabled: Any = None
    key_vault_key_id: Any = None
    key_vault_managed_identity_id: Any = None

@dataclasses.dataclass
class SparkCluster_Extension:
    log_analytics_workspace_id: Any = None
    primary_key: Any = None

@dataclasses.dataclass
class SparkCluster_Gateway:
    password: Any = None
    username: Any = None

@dataclasses.dataclass
class SparkCluster_Metastores_Ambari:
    database_name: Any = None
    password: Any = None
    server: Any = None
    username: Any = None

@dataclasses.dataclass
class SparkCluster_Metastores:
    ambari: Any = None
    hive: Any = None
    oozie: Any = None

@dataclasses.dataclass
class SparkCluster_Network:
    connection_direction: Any = None
    private_link_enabled: Any = None

@dataclasses.dataclass
class SparkCluster_PrivateLinkConfiguration_IpConfiguration:
    name: Any = None
    primary: Any = None
    private_ip_address: Any = None
    private_ip_allocation_method: Any = None
    subnet_id: Any = None

@dataclasses.dataclass
class SparkCluster_PrivateLinkConfiguration:
    group_id: Any = None
    name: Any = None
    ip_configuration: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_HeadNode_ScriptActions:
    name: Any = None
    parameters: Any = None
    uri: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_HeadNode:
    password: Any = None
    ssh_keys: Any = None
    subnet_id: Any = None
    username: Any = None
    virtual_network_id: Any = None
    vm_size: Any = None
    script_actions: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_WorkerNode_Autoscale_Capacity:
    max_instance_count: Any = None
    min_instance_count: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_WorkerNode_Autoscale_Recurrence_Schedule:
    days: Any = None
    target_instance_count: Any = None
    time: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_WorkerNode_Autoscale_Recurrence:
    timezone: Any = None
    schedule: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_WorkerNode_Autoscale:
    capacity: Any = None
    recurrence: Any = None

@dataclasses.dataclass
class SparkCluster_Roles_WorkerNode:
    password: Any = None
    ssh_keys: Any = None
    subnet_id: Any = None
    target_instance_count: Any = None
    username: Any = None
    virtual_network_id: Any = None
    vm_size: Any = None
    autoscale: Any = None
    script_actions: Any = None

@dataclasses.dataclass
class SparkCluster_Roles:
    head_node: Any = None
    worker_node: Any = None
    zookeeper_node: Any = None

@dataclasses.dataclass
class SparkCluster_SecurityProfile:
    aadds_resource_id: Any = None
    cluster_users_group_dns: Any = None
    domain_name: Any = None
    domain_user_password: Any = None
    domain_username: Any = None
    ldaps_urls: Any = None
    msi_resource_id: Any = None

@dataclasses.dataclass
class SparkCluster_StorageAccount:
    is_default: Any = None
    storage_account_id: Any = None
    storage_account_key: Any = None
    storage_container_url: Any = None

@dataclasses.dataclass
class SparkCluster_StorageAccountGen2:
    filesystem_id: Any = None
    is_default: Any = None
    storage_account_id: Any = None
    user_assigned_identity_id: Any = None

@dataclasses.dataclass
class SparkCluster_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SparkCluster_ComponentVersionFields = {
    "spark": sdk.FieldSpec(wire_name="spark"),
}

_SparkCluster_ComputeIsolationFields = {
    "compute_isolation_enabled": sdk.FieldSpec(wire_name="compute_isolation_enabled"),
    "host_sku": sdk.FieldSpec(wire_name="host_sku"),
}

_SparkCluster_DiskEncryptionFields = {
    "encryption_algorithm": sdk.FieldSpec(wire_name="encryption_algorithm"),
    "encryption_at_host_enabled": sdk.FieldSpec(wire_name="encryption_at_host_enabled"),
    "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
    "key_vault_managed_identity_id": sdk.FieldSpec(wire_name="key_vault_managed_identity_id"),
}

_SparkCluster_ExtensionFields = {
    "log_analytics_workspace_id": sdk.FieldSpec(wire_name="log_analytics_workspace_id"),
    "primary_key": sdk.FieldSpec(wire_name="primary_key"),
}

_SparkCluster_GatewayFields = {
    "password": sdk.FieldSpec(wire_name="password"),
    "username": sdk.FieldSpec(wire_name="username"),
}

_SparkCluster_Metastores_AmbariFields = {
    "database_name": sdk.FieldSpec(wire_name="database_name"),
    "password": sdk.FieldSpec(wire_name="password"),
    "server": sdk.FieldSpec(wire_name="server"),
    "username": sdk.FieldSpec(wire_name="username"),
}

_SparkCluster_MetastoresFields = {
    "ambari": sdk.FieldSpec(
        wire_name="ambari",
        kind="list",
        fields=_SparkCluster_Metastores_AmbariFields,
    ),
    "hive": sdk.FieldSpec(
        wire_name="hive",
        kind="list",
        fields=_SparkCluster_Metastores_AmbariFields,
    ),
    "oozie": sdk.FieldSpec(
        wire_name="oozie",
        kind="list",
        fields=_SparkCluster_Metastores_AmbariFields,
    ),
}

_SparkCluster_NetworkFields = {
    "connection_direction": sdk.FieldSpec(wire_name="connection_direction"),
    "private_link_enabled": sdk.FieldSpec(wire_name="private_link_enabled"),
}

_SparkCluster_PrivateLinkConfiguration_IpConfigurationFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "primary": sdk.FieldSpec(wire_name="primary"),
    "private_ip_address": sdk.FieldSpec(wire_name="private_ip_address"),
    "private_ip_allocation_method": sdk.FieldSpec(wire_name="private_ip_allocation_method"),
    "subnet_id": sdk.FieldSpec(wire_name="subnet_id"),
}

_SparkCluster_PrivateLinkConfigurationFields = {
    "group_id": sdk.FieldSpec(wire_name="group_id"),
    "name": sdk.FieldSpec(wire_name="name"),
    "ip_configuration": sdk.FieldSpec(
        wire_name="ip_configuration",
        kind="list",
        fields=_SparkCluster_PrivateLinkConfiguration_IpConfigurationFields,
    ),
}

_SparkCluster_Roles_HeadNode_ScriptActionsFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "parameters": sdk.FieldSpec(wire_name="parameters"),
    "uri": sdk.FieldSpec(wire_name="uri"),
}

_SparkCluster_Roles_HeadNodeFields = {
    "password": sdk.FieldSpec(wire_name="password"),
    "ssh_keys": sdk.FieldSpec(wire_name="ssh_keys"),
    "subnet_id": sdk.FieldSpec(wire_name="subnet_id"),
    "username": sdk.FieldSpec(wire_name="username"),
    "virtual_network_id": sdk.FieldSpec(wire_name="virtual_network_id"),
    "vm_size": sdk.FieldSpec(wire_name="vm_size"),
    "script_actions": sdk.FieldSpec(
        wire_name="script_actions",
        kind="list",
        fields=_SparkCluster_Roles_HeadNode_ScriptActionsFields,
    ),
}

_SparkCluster_Roles_WorkerNode_Autoscale_CapacityFields = {
    "max_instance_count": sdk.FieldSpec(wire_name="max_instance_count"),
    "min_instance_count": sdk.FieldSpec(wire_name="min_instance_count"),
}

_SparkCluster_Roles_WorkerNode_Autoscale_Recurrence_ScheduleFields = {
    "days": sdk.FieldSpec(wire_name="days"),
    "target_instance_count": sdk.FieldSpec(wire_name="target_instance_count"),
    "time": sdk.FieldSpec(wire_name="time"),
}

_SparkCluster_Roles_WorkerNode_Autoscale_RecurrenceFields = {
    "timezone": sdk.FieldSpec(wire_name="timezone"),
    "schedule": sdk.FieldSpec(
        wire_name="schedule",
        kind="list",
        fields=_SparkCluster_Roles_WorkerNode_Autoscale_Recurrence_ScheduleFields,
    ),
}

_SparkCluster_Roles_WorkerNode_AutoscaleFields = {
    "capacity": sdk.FieldSpec(
        wire_name="capacity",
        kind="list",
        fields=_SparkCluster_Roles_WorkerNode_Autoscale_CapacityFields,
    ),
    "recurrence": sdk.FieldSpec(
        wire_name="recurrence",
        kind="list",
        fields=_SparkCluster_Roles_WorkerNode_Autoscale_RecurrenceFields,
    ),
}

_SparkCluster_Roles_WorkerNodeFields = {
    "password": sdk.FieldSpec(wire_name="password"),
    "ssh_keys": sdk.FieldSpec(wire_name="ssh_keys"),
    "subnet_id": sdk.FieldSpec(wire_name="subnet_id"),
    "target_instance_count": sdk.FieldSpec(wire_name="target_instance_count"),
    "username": sdk.FieldSpec(wire_name="username"),
    "virtual_network_id": sdk.FieldSpec(wire_name="virtual_network_id"),
    "vm_size": sdk.FieldSpec(wire_name="vm_size"),
    "autoscale": sdk.FieldSpec(
        wire_name="autoscale",
        kind="list",
        fields=_SparkCluster_Roles_WorkerNode_AutoscaleFields,
    ),
    "script_actions": sdk.FieldSpec(
        wire_name="script_actions",
        kind="list",
        fields=_SparkCluster_Roles_HeadNode_ScriptActionsFields,
    ),
}

_SparkCluster_RolesFields = {
    "head_node": sdk.FieldSpec(
        wire_name="head_node",
        kind="list",
        fields=_SparkCluster_Roles_HeadNodeFields,
    ),
    "worker_node": sdk.FieldSpec(
        wire_name="worker_node",
        kind="list",
        fields=_SparkCluster_Roles_WorkerNodeFields,
    ),
    "zookeeper_node": sdk.FieldSpec(
        wire_name="zookeeper_node",
        kind="list",
        fields=_SparkCluster_Roles_HeadNodeFields,
    ),
}

_SparkCluster_SecurityProfileFields = {
    "aadds_resource_id": sdk.FieldSpec(wire_name="aadds_resource_id"),
    "cluster_users_group_dns": sdk.FieldSpec(wire_name="cluster_users_group_dns"),
    "domain_name": sdk.FieldSpec(wire_name="domain_name"),
    "domain_user_password": sdk.FieldSpec(wire_name="domain_user_password"),
    "domain_username": sdk.FieldSpec(wire_name="domain_username"),
    "ldaps_urls": sdk.FieldSpec(wire_name="ldaps_urls"),
    "msi_resource_id": sdk.FieldSpec(wire_name="msi_resource_id"),
}

_SparkCluster_StorageAccountFields = {
    "is_default": sdk.FieldSpec(wire_name="is_default"),
    "storage_account_id": sdk.FieldSpec(wire_name="storage_account_id"),
    "storage_account_key": sdk.FieldSpec(wire_name="storage_account_key"),
    "storage_container_url": sdk.FieldSpec(wire_name="storage_container_url"),
}

_SparkCluster_StorageAccountGen2Fields = {
    "filesystem_id": sdk.FieldSpec(wire_name="filesystem_id"),
    "is_default": sdk.FieldSpec(wire_name="is_default"),
    "storage_account_id": sdk.FieldSpec(wire_name="storage_account_id"),
    "user_assigned_identity_id": sdk.FieldSpec(wire_name="user_assigned_identity_id"),
}

_SparkCluster_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SparkClusterConfig:
    cluster_version: Any = None
    encryption_in_transit_enabled: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    tier: Any = None
    tls_min_version: Any = None
    zones: Any = None
    component_version: Any = None
    compute_isolation: Any = None
    disk_encryption: Any = None
    extension: Any = None
    gateway: Any = None
    metastores: Any = None
    monitor: Any = None
    network: Any = None
    private_link_configuration: Any = None
    roles: Any = None
    security_profile: Any = None
    storage_account: Any = None
    storage_account_gen2: Any = None
    timeouts: Any = None

SparkCluster = sdk.ResourceBinding(
    wire_type="azurerm_hdinsight_spark_cluster",
    fields={
        "cluster_version": sdk.FieldSpec(wire_name="cluster_version"),
        "encryption_in_transit_enabled": sdk.FieldSpec(wire_name="encryption_in_transit_enabled"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "tier": sdk.FieldSpec(wire_name="tier"),
        "tls_min_version": sdk.FieldSpec(wire_name="tls_min_version"),
        "zones": sdk.FieldSpec(wire_name="zones"),
        "component_version": sdk.FieldSpec(
            wire_name="component_version",
            kind="list",
            fields=_SparkCluster_ComponentVersionFields,
        ),
        "compute_isolation": sdk.FieldSpec(
            wire_name="compute_isolation",
            kind="list",
            fields=_SparkCluster_ComputeIsolationFields,
        ),
        "disk_encryption": sdk.FieldSpec(
            wire_name="disk_encryption",
            kind="list",
            fields=_SparkCluster_DiskEncryptionFields,
        ),
        "extension": sdk.FieldSpec(
            wire_name="extension",
            kind="list",
            fields=_SparkCluster_ExtensionFields,
        ),
        "gateway": sdk.FieldSpec(
            wire_name="gateway",
            kind="list",
            fields=_SparkCluster_GatewayFields,
        ),
        "metastores": sdk.FieldSpec(
            wire_name="metastores",
            kind="list",
            fields=_SparkCluster_MetastoresFields,
        ),
        "monitor": sdk.FieldSpec(
            wire_name="monitor",
            kind="list",
            fields=_SparkCluster_ExtensionFields,
        ),
        "network": sdk.FieldSpec(
            wire_name="network",
            kind="list",
            fields=_SparkCluster_NetworkFields,
        ),
        "private_link_configuration": sdk.FieldSpec(
            wire_name="private_link_configuration",
            kind="list",
            fields=_SparkCluster_PrivateLinkConfigurationFields,
        ),
        "roles": sdk.FieldSpec(
            wire_name="roles",
            kind="list",
            fields=_SparkCluster_RolesFields,
        ),
        "security_profile": sdk.FieldSpec(
            wire_name="security_profile",
            kind="list",
            fields=_SparkCluster_SecurityProfileFields,
        ),
        "storage_account": sdk.FieldSpec(
            wire_name="storage_account",
            kind="list",
            fields=_SparkCluster_StorageAccountFields,
        ),
        "storage_account_gen2": sdk.FieldSpec(
            wire_name="storage_account_gen2",
            kind="list",
            fields=_SparkCluster_StorageAccountGen2Fields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SparkCluster_TimeoutsFields,
        ),
    },
)
