# Code generated by `ubx sdk gen` from azurerm_monitor_autoscale_setting. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AutoscaleSetting_Notification_Email:
    custom_emails: Any = None
    send_to_subscription_administrator: Any = None
    send_to_subscription_co_administrator: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Notification_Webhook:
    properties: Any = None
    service_uri: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Notification:
    email: Any = None
    webhook: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Predictive:
    look_ahead_time: Any = None
    scale_mode: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Capacity:
    default: Any = None
    maximum: Any = None
    minimum: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_FixedDate:
    end: Any = None
    start: Any = None
    timezone: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Recurrence:
    days: Any = None
    hours: Any = None
    minutes: Any = None
    timezone: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Rule_MetricTrigger_Dimensions:
    name: Any = None
    operator: Any = None
    values: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Rule_MetricTrigger:
    divide_by_instance_count: Any = None
    metric_name: Any = None
    metric_namespace: Any = None
    metric_resource_id: Any = None
    operator: Any = None
    statistic: Any = None
    threshold: Any = None
    time_aggregation: Any = None
    time_grain: Any = None
    time_window: Any = None
    dimensions: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Rule_ScaleAction:
    cooldown: Any = None
    direction: Any = None
    type: Any = None
    value: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile_Rule:
    metric_trigger: Any = None
    scale_action: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Profile:
    name: Any = None
    capacity: Any = None
    fixed_date: Any = None
    recurrence: Any = None
    rule: Any = None

@dataclasses.dataclass
class AutoscaleSetting_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AutoscaleSetting_Notification_EmailFields = {
    "custom_emails": ubx.FieldSpec(wire_name="custom_emails"),
    "send_to_subscription_administrator": ubx.FieldSpec(wire_name="send_to_subscription_administrator"),
    "send_to_subscription_co_administrator": ubx.FieldSpec(wire_name="send_to_subscription_co_administrator"),
}

_AutoscaleSetting_Notification_WebhookFields = {
    "properties": ubx.FieldSpec(wire_name="properties"),
    "service_uri": ubx.FieldSpec(wire_name="service_uri"),
}

_AutoscaleSetting_NotificationFields = {
    "email": ubx.FieldSpec(
        wire_name="email",
        kind="list",
        fields=_AutoscaleSetting_Notification_EmailFields,
    ),
    "webhook": ubx.FieldSpec(
        wire_name="webhook",
        kind="list",
        fields=_AutoscaleSetting_Notification_WebhookFields,
    ),
}

_AutoscaleSetting_PredictiveFields = {
    "look_ahead_time": ubx.FieldSpec(wire_name="look_ahead_time"),
    "scale_mode": ubx.FieldSpec(wire_name="scale_mode"),
}

_AutoscaleSetting_Profile_CapacityFields = {
    "default": ubx.FieldSpec(wire_name="default"),
    "maximum": ubx.FieldSpec(wire_name="maximum"),
    "minimum": ubx.FieldSpec(wire_name="minimum"),
}

_AutoscaleSetting_Profile_FixedDateFields = {
    "end": ubx.FieldSpec(wire_name="end"),
    "start": ubx.FieldSpec(wire_name="start"),
    "timezone": ubx.FieldSpec(wire_name="timezone"),
}

_AutoscaleSetting_Profile_RecurrenceFields = {
    "days": ubx.FieldSpec(wire_name="days"),
    "hours": ubx.FieldSpec(wire_name="hours"),
    "minutes": ubx.FieldSpec(wire_name="minutes"),
    "timezone": ubx.FieldSpec(wire_name="timezone"),
}

_AutoscaleSetting_Profile_Rule_MetricTrigger_DimensionsFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "values": ubx.FieldSpec(wire_name="values"),
}

_AutoscaleSetting_Profile_Rule_MetricTriggerFields = {
    "divide_by_instance_count": ubx.FieldSpec(wire_name="divide_by_instance_count"),
    "metric_name": ubx.FieldSpec(wire_name="metric_name"),
    "metric_namespace": ubx.FieldSpec(wire_name="metric_namespace"),
    "metric_resource_id": ubx.FieldSpec(wire_name="metric_resource_id"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "statistic": ubx.FieldSpec(wire_name="statistic"),
    "threshold": ubx.FieldSpec(wire_name="threshold"),
    "time_aggregation": ubx.FieldSpec(wire_name="time_aggregation"),
    "time_grain": ubx.FieldSpec(wire_name="time_grain"),
    "time_window": ubx.FieldSpec(wire_name="time_window"),
    "dimensions": ubx.FieldSpec(
        wire_name="dimensions",
        kind="list",
        fields=_AutoscaleSetting_Profile_Rule_MetricTrigger_DimensionsFields,
    ),
}

_AutoscaleSetting_Profile_Rule_ScaleActionFields = {
    "cooldown": ubx.FieldSpec(wire_name="cooldown"),
    "direction": ubx.FieldSpec(wire_name="direction"),
    "type": ubx.FieldSpec(wire_name="type"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_AutoscaleSetting_Profile_RuleFields = {
    "metric_trigger": ubx.FieldSpec(
        wire_name="metric_trigger",
        kind="list",
        fields=_AutoscaleSetting_Profile_Rule_MetricTriggerFields,
    ),
    "scale_action": ubx.FieldSpec(
        wire_name="scale_action",
        kind="list",
        fields=_AutoscaleSetting_Profile_Rule_ScaleActionFields,
    ),
}

_AutoscaleSetting_ProfileFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "capacity": ubx.FieldSpec(
        wire_name="capacity",
        kind="list",
        fields=_AutoscaleSetting_Profile_CapacityFields,
    ),
    "fixed_date": ubx.FieldSpec(
        wire_name="fixed_date",
        kind="list",
        fields=_AutoscaleSetting_Profile_FixedDateFields,
    ),
    "recurrence": ubx.FieldSpec(
        wire_name="recurrence",
        kind="list",
        fields=_AutoscaleSetting_Profile_RecurrenceFields,
    ),
    "rule": ubx.FieldSpec(
        wire_name="rule",
        kind="list",
        fields=_AutoscaleSetting_Profile_RuleFields,
    ),
}

_AutoscaleSetting_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AutoscaleSettingConfig:
    enabled: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    target_resource_id: Any = None
    notification: Any = None
    predictive: Any = None
    profile: Any = None
    timeouts: Any = None

AutoscaleSetting = ubx.ResourceBinding(
    wire_type="azurerm_monitor_autoscale_setting",
    fields={
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "target_resource_id": ubx.FieldSpec(wire_name="target_resource_id"),
        "notification": ubx.FieldSpec(
            wire_name="notification",
            kind="list",
            fields=_AutoscaleSetting_NotificationFields,
        ),
        "predictive": ubx.FieldSpec(
            wire_name="predictive",
            kind="list",
            fields=_AutoscaleSetting_PredictiveFields,
        ),
        "profile": ubx.FieldSpec(
            wire_name="profile",
            kind="list",
            fields=_AutoscaleSetting_ProfileFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AutoscaleSetting_TimeoutsFields,
        ),
    },
)
