# Code generated by `ubx sdk gen` from azurerm_monitor_scheduled_query_rules_log. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ScheduledQueryRulesLog_Criteria_Dimension:
    name: Any = None
    operator: Any = None
    values: Any = None

@dataclasses.dataclass
class ScheduledQueryRulesLog_Criteria:
    metric_name: Any = None
    dimension: Any = None

@dataclasses.dataclass
class ScheduledQueryRulesLog_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ScheduledQueryRulesLog_Criteria_DimensionFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "values": ubx.FieldSpec(wire_name="values"),
}

_ScheduledQueryRulesLog_CriteriaFields = {
    "metric_name": ubx.FieldSpec(wire_name="metric_name"),
    "dimension": ubx.FieldSpec(
        wire_name="dimension",
        kind="set",
        fields=_ScheduledQueryRulesLog_Criteria_DimensionFields,
    ),
}

_ScheduledQueryRulesLog_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ScheduledQueryRulesLogConfig:
    authorized_resource_ids: Any = None
    data_source_id: Any = None
    description: Any = None
    enabled: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    criteria: Any = None
    timeouts: Any = None

ScheduledQueryRulesLog = ubx.ResourceBinding(
    wire_type="azurerm_monitor_scheduled_query_rules_log",
    fields={
        "authorized_resource_ids": ubx.FieldSpec(wire_name="authorized_resource_ids"),
        "data_source_id": ubx.FieldSpec(wire_name="data_source_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "criteria": ubx.FieldSpec(
            wire_name="criteria",
            kind="list",
            fields=_ScheduledQueryRulesLog_CriteriaFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ScheduledQueryRulesLog_TimeoutsFields,
        ),
    },
)
