# Code generated by `ubx sdk gen` from azurerm_databricks_workspace_root_dbfs_customer_managed_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class WorkspaceRootDbfsCustomerManagedKey_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_WorkspaceRootDbfsCustomerManagedKey_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class WorkspaceRootDbfsCustomerManagedKeyConfig:
    id: Any = None
    key_vault_id: Any = None
    key_vault_key_id: Any = None
    workspace_id: Any = None
    timeouts: Any = None

WorkspaceRootDbfsCustomerManagedKey = sdk.ResourceBinding(
    wire_type="azurerm_databricks_workspace_root_dbfs_customer_managed_key",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "key_vault_id": sdk.FieldSpec(wire_name="key_vault_id"),
        "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
        "workspace_id": sdk.FieldSpec(wire_name="workspace_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_WorkspaceRootDbfsCustomerManagedKey_TimeoutsFields,
        ),
    },
)
