# Code generated by `ubx sdk gen` from azurerm_mssql_database. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Database_Identity:
    identity_ids: Any = None
    type: Any = None

@dataclasses.dataclass
class Database_Import:
    administrator_login: Any = None
    administrator_login_password: Any = None
    authentication_type: Any = None
    storage_account_id: Any = None
    storage_key: Any = None
    storage_key_type: Any = None
    storage_uri: Any = None

@dataclasses.dataclass
class Database_LongTermRetentionPolicy:
    monthly_retention: Any = None
    week_of_year: Any = None
    weekly_retention: Any = None
    yearly_retention: Any = None

@dataclasses.dataclass
class Database_ShortTermRetentionPolicy:
    backup_interval_in_hours: Any = None
    retention_days: Any = None

@dataclasses.dataclass
class Database_ThreatDetectionPolicy:
    disabled_alerts: Any = None
    email_account_admins_enabled: Any = None
    email_addresses: Any = None
    retention_days: Any = None
    state: Any = None
    storage_account_access_key: Any = None
    storage_endpoint: Any = None

@dataclasses.dataclass
class Database_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Database_IdentityFields = {
    "identity_ids": ubx.FieldSpec(wire_name="identity_ids"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_Database_ImportFields = {
    "administrator_login": ubx.FieldSpec(wire_name="administrator_login"),
    "administrator_login_password": ubx.FieldSpec(wire_name="administrator_login_password"),
    "authentication_type": ubx.FieldSpec(wire_name="authentication_type"),
    "storage_account_id": ubx.FieldSpec(wire_name="storage_account_id"),
    "storage_key": ubx.FieldSpec(wire_name="storage_key"),
    "storage_key_type": ubx.FieldSpec(wire_name="storage_key_type"),
    "storage_uri": ubx.FieldSpec(wire_name="storage_uri"),
}

_Database_LongTermRetentionPolicyFields = {
    "monthly_retention": ubx.FieldSpec(wire_name="monthly_retention"),
    "week_of_year": ubx.FieldSpec(wire_name="week_of_year"),
    "weekly_retention": ubx.FieldSpec(wire_name="weekly_retention"),
    "yearly_retention": ubx.FieldSpec(wire_name="yearly_retention"),
}

_Database_ShortTermRetentionPolicyFields = {
    "backup_interval_in_hours": ubx.FieldSpec(wire_name="backup_interval_in_hours"),
    "retention_days": ubx.FieldSpec(wire_name="retention_days"),
}

_Database_ThreatDetectionPolicyFields = {
    "disabled_alerts": ubx.FieldSpec(wire_name="disabled_alerts"),
    "email_account_admins_enabled": ubx.FieldSpec(wire_name="email_account_admins_enabled"),
    "email_addresses": ubx.FieldSpec(wire_name="email_addresses"),
    "retention_days": ubx.FieldSpec(wire_name="retention_days"),
    "state": ubx.FieldSpec(wire_name="state"),
    "storage_account_access_key": ubx.FieldSpec(wire_name="storage_account_access_key"),
    "storage_endpoint": ubx.FieldSpec(wire_name="storage_endpoint"),
}

_Database_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DatabaseConfig:
    auto_pause_delay_in_minutes: Any = None
    collation: Any = None
    create_mode: Any = None
    creation_source_database_id: Any = None
    elastic_pool_id: Any = None
    enclave_type: Any = None
    geo_backup_enabled: Any = None
    id: Any = None
    ledger_enabled: Any = None
    license_type: Any = None
    maintenance_configuration_name: Any = None
    max_size_gb: Any = None
    min_capacity: Any = None
    name: Any = None
    read_replica_count: Any = None
    read_scale: Any = None
    recover_database_id: Any = None
    recovery_point_id: Any = None
    restore_dropped_database_id: Any = None
    restore_long_term_retention_backup_id: Any = None
    restore_point_in_time: Any = None
    sample_name: Any = None
    secondary_type: Any = None
    server_id: Any = None
    sku_name: Any = None
    storage_account_type: Any = None
    tags: Any = None
    transparent_data_encryption_enabled: Any = None
    transparent_data_encryption_key_automatic_rotation_enabled: Any = None
    transparent_data_encryption_key_vault_key_id: Any = None
    zone_redundant: Any = None
    identity: Any = None
    import_: Any = None
    long_term_retention_policy: Any = None
    short_term_retention_policy: Any = None
    threat_detection_policy: Any = None
    timeouts: Any = None

Database = ubx.ResourceBinding(
    wire_type="azurerm_mssql_database",
    fields={
        "auto_pause_delay_in_minutes": ubx.FieldSpec(wire_name="auto_pause_delay_in_minutes"),
        "collation": ubx.FieldSpec(wire_name="collation"),
        "create_mode": ubx.FieldSpec(wire_name="create_mode"),
        "creation_source_database_id": ubx.FieldSpec(wire_name="creation_source_database_id"),
        "elastic_pool_id": ubx.FieldSpec(wire_name="elastic_pool_id"),
        "enclave_type": ubx.FieldSpec(wire_name="enclave_type"),
        "geo_backup_enabled": ubx.FieldSpec(wire_name="geo_backup_enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "ledger_enabled": ubx.FieldSpec(wire_name="ledger_enabled"),
        "license_type": ubx.FieldSpec(wire_name="license_type"),
        "maintenance_configuration_name": ubx.FieldSpec(wire_name="maintenance_configuration_name"),
        "max_size_gb": ubx.FieldSpec(wire_name="max_size_gb"),
        "min_capacity": ubx.FieldSpec(wire_name="min_capacity"),
        "name": ubx.FieldSpec(wire_name="name"),
        "read_replica_count": ubx.FieldSpec(wire_name="read_replica_count"),
        "read_scale": ubx.FieldSpec(wire_name="read_scale"),
        "recover_database_id": ubx.FieldSpec(wire_name="recover_database_id"),
        "recovery_point_id": ubx.FieldSpec(wire_name="recovery_point_id"),
        "restore_dropped_database_id": ubx.FieldSpec(wire_name="restore_dropped_database_id"),
        "restore_long_term_retention_backup_id": ubx.FieldSpec(wire_name="restore_long_term_retention_backup_id"),
        "restore_point_in_time": ubx.FieldSpec(wire_name="restore_point_in_time"),
        "sample_name": ubx.FieldSpec(wire_name="sample_name"),
        "secondary_type": ubx.FieldSpec(wire_name="secondary_type"),
        "server_id": ubx.FieldSpec(wire_name="server_id"),
        "sku_name": ubx.FieldSpec(wire_name="sku_name"),
        "storage_account_type": ubx.FieldSpec(wire_name="storage_account_type"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "transparent_data_encryption_enabled": ubx.FieldSpec(wire_name="transparent_data_encryption_enabled"),
        "transparent_data_encryption_key_automatic_rotation_enabled": ubx.FieldSpec(wire_name="transparent_data_encryption_key_automatic_rotation_enabled"),
        "transparent_data_encryption_key_vault_key_id": ubx.FieldSpec(wire_name="transparent_data_encryption_key_vault_key_id"),
        "zone_redundant": ubx.FieldSpec(wire_name="zone_redundant"),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_Database_IdentityFields,
        ),
        "import_": ubx.FieldSpec(
            wire_name="import",
            kind="list",
            fields=_Database_ImportFields,
        ),
        "long_term_retention_policy": ubx.FieldSpec(
            wire_name="long_term_retention_policy",
            kind="list",
            fields=_Database_LongTermRetentionPolicyFields,
        ),
        "short_term_retention_policy": ubx.FieldSpec(
            wire_name="short_term_retention_policy",
            kind="list",
            fields=_Database_ShortTermRetentionPolicyFields,
        ),
        "threat_detection_policy": ubx.FieldSpec(
            wire_name="threat_detection_policy",
            kind="list",
            fields=_Database_ThreatDetectionPolicyFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Database_TimeoutsFields,
        ),
    },
)
