# Code generated by `ubx sdk gen` from azurerm_mssql_managed_instance_security_alert_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagedInstanceSecurityAlertPolicy_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagedInstanceSecurityAlertPolicy_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagedInstanceSecurityAlertPolicyConfig:
    disabled_alerts: Any = None
    email_account_admins_enabled: Any = None
    email_addresses: Any = None
    enabled: Any = None
    id: Any = None
    managed_instance_name: Any = None
    resource_group_name: Any = None
    retention_days: Any = None
    storage_account_access_key: Any = None
    storage_endpoint: Any = None
    timeouts: Any = None

ManagedInstanceSecurityAlertPolicy = ubx.ResourceBinding(
    wire_type="azurerm_mssql_managed_instance_security_alert_policy",
    fields={
        "disabled_alerts": ubx.FieldSpec(wire_name="disabled_alerts"),
        "email_account_admins_enabled": ubx.FieldSpec(wire_name="email_account_admins_enabled"),
        "email_addresses": ubx.FieldSpec(wire_name="email_addresses"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "managed_instance_name": ubx.FieldSpec(wire_name="managed_instance_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "retention_days": ubx.FieldSpec(wire_name="retention_days"),
        "storage_account_access_key": ubx.FieldSpec(wire_name="storage_account_access_key"),
        "storage_endpoint": ubx.FieldSpec(wire_name="storage_endpoint"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagedInstanceSecurityAlertPolicy_TimeoutsFields,
        ),
    },
)
