# Code generated by `ubx sdk gen` from azurerm_mssql_server. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Server_AzureadAdministrator:
    azuread_authentication_only: Any = None
    login_username: Any = None
    object_id: Any = None
    tenant_id: Any = None

@dataclasses.dataclass
class Server_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class Server_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Server_AzureadAdministratorFields = {
    "azuread_authentication_only": ubx.FieldSpec(wire_name="azuread_authentication_only"),
    "login_username": ubx.FieldSpec(wire_name="login_username"),
    "object_id": ubx.FieldSpec(wire_name="object_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
}

_Server_IdentityFields = {
    "identity_ids": ubx.FieldSpec(wire_name="identity_ids"),
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_Server_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ServerConfig:
    administrator_login: Any = None
    administrator_login_password: Any = None
    administrator_login_password_wo: Any = None
    administrator_login_password_wo_version: Any = None
    connection_policy: Any = None
    express_vulnerability_assessment_enabled: Any = None
    id: Any = None
    location: Any = None
    minimum_tls_version: Any = None
    name: Any = None
    outbound_network_restriction_enabled: Any = None
    primary_user_assigned_identity_id: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    tags: Any = None
    transparent_data_encryption_key_vault_key_id: Any = None
    version: Any = None
    azuread_administrator: Any = None
    identity: Any = None
    timeouts: Any = None

Server = ubx.ResourceBinding(
    wire_type="azurerm_mssql_server",
    fields={
        "administrator_login": ubx.FieldSpec(wire_name="administrator_login"),
        "administrator_login_password": ubx.FieldSpec(wire_name="administrator_login_password"),
        "administrator_login_password_wo": ubx.FieldSpec(wire_name="administrator_login_password_wo"),
        "administrator_login_password_wo_version": ubx.FieldSpec(wire_name="administrator_login_password_wo_version"),
        "connection_policy": ubx.FieldSpec(wire_name="connection_policy"),
        "express_vulnerability_assessment_enabled": ubx.FieldSpec(wire_name="express_vulnerability_assessment_enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "minimum_tls_version": ubx.FieldSpec(wire_name="minimum_tls_version"),
        "name": ubx.FieldSpec(wire_name="name"),
        "outbound_network_restriction_enabled": ubx.FieldSpec(wire_name="outbound_network_restriction_enabled"),
        "primary_user_assigned_identity_id": ubx.FieldSpec(wire_name="primary_user_assigned_identity_id"),
        "public_network_access_enabled": ubx.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "transparent_data_encryption_key_vault_key_id": ubx.FieldSpec(wire_name="transparent_data_encryption_key_vault_key_id"),
        "version": ubx.FieldSpec(wire_name="version"),
        "azuread_administrator": ubx.FieldSpec(
            wire_name="azuread_administrator",
            kind="list",
            fields=_Server_AzureadAdministratorFields,
        ),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_Server_IdentityFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Server_TimeoutsFields,
        ),
    },
)
