# Code generated by `ubx sdk gen` from azurerm_mssql_virtual_network_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class VirtualNetworkRule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VirtualNetworkRule_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VirtualNetworkRuleConfig:
    id: Any = None
    ignore_missing_vnet_service_endpoint: Any = None
    name: Any = None
    server_id: Any = None
    subnet_id: Any = None
    timeouts: Any = None

VirtualNetworkRule = sdk.ResourceBinding(
    wire_type="azurerm_mssql_virtual_network_rule",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "ignore_missing_vnet_service_endpoint": sdk.FieldSpec(wire_name="ignore_missing_vnet_service_endpoint"),
        "name": sdk.FieldSpec(wire_name="name"),
        "server_id": sdk.FieldSpec(wire_name="server_id"),
        "subnet_id": sdk.FieldSpec(wire_name="subnet_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VirtualNetworkRule_TimeoutsFields,
        ),
    },
)
