# Code generated by `ubx sdk gen` from azurerm_spring_cloud_active_deployment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CloudActiveDeployment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CloudActiveDeployment_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CloudActiveDeploymentConfig:
    deployment_name: Any = None
    id: Any = None
    spring_cloud_app_id: Any = None
    timeouts: Any = None

CloudActiveDeployment = ubx.ResourceBinding(
    wire_type="azurerm_spring_cloud_active_deployment",
    fields={
        "deployment_name": ubx.FieldSpec(wire_name="deployment_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "spring_cloud_app_id": ubx.FieldSpec(wire_name="spring_cloud_app_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CloudActiveDeployment_TimeoutsFields,
        ),
    },
)
