# Code generated by `ubx sdk gen` from azurerm_spring_cloud_storage. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CloudStorage_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CloudStorage_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CloudStorageConfig:
    id: Any = None
    name: Any = None
    spring_cloud_service_id: Any = None
    storage_account_key: Any = None
    storage_account_name: Any = None
    timeouts: Any = None

CloudStorage = sdk.ResourceBinding(
    wire_type="azurerm_spring_cloud_storage",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "spring_cloud_service_id": sdk.FieldSpec(wire_name="spring_cloud_service_id"),
        "storage_account_key": sdk.FieldSpec(wire_name="storage_account_key"),
        "storage_account_name": sdk.FieldSpec(wire_name="storage_account_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CloudStorage_TimeoutsFields,
        ),
    },
)
