# Code generated by `ubx sdk gen` from azurerm_spring_cloud_container_deployment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CloudContainerDeployment_Quota:
    cpu: Any = None
    memory: Any = None

@dataclasses.dataclass
class CloudContainerDeployment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CloudContainerDeployment_QuotaFields = {
    "cpu": sdk.FieldSpec(wire_name="cpu"),
    "memory": sdk.FieldSpec(wire_name="memory"),
}

_CloudContainerDeployment_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CloudContainerDeploymentConfig:
    addon_json: Any = None
    application_performance_monitoring_ids: Any = None
    arguments: Any = None
    commands: Any = None
    environment_variables: Any = None
    id: Any = None
    image: Any = None
    instance_count: Any = None
    language_framework: Any = None
    name: Any = None
    server: Any = None
    spring_cloud_app_id: Any = None
    quota: Any = None
    timeouts: Any = None

CloudContainerDeployment = sdk.ResourceBinding(
    wire_type="azurerm_spring_cloud_container_deployment",
    fields={
        "addon_json": sdk.FieldSpec(wire_name="addon_json"),
        "application_performance_monitoring_ids": sdk.FieldSpec(wire_name="application_performance_monitoring_ids"),
        "arguments": sdk.FieldSpec(wire_name="arguments"),
        "commands": sdk.FieldSpec(wire_name="commands"),
        "environment_variables": sdk.FieldSpec(wire_name="environment_variables"),
        "id": sdk.FieldSpec(wire_name="id"),
        "image": sdk.FieldSpec(wire_name="image"),
        "instance_count": sdk.FieldSpec(wire_name="instance_count"),
        "language_framework": sdk.FieldSpec(wire_name="language_framework"),
        "name": sdk.FieldSpec(wire_name="name"),
        "server": sdk.FieldSpec(wire_name="server"),
        "spring_cloud_app_id": sdk.FieldSpec(wire_name="spring_cloud_app_id"),
        "quota": sdk.FieldSpec(
            wire_name="quota",
            kind="list",
            fields=_CloudContainerDeployment_QuotaFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CloudContainerDeployment_TimeoutsFields,
        ),
    },
)
