# Code generated by `ubx sdk gen` from azurerm_oracle_autonomous_database_backup. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AutonomousDatabaseBackup_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AutonomousDatabaseBackup_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AutonomousDatabaseBackupConfig:
    autonomous_database_id: Any = None
    id: Any = None
    name: Any = None
    retention_period_in_days: Any = None
    type: Any = None
    timeouts: Any = None

AutonomousDatabaseBackup = ubx.ResourceBinding(
    wire_type="azurerm_oracle_autonomous_database_backup",
    fields={
        "autonomous_database_id": ubx.FieldSpec(wire_name="autonomous_database_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "retention_period_in_days": ubx.FieldSpec(wire_name="retention_period_in_days"),
        "type": ubx.FieldSpec(wire_name="type"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AutonomousDatabaseBackup_TimeoutsFields,
        ),
    },
)
