# Code generated by `ubx sdk gen` from azurerm_redis_linked_server. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class LinkedServer_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_LinkedServer_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class LinkedServerConfig:
    id: Any = None
    linked_redis_cache_id: Any = None
    linked_redis_cache_location: Any = None
    resource_group_name: Any = None
    server_role: Any = None
    target_redis_cache_name: Any = None
    timeouts: Any = None

LinkedServer = sdk.ResourceBinding(
    wire_type="azurerm_redis_linked_server",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "linked_redis_cache_id": sdk.FieldSpec(wire_name="linked_redis_cache_id"),
        "linked_redis_cache_location": sdk.FieldSpec(wire_name="linked_redis_cache_location"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "server_role": sdk.FieldSpec(wire_name="server_role"),
        "target_redis_cache_name": sdk.FieldSpec(wire_name="target_redis_cache_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LinkedServer_TimeoutsFields,
        ),
    },
)
