# Code generated by `ubx sdk gen` from azurerm_network_interface_application_security_group_association. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class InterfaceApplicationSecurityGroupAssociation_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_InterfaceApplicationSecurityGroupAssociation_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class InterfaceApplicationSecurityGroupAssociationConfig:
    application_security_group_id: Any = None
    id: Any = None
    network_interface_id: Any = None
    timeouts: Any = None

InterfaceApplicationSecurityGroupAssociation = sdk.ResourceBinding(
    wire_type="azurerm_network_interface_application_security_group_association",
    fields={
        "application_security_group_id": sdk.FieldSpec(wire_name="application_security_group_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "network_interface_id": sdk.FieldSpec(wire_name="network_interface_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_InterfaceApplicationSecurityGroupAssociation_TimeoutsFields,
        ),
    },
)
