# Code generated by `ubx sdk gen` from azurerm_network_manager_deployment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagerDeployment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagerDeployment_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagerDeploymentConfig:
    configuration_ids: Any = None
    id: Any = None
    location: Any = None
    network_manager_id: Any = None
    scope_access: Any = None
    triggers: Any = None
    timeouts: Any = None

ManagerDeployment = sdk.ResourceBinding(
    wire_type="azurerm_network_manager_deployment",
    fields={
        "configuration_ids": sdk.FieldSpec(wire_name="configuration_ids"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "network_manager_id": sdk.FieldSpec(wire_name="network_manager_id"),
        "scope_access": sdk.FieldSpec(wire_name="scope_access"),
        "triggers": sdk.FieldSpec(wire_name="triggers"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagerDeployment_TimeoutsFields,
        ),
    },
)
