# Code generated by `ubx sdk gen` from azurerm_network_manager_admin_rule_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ManagerAdminRuleCollection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagerAdminRuleCollection_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagerAdminRuleCollectionConfig:
    description: Any = None
    id: Any = None
    name: Any = None
    network_group_ids: Any = None
    security_admin_configuration_id: Any = None
    timeouts: Any = None

ManagerAdminRuleCollection = sdk.ResourceBinding(
    wire_type="azurerm_network_manager_admin_rule_collection",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "network_group_ids": sdk.FieldSpec(wire_name="network_group_ids"),
        "security_admin_configuration_id": sdk.FieldSpec(wire_name="security_admin_configuration_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagerAdminRuleCollection_TimeoutsFields,
        ),
    },
)
