# Code generated by `ubx sdk gen` from azurerm_network_manager_admin_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagerAdminRule_Destination:
    address_prefix: Any = None
    address_prefix_type: Any = None

@dataclasses.dataclass
class ManagerAdminRule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagerAdminRule_DestinationFields = {
    "address_prefix": ubx.FieldSpec(wire_name="address_prefix"),
    "address_prefix_type": ubx.FieldSpec(wire_name="address_prefix_type"),
}

_ManagerAdminRule_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagerAdminRuleConfig:
    action: Any = None
    admin_rule_collection_id: Any = None
    description: Any = None
    destination_port_ranges: Any = None
    direction: Any = None
    id: Any = None
    name: Any = None
    priority: Any = None
    protocol: Any = None
    source_port_ranges: Any = None
    destination: Any = None
    source: Any = None
    timeouts: Any = None

ManagerAdminRule = ubx.ResourceBinding(
    wire_type="azurerm_network_manager_admin_rule",
    fields={
        "action": ubx.FieldSpec(wire_name="action"),
        "admin_rule_collection_id": ubx.FieldSpec(wire_name="admin_rule_collection_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "destination_port_ranges": ubx.FieldSpec(wire_name="destination_port_ranges"),
        "direction": ubx.FieldSpec(wire_name="direction"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "priority": ubx.FieldSpec(wire_name="priority"),
        "protocol": ubx.FieldSpec(wire_name="protocol"),
        "source_port_ranges": ubx.FieldSpec(wire_name="source_port_ranges"),
        "destination": ubx.FieldSpec(
            wire_name="destination",
            kind="list",
            fields=_ManagerAdminRule_DestinationFields,
        ),
        "source": ubx.FieldSpec(
            wire_name="source",
            kind="list",
            fields=_ManagerAdminRule_DestinationFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagerAdminRule_TimeoutsFields,
        ),
    },
)
