# Code generated by `ubx sdk gen` from azurerm_network_manager_scope_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ManagerScopeConnection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ManagerScopeConnection_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ManagerScopeConnectionConfig:
    description: Any = None
    id: Any = None
    name: Any = None
    network_manager_id: Any = None
    target_scope_id: Any = None
    tenant_id: Any = None
    timeouts: Any = None

ManagerScopeConnection = ubx.ResourceBinding(
    wire_type="azurerm_network_manager_scope_connection",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "network_manager_id": ubx.FieldSpec(wire_name="network_manager_id"),
        "target_scope_id": ubx.FieldSpec(wire_name="target_scope_id"),
        "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ManagerScopeConnection_TimeoutsFields,
        ),
    },
)
