# Code generated by `ubx sdk gen` from azurerm_signalr_service_custom_certificate. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceCustomCertificate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_ServiceCustomCertificate_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class ServiceCustomCertificateConfig:
    custom_certificate_id: Any = None
    id: Any = None
    name: Any = None
    signalr_service_id: Any = None
    timeouts: Any = None

ServiceCustomCertificate = ubx.ResourceBinding(
    wire_type="azurerm_signalr_service_custom_certificate",
    fields={
        "custom_certificate_id": ubx.FieldSpec(wire_name="custom_certificate_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "signalr_service_id": ubx.FieldSpec(wire_name="signalr_service_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ServiceCustomCertificate_TimeoutsFields,
        ),
    },
)
