# Code generated by `ubx sdk gen` from azurerm_iothub_dps. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Dps_IpFilterRule:
    action: Any = None
    ip_mask: Any = None
    name: Any = None
    target: Any = None

@dataclasses.dataclass
class Dps_LinkedHub:
    allocation_weight: Any = None
    apply_allocation_policy: Any = None
    connection_string: Any = None
    hostname: Any = None
    location: Any = None

@dataclasses.dataclass
class Dps_Sku:
    capacity: Any = None
    name: Any = None

@dataclasses.dataclass
class Dps_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Dps_IpFilterRuleFields = {
    "action": sdk.FieldSpec(wire_name="action"),
    "ip_mask": sdk.FieldSpec(wire_name="ip_mask"),
    "name": sdk.FieldSpec(wire_name="name"),
    "target": sdk.FieldSpec(wire_name="target"),
}

_Dps_LinkedHubFields = {
    "allocation_weight": sdk.FieldSpec(wire_name="allocation_weight"),
    "apply_allocation_policy": sdk.FieldSpec(wire_name="apply_allocation_policy"),
    "connection_string": sdk.FieldSpec(wire_name="connection_string"),
    "hostname": sdk.FieldSpec(wire_name="hostname"),
    "location": sdk.FieldSpec(wire_name="location"),
}

_Dps_SkuFields = {
    "capacity": sdk.FieldSpec(wire_name="capacity"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_Dps_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DpsConfig:
    allocation_policy: Any = None
    data_residency_enabled: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    tags: Any = None
    ip_filter_rule: Any = None
    linked_hub: Any = None
    sku: Any = None
    timeouts: Any = None

Dps = sdk.ResourceBinding(
    wire_type="azurerm_iothub_dps",
    fields={
        "allocation_policy": sdk.FieldSpec(wire_name="allocation_policy"),
        "data_residency_enabled": sdk.FieldSpec(wire_name="data_residency_enabled"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "public_network_access_enabled": sdk.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "ip_filter_rule": sdk.FieldSpec(
            wire_name="ip_filter_rule",
            kind="list",
            fields=_Dps_IpFilterRuleFields,
        ),
        "linked_hub": sdk.FieldSpec(
            wire_name="linked_hub",
            kind="list",
            fields=_Dps_LinkedHubFields,
        ),
        "sku": sdk.FieldSpec(
            wire_name="sku",
            kind="list",
            fields=_Dps_SkuFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Dps_TimeoutsFields,
        ),
    },
)
