# Code generated by `ubx sdk gen` from azurerm_nginx_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Configuration_ConfigFile:
    content: Any = None
    virtual_path: Any = None

@dataclasses.dataclass
class Configuration_ProtectedFile:
    content: Any = None
    content_hash: Any = None
    virtual_path: Any = None

@dataclasses.dataclass
class Configuration_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Configuration_ConfigFileFields = {
    "content": ubx.FieldSpec(wire_name="content"),
    "virtual_path": ubx.FieldSpec(wire_name="virtual_path"),
}

_Configuration_ProtectedFileFields = {
    "content": ubx.FieldSpec(wire_name="content"),
    "content_hash": ubx.FieldSpec(wire_name="content_hash"),
    "virtual_path": ubx.FieldSpec(wire_name="virtual_path"),
}

_Configuration_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConfigurationConfig:
    id: Any = None
    nginx_deployment_id: Any = None
    package_data: Any = None
    root_file: Any = None
    config_file: Any = None
    protected_file: Any = None
    timeouts: Any = None

Configuration = ubx.ResourceBinding(
    wire_type="azurerm_nginx_configuration",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "nginx_deployment_id": ubx.FieldSpec(wire_name="nginx_deployment_id"),
        "package_data": ubx.FieldSpec(wire_name="package_data"),
        "root_file": ubx.FieldSpec(wire_name="root_file"),
        "config_file": ubx.FieldSpec(
            wire_name="config_file",
            kind="set",
            fields=_Configuration_ConfigFileFields,
        ),
        "protected_file": ubx.FieldSpec(
            wire_name="protected_file",
            kind="set",
            fields=_Configuration_ProtectedFileFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Configuration_TimeoutsFields,
        ),
    },
)
