# Code generated by `ubx sdk gen` from azurerm_security_center_automation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CenterAutomation_Action:
    connection_string: Any = None
    resource_id: Any = None
    trigger_url: Any = None
    type: Any = None

@dataclasses.dataclass
class CenterAutomation_Source_RuleSet_Rule:
    expected_value: Any = None
    operator: Any = None
    property_path: Any = None
    property_type: Any = None

@dataclasses.dataclass
class CenterAutomation_Source_RuleSet:
    rule: Any = None

@dataclasses.dataclass
class CenterAutomation_Source:
    event_source: Any = None
    rule_set: Any = None

@dataclasses.dataclass
class CenterAutomation_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterAutomation_ActionFields = {
    "connection_string": ubx.FieldSpec(wire_name="connection_string"),
    "resource_id": ubx.FieldSpec(wire_name="resource_id"),
    "trigger_url": ubx.FieldSpec(wire_name="trigger_url"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_CenterAutomation_Source_RuleSet_RuleFields = {
    "expected_value": ubx.FieldSpec(wire_name="expected_value"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "property_path": ubx.FieldSpec(wire_name="property_path"),
    "property_type": ubx.FieldSpec(wire_name="property_type"),
}

_CenterAutomation_Source_RuleSetFields = {
    "rule": ubx.FieldSpec(
        wire_name="rule",
        kind="list",
        fields=_CenterAutomation_Source_RuleSet_RuleFields,
    ),
}

_CenterAutomation_SourceFields = {
    "event_source": ubx.FieldSpec(wire_name="event_source"),
    "rule_set": ubx.FieldSpec(
        wire_name="rule_set",
        kind="list",
        fields=_CenterAutomation_Source_RuleSetFields,
    ),
}

_CenterAutomation_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterAutomationConfig:
    description: Any = None
    enabled: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    scopes: Any = None
    tags: Any = None
    action: Any = None
    source: Any = None
    timeouts: Any = None

CenterAutomation = ubx.ResourceBinding(
    wire_type="azurerm_security_center_automation",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "scopes": ubx.FieldSpec(wire_name="scopes"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "action": ubx.FieldSpec(
            wire_name="action",
            kind="list",
            fields=_CenterAutomation_ActionFields,
        ),
        "source": ubx.FieldSpec(
            wire_name="source",
            kind="list",
            fields=_CenterAutomation_SourceFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterAutomation_TimeoutsFields,
        ),
    },
)
