# Code generated by `ubx sdk gen` from azurerm_security_center_assessment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CenterAssessment_Status:
    cause: Any = None
    code: Any = None
    description: Any = None

@dataclasses.dataclass
class CenterAssessment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterAssessment_StatusFields = {
    "cause": ubx.FieldSpec(wire_name="cause"),
    "code": ubx.FieldSpec(wire_name="code"),
    "description": ubx.FieldSpec(wire_name="description"),
}

_CenterAssessment_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterAssessmentConfig:
    additional_data: Any = None
    assessment_policy_id: Any = None
    id: Any = None
    target_resource_id: Any = None
    status: Any = None
    timeouts: Any = None

CenterAssessment = ubx.ResourceBinding(
    wire_type="azurerm_security_center_assessment",
    fields={
        "additional_data": ubx.FieldSpec(wire_name="additional_data"),
        "assessment_policy_id": ubx.FieldSpec(wire_name="assessment_policy_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "target_resource_id": ubx.FieldSpec(wire_name="target_resource_id"),
        "status": ubx.FieldSpec(
            wire_name="status",
            kind="list",
            fields=_CenterAssessment_StatusFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterAssessment_TimeoutsFields,
        ),
    },
)
