# Code generated by `ubx sdk gen` from azurerm_security_center_workspace. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CenterWorkspace_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterWorkspace_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterWorkspaceConfig:
    id: Any = None
    scope: Any = None
    workspace_id: Any = None
    timeouts: Any = None

CenterWorkspace = sdk.ResourceBinding(
    wire_type="azurerm_security_center_workspace",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "scope": sdk.FieldSpec(wire_name="scope"),
        "workspace_id": sdk.FieldSpec(wire_name="workspace_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterWorkspace_TimeoutsFields,
        ),
    },
)
