# Code generated by `ubx sdk gen` from azurerm_security_center_setting. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CenterSetting_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterSetting_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterSettingConfig:
    enabled: Any = None
    id: Any = None
    setting_name: Any = None
    timeouts: Any = None

CenterSetting = ubx.ResourceBinding(
    wire_type="azurerm_security_center_setting",
    fields={
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "setting_name": ubx.FieldSpec(wire_name="setting_name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterSetting_TimeoutsFields,
        ),
    },
)
