# Code generated by `ubx sdk gen` from azurerm_managed_redis_access_policy_assignment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RedisAccessPolicyAssignment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_RedisAccessPolicyAssignment_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class RedisAccessPolicyAssignmentConfig:
    id: Any = None
    managed_redis_id: Any = None
    object_id: Any = None
    timeouts: Any = None

RedisAccessPolicyAssignment = ubx.ResourceBinding(
    wire_type="azurerm_managed_redis_access_policy_assignment",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "managed_redis_id": ubx.FieldSpec(wire_name="managed_redis_id"),
        "object_id": ubx.FieldSpec(wire_name="object_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RedisAccessPolicyAssignment_TimeoutsFields,
        ),
    },
)
