# Code generated by `ubx sdk gen` from azurerm_management_group_policy_set_definition. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class GroupPolicySetDefinition_PolicyDefinitionGroup:
    additional_metadata_resource_id: Any = None
    category: Any = None
    description: Any = None
    display_name: Any = None
    name: Any = None

@dataclasses.dataclass
class GroupPolicySetDefinition_PolicyDefinitionReference:
    parameter_values: Any = None
    policy_definition_id: Any = None
    policy_group_names: Any = None
    reference_id: Any = None
    version: Any = None

@dataclasses.dataclass
class GroupPolicySetDefinition_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_GroupPolicySetDefinition_PolicyDefinitionGroupFields = {
    "additional_metadata_resource_id": sdk.FieldSpec(wire_name="additional_metadata_resource_id"),
    "category": sdk.FieldSpec(wire_name="category"),
    "description": sdk.FieldSpec(wire_name="description"),
    "display_name": sdk.FieldSpec(wire_name="display_name"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_GroupPolicySetDefinition_PolicyDefinitionReferenceFields = {
    "parameter_values": sdk.FieldSpec(wire_name="parameter_values"),
    "policy_definition_id": sdk.FieldSpec(wire_name="policy_definition_id"),
    "policy_group_names": sdk.FieldSpec(wire_name="policy_group_names"),
    "reference_id": sdk.FieldSpec(wire_name="reference_id"),
    "version": sdk.FieldSpec(wire_name="version"),
}

_GroupPolicySetDefinition_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class GroupPolicySetDefinitionConfig:
    description: Any = None
    display_name: Any = None
    id: Any = None
    management_group_id: Any = None
    metadata: Any = None
    name: Any = None
    parameters: Any = None
    policy_type: Any = None
    policy_definition_group: Any = None
    policy_definition_reference: Any = None
    timeouts: Any = None

GroupPolicySetDefinition = sdk.ResourceBinding(
    wire_type="azurerm_management_group_policy_set_definition",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "management_group_id": sdk.FieldSpec(wire_name="management_group_id"),
        "metadata": sdk.FieldSpec(wire_name="metadata"),
        "name": sdk.FieldSpec(wire_name="name"),
        "parameters": sdk.FieldSpec(wire_name="parameters"),
        "policy_type": sdk.FieldSpec(wire_name="policy_type"),
        "policy_definition_group": sdk.FieldSpec(
            wire_name="policy_definition_group",
            kind="set",
            fields=_GroupPolicySetDefinition_PolicyDefinitionGroupFields,
        ),
        "policy_definition_reference": sdk.FieldSpec(
            wire_name="policy_definition_reference",
            kind="list",
            fields=_GroupPolicySetDefinition_PolicyDefinitionReferenceFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_GroupPolicySetDefinition_TimeoutsFields,
        ),
    },
)
