# Code generated by `ubx sdk gen` from azurerm_management_lock. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Lock_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_Lock_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class LockConfig:
    id: Any = None
    lock_level: Any = None
    name: Any = None
    notes: Any = None
    scope: Any = None
    timeouts: Any = None

Lock = ubx.ResourceBinding(
    wire_type="azurerm_management_lock",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "lock_level": ubx.FieldSpec(wire_name="lock_level"),
        "name": ubx.FieldSpec(wire_name="name"),
        "notes": ubx.FieldSpec(wire_name="notes"),
        "scope": ubx.FieldSpec(wire_name="scope"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Lock_TimeoutsFields,
        ),
    },
)
