# Code generated by `ubx sdk gen` from azurerm_maintenance_assignment_dynamic_scope. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AssignmentDynamicScope_Filter_Tags:
    tag: Any = None
    values: Any = None

@dataclasses.dataclass
class AssignmentDynamicScope_Filter:
    locations: Any = None
    os_types: Any = None
    resource_groups: Any = None
    resource_types: Any = None
    tag_filter: Any = None
    tags: Any = None

@dataclasses.dataclass
class AssignmentDynamicScope_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AssignmentDynamicScope_Filter_TagsFields = {
    "tag": ubx.FieldSpec(wire_name="tag"),
    "values": ubx.FieldSpec(wire_name="values"),
}

_AssignmentDynamicScope_FilterFields = {
    "locations": ubx.FieldSpec(wire_name="locations"),
    "os_types": ubx.FieldSpec(wire_name="os_types"),
    "resource_groups": ubx.FieldSpec(wire_name="resource_groups"),
    "resource_types": ubx.FieldSpec(wire_name="resource_types"),
    "tag_filter": ubx.FieldSpec(wire_name="tag_filter"),
    "tags": ubx.FieldSpec(
        wire_name="tags",
        kind="list",
        fields=_AssignmentDynamicScope_Filter_TagsFields,
    ),
}

_AssignmentDynamicScope_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AssignmentDynamicScopeConfig:
    id: Any = None
    maintenance_configuration_id: Any = None
    name: Any = None
    filter: Any = None
    timeouts: Any = None

AssignmentDynamicScope = ubx.ResourceBinding(
    wire_type="azurerm_maintenance_assignment_dynamic_scope",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "maintenance_configuration_id": ubx.FieldSpec(wire_name="maintenance_configuration_id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "filter": ubx.FieldSpec(
            wire_name="filter",
            kind="list",
            fields=_AssignmentDynamicScope_FilterFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AssignmentDynamicScope_TimeoutsFields,
        ),
    },
)
