# Code generated by `ubx sdk gen` from azurerm_lb_backend_address_pool_address. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class BackendAddressPoolAddress_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_BackendAddressPoolAddress_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class BackendAddressPoolAddressConfig:
    backend_address_ip_configuration_id: Any = None
    backend_address_pool_id: Any = None
    id: Any = None
    ip_address: Any = None
    name: Any = None
    virtual_network_id: Any = None
    timeouts: Any = None

BackendAddressPoolAddress = ubx.ResourceBinding(
    wire_type="azurerm_lb_backend_address_pool_address",
    fields={
        "backend_address_ip_configuration_id": ubx.FieldSpec(wire_name="backend_address_ip_configuration_id"),
        "backend_address_pool_id": ubx.FieldSpec(wire_name="backend_address_pool_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "ip_address": ubx.FieldSpec(wire_name="ip_address"),
        "name": ubx.FieldSpec(wire_name="name"),
        "virtual_network_id": ubx.FieldSpec(wire_name="virtual_network_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_BackendAddressPoolAddress_TimeoutsFields,
        ),
    },
)
