# Code generated by `ubx sdk gen` from azurerm_lb_outbound_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OutboundRule_FrontendIpConfiguration:
    id: Any = None
    name: Any = None

@dataclasses.dataclass
class OutboundRule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_OutboundRule_FrontendIpConfigurationFields = {
    "id": ubx.FieldSpec(wire_name="id"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_OutboundRule_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class OutboundRuleConfig:
    allocated_outbound_ports: Any = None
    backend_address_pool_id: Any = None
    id: Any = None
    idle_timeout_in_minutes: Any = None
    loadbalancer_id: Any = None
    name: Any = None
    protocol: Any = None
    tcp_reset_enabled: Any = None
    frontend_ip_configuration: Any = None
    timeouts: Any = None

OutboundRule = ubx.ResourceBinding(
    wire_type="azurerm_lb_outbound_rule",
    fields={
        "allocated_outbound_ports": ubx.FieldSpec(wire_name="allocated_outbound_ports"),
        "backend_address_pool_id": ubx.FieldSpec(wire_name="backend_address_pool_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "idle_timeout_in_minutes": ubx.FieldSpec(wire_name="idle_timeout_in_minutes"),
        "loadbalancer_id": ubx.FieldSpec(wire_name="loadbalancer_id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "protocol": ubx.FieldSpec(wire_name="protocol"),
        "tcp_reset_enabled": ubx.FieldSpec(wire_name="tcp_reset_enabled"),
        "frontend_ip_configuration": ubx.FieldSpec(
            wire_name="frontend_ip_configuration",
            kind="list",
            fields=_OutboundRule_FrontendIpConfigurationFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_OutboundRule_TimeoutsFields,
        ),
    },
)
