# Code generated by `ubx sdk gen` from azurerm_data_factory_flowlet_data_flow. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FactoryFlowletDataFlow_Sink_Dataset:
    name: Any = None
    parameters: Any = None

@dataclasses.dataclass
class FactoryFlowletDataFlow_Sink_Flowlet:
    dataset_parameters: Any = None
    name: Any = None
    parameters: Any = None

@dataclasses.dataclass
class FactoryFlowletDataFlow_Sink:
    description: Any = None
    name: Any = None
    dataset: Any = None
    flowlet: Any = None
    linked_service: Any = None
    rejected_linked_service: Any = None
    schema_linked_service: Any = None

@dataclasses.dataclass
class FactoryFlowletDataFlow_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class FactoryFlowletDataFlow_Transformation:
    description: Any = None
    name: Any = None
    dataset: Any = None
    flowlet: Any = None
    linked_service: Any = None

_FactoryFlowletDataFlow_Sink_DatasetFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "parameters": ubx.FieldSpec(wire_name="parameters"),
}

_FactoryFlowletDataFlow_Sink_FlowletFields = {
    "dataset_parameters": ubx.FieldSpec(wire_name="dataset_parameters"),
    "name": ubx.FieldSpec(wire_name="name"),
    "parameters": ubx.FieldSpec(wire_name="parameters"),
}

_FactoryFlowletDataFlow_SinkFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "name": ubx.FieldSpec(wire_name="name"),
    "dataset": ubx.FieldSpec(
        wire_name="dataset",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
    "flowlet": ubx.FieldSpec(
        wire_name="flowlet",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_FlowletFields,
    ),
    "linked_service": ubx.FieldSpec(
        wire_name="linked_service",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
    "rejected_linked_service": ubx.FieldSpec(
        wire_name="rejected_linked_service",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
    "schema_linked_service": ubx.FieldSpec(
        wire_name="schema_linked_service",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
}

_FactoryFlowletDataFlow_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

_FactoryFlowletDataFlow_TransformationFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "name": ubx.FieldSpec(wire_name="name"),
    "dataset": ubx.FieldSpec(
        wire_name="dataset",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
    "flowlet": ubx.FieldSpec(
        wire_name="flowlet",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_FlowletFields,
    ),
    "linked_service": ubx.FieldSpec(
        wire_name="linked_service",
        kind="list",
        fields=_FactoryFlowletDataFlow_Sink_DatasetFields,
    ),
}

@dataclasses.dataclass
class FactoryFlowletDataFlowConfig:
    annotations: Any = None
    data_factory_id: Any = None
    description: Any = None
    folder: Any = None
    id: Any = None
    name: Any = None
    script: Any = None
    script_lines: Any = None
    sink: Any = None
    source: Any = None
    timeouts: Any = None
    transformation: Any = None

FactoryFlowletDataFlow = ubx.ResourceBinding(
    wire_type="azurerm_data_factory_flowlet_data_flow",
    fields={
        "annotations": ubx.FieldSpec(wire_name="annotations"),
        "data_factory_id": ubx.FieldSpec(wire_name="data_factory_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "folder": ubx.FieldSpec(wire_name="folder"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "script": ubx.FieldSpec(wire_name="script"),
        "script_lines": ubx.FieldSpec(wire_name="script_lines"),
        "sink": ubx.FieldSpec(
            wire_name="sink",
            kind="list",
            fields=_FactoryFlowletDataFlow_SinkFields,
        ),
        "source": ubx.FieldSpec(
            wire_name="source",
            kind="list",
            fields=_FactoryFlowletDataFlow_SinkFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FactoryFlowletDataFlow_TimeoutsFields,
        ),
        "transformation": ubx.FieldSpec(
            wire_name="transformation",
            kind="list",
            fields=_FactoryFlowletDataFlow_TransformationFields,
        ),
    },
)
