# Code generated by `ubx sdk gen` from azurerm_data_factory_credential_service_principal. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FactoryCredentialServicePrincipal_ServicePrincipalKey:
    linked_service_name: Any = None
    secret_name: Any = None
    secret_version: Any = None

@dataclasses.dataclass
class FactoryCredentialServicePrincipal_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_FactoryCredentialServicePrincipal_ServicePrincipalKeyFields = {
    "linked_service_name": ubx.FieldSpec(wire_name="linked_service_name"),
    "secret_name": ubx.FieldSpec(wire_name="secret_name"),
    "secret_version": ubx.FieldSpec(wire_name="secret_version"),
}

_FactoryCredentialServicePrincipal_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FactoryCredentialServicePrincipalConfig:
    annotations: Any = None
    data_factory_id: Any = None
    description: Any = None
    id: Any = None
    name: Any = None
    service_principal_id: Any = None
    tenant_id: Any = None
    service_principal_key: Any = None
    timeouts: Any = None

FactoryCredentialServicePrincipal = ubx.ResourceBinding(
    wire_type="azurerm_data_factory_credential_service_principal",
    fields={
        "annotations": ubx.FieldSpec(wire_name="annotations"),
        "data_factory_id": ubx.FieldSpec(wire_name="data_factory_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "service_principal_id": ubx.FieldSpec(wire_name="service_principal_id"),
        "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
        "service_principal_key": ubx.FieldSpec(
            wire_name="service_principal_key",
            kind="list",
            fields=_FactoryCredentialServicePrincipal_ServicePrincipalKeyFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FactoryCredentialServicePrincipal_TimeoutsFields,
        ),
    },
)
