# Code generated by `ubx sdk gen` from azurerm_servicebus_namespace_customer_managed_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class NamespaceCustomerManagedKey_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_NamespaceCustomerManagedKey_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class NamespaceCustomerManagedKeyConfig:
    id: Any = None
    infrastructure_encryption_enabled: Any = None
    key_vault_key_id: Any = None
    namespace_id: Any = None
    timeouts: Any = None

NamespaceCustomerManagedKey = sdk.ResourceBinding(
    wire_type="azurerm_servicebus_namespace_customer_managed_key",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "infrastructure_encryption_enabled": sdk.FieldSpec(wire_name="infrastructure_encryption_enabled"),
        "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
        "namespace_id": sdk.FieldSpec(wire_name="namespace_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_NamespaceCustomerManagedKey_TimeoutsFields,
        ),
    },
)
