# Code generated by `ubx sdk gen` from azurerm_servicebus_queue. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Queue_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Queue_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class QueueConfig:
    auto_delete_on_idle: Any = None
    batched_operations_enabled: Any = None
    dead_lettering_on_message_expiration: Any = None
    default_message_ttl: Any = None
    duplicate_detection_history_time_window: Any = None
    express_enabled: Any = None
    forward_dead_lettered_messages_to: Any = None
    forward_to: Any = None
    id: Any = None
    lock_duration: Any = None
    max_delivery_count: Any = None
    max_message_size_in_kilobytes: Any = None
    max_size_in_megabytes: Any = None
    name: Any = None
    namespace_id: Any = None
    partitioning_enabled: Any = None
    requires_duplicate_detection: Any = None
    requires_session: Any = None
    status: Any = None
    timeouts: Any = None

Queue = ubx.ResourceBinding(
    wire_type="azurerm_servicebus_queue",
    fields={
        "auto_delete_on_idle": ubx.FieldSpec(wire_name="auto_delete_on_idle"),
        "batched_operations_enabled": ubx.FieldSpec(wire_name="batched_operations_enabled"),
        "dead_lettering_on_message_expiration": ubx.FieldSpec(wire_name="dead_lettering_on_message_expiration"),
        "default_message_ttl": ubx.FieldSpec(wire_name="default_message_ttl"),
        "duplicate_detection_history_time_window": ubx.FieldSpec(wire_name="duplicate_detection_history_time_window"),
        "express_enabled": ubx.FieldSpec(wire_name="express_enabled"),
        "forward_dead_lettered_messages_to": ubx.FieldSpec(wire_name="forward_dead_lettered_messages_to"),
        "forward_to": ubx.FieldSpec(wire_name="forward_to"),
        "id": ubx.FieldSpec(wire_name="id"),
        "lock_duration": ubx.FieldSpec(wire_name="lock_duration"),
        "max_delivery_count": ubx.FieldSpec(wire_name="max_delivery_count"),
        "max_message_size_in_kilobytes": ubx.FieldSpec(wire_name="max_message_size_in_kilobytes"),
        "max_size_in_megabytes": ubx.FieldSpec(wire_name="max_size_in_megabytes"),
        "name": ubx.FieldSpec(wire_name="name"),
        "namespace_id": ubx.FieldSpec(wire_name="namespace_id"),
        "partitioning_enabled": ubx.FieldSpec(wire_name="partitioning_enabled"),
        "requires_duplicate_detection": ubx.FieldSpec(wire_name="requires_duplicate_detection"),
        "requires_session": ubx.FieldSpec(wire_name="requires_session"),
        "status": ubx.FieldSpec(wire_name="status"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Queue_TimeoutsFields,
        ),
    },
)
