# Code generated by `ubx sdk gen` from azurerm_machine_learning_datastore_fileshare. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LearningDatastoreFileshare_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_LearningDatastoreFileshare_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class LearningDatastoreFileshareConfig:
    account_key: Any = None
    description: Any = None
    id: Any = None
    name: Any = None
    service_data_identity: Any = None
    shared_access_signature: Any = None
    storage_fileshare_id: Any = None
    tags: Any = None
    workspace_id: Any = None
    timeouts: Any = None

LearningDatastoreFileshare = ubx.ResourceBinding(
    wire_type="azurerm_machine_learning_datastore_fileshare",
    fields={
        "account_key": ubx.FieldSpec(wire_name="account_key"),
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "service_data_identity": ubx.FieldSpec(wire_name="service_data_identity"),
        "shared_access_signature": ubx.FieldSpec(wire_name="shared_access_signature"),
        "storage_fileshare_id": ubx.FieldSpec(wire_name="storage_fileshare_id"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "workspace_id": ubx.FieldSpec(wire_name="workspace_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LearningDatastoreFileshare_TimeoutsFields,
        ),
    },
)
