# Code generated by `ubx sdk gen` from azurerm_log_analytics_linked_storage_account. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AnalyticsLinkedStorageAccount_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsLinkedStorageAccount_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsLinkedStorageAccountConfig:
    data_source_type: Any = None
    id: Any = None
    resource_group_name: Any = None
    storage_account_ids: Any = None
    workspace_id: Any = None
    timeouts: Any = None

AnalyticsLinkedStorageAccount = sdk.ResourceBinding(
    wire_type="azurerm_log_analytics_linked_storage_account",
    fields={
        "data_source_type": sdk.FieldSpec(wire_name="data_source_type"),
        "id": sdk.FieldSpec(wire_name="id"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "storage_account_ids": sdk.FieldSpec(wire_name="storage_account_ids"),
        "workspace_id": sdk.FieldSpec(wire_name="workspace_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsLinkedStorageAccount_TimeoutsFields,
        ),
    },
)
