# Code generated by `ubx sdk gen` from azurerm_bot_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Connection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Connection_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConnectionConfig:
    bot_name: Any = None
    client_id: Any = None
    client_secret: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    parameters: Any = None
    resource_group_name: Any = None
    scopes: Any = None
    service_provider_name: Any = None
    timeouts: Any = None

Connection = sdk.ResourceBinding(
    wire_type="azurerm_bot_connection",
    fields={
        "bot_name": sdk.FieldSpec(wire_name="bot_name"),
        "client_id": sdk.FieldSpec(wire_name="client_id"),
        "client_secret": sdk.FieldSpec(wire_name="client_secret"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "parameters": sdk.FieldSpec(wire_name="parameters"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "scopes": sdk.FieldSpec(wire_name="scopes"),
        "service_provider_name": sdk.FieldSpec(wire_name="service_provider_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Connection_TimeoutsFields,
        ),
    },
)
