# Code generated by `ubx sdk gen` from azurerm_bot_web_app. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class WebApp_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_WebApp_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class WebAppConfig:
    developer_app_insights_api_key: Any = None
    developer_app_insights_application_id: Any = None
    developer_app_insights_key: Any = None
    display_name: Any = None
    endpoint: Any = None
    id: Any = None
    location: Any = None
    luis_app_ids: Any = None
    luis_key: Any = None
    microsoft_app_id: Any = None
    microsoft_app_tenant_id: Any = None
    microsoft_app_type: Any = None
    microsoft_app_user_assigned_identity_id: Any = None
    name: Any = None
    resource_group_name: Any = None
    sku: Any = None
    tags: Any = None
    timeouts: Any = None

WebApp = sdk.ResourceBinding(
    wire_type="azurerm_bot_web_app",
    fields={
        "developer_app_insights_api_key": sdk.FieldSpec(wire_name="developer_app_insights_api_key"),
        "developer_app_insights_application_id": sdk.FieldSpec(wire_name="developer_app_insights_application_id"),
        "developer_app_insights_key": sdk.FieldSpec(wire_name="developer_app_insights_key"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "endpoint": sdk.FieldSpec(wire_name="endpoint"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "luis_app_ids": sdk.FieldSpec(wire_name="luis_app_ids"),
        "luis_key": sdk.FieldSpec(wire_name="luis_key"),
        "microsoft_app_id": sdk.FieldSpec(wire_name="microsoft_app_id"),
        "microsoft_app_tenant_id": sdk.FieldSpec(wire_name="microsoft_app_tenant_id"),
        "microsoft_app_type": sdk.FieldSpec(wire_name="microsoft_app_type"),
        "microsoft_app_user_assigned_identity_id": sdk.FieldSpec(wire_name="microsoft_app_user_assigned_identity_id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "sku": sdk.FieldSpec(wire_name="sku"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_WebApp_TimeoutsFields,
        ),
    },
)
