# Code generated by `ubx sdk gen` from azurerm_chaos_studio_target. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StudioTarget_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_StudioTarget_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class StudioTargetConfig:
    id: Any = None
    location: Any = None
    target_resource_id: Any = None
    target_type: Any = None
    timeouts: Any = None

StudioTarget = ubx.ResourceBinding(
    wire_type="azurerm_chaos_studio_target",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "target_resource_id": ubx.FieldSpec(wire_name="target_resource_id"),
        "target_type": ubx.FieldSpec(wire_name="target_type"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_StudioTarget_TimeoutsFields,
        ),
    },
)
