# Code generated by `ubx sdk gen` from azurerm_web_app_hybrid_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AppHybridConnection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppHybridConnection_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppHybridConnectionConfig:
    hostname: Any = None
    id: Any = None
    port: Any = None
    relay_id: Any = None
    send_key_name: Any = None
    web_app_id: Any = None
    timeouts: Any = None

AppHybridConnection = ubx.ResourceBinding(
    wire_type="azurerm_web_app_hybrid_connection",
    fields={
        "hostname": ubx.FieldSpec(wire_name="hostname"),
        "id": ubx.FieldSpec(wire_name="id"),
        "port": ubx.FieldSpec(wire_name="port"),
        "relay_id": ubx.FieldSpec(wire_name="relay_id"),
        "send_key_name": ubx.FieldSpec(wire_name="send_key_name"),
        "web_app_id": ubx.FieldSpec(wire_name="web_app_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppHybridConnection_TimeoutsFields,
        ),
    },
)
