# Code generated by `ubx sdk gen` from azurerm_web_pubsub_custom_certificate. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PubsubCustomCertificate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_PubsubCustomCertificate_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class PubsubCustomCertificateConfig:
    custom_certificate_id: Any = None
    id: Any = None
    name: Any = None
    web_pubsub_id: Any = None
    timeouts: Any = None

PubsubCustomCertificate = ubx.ResourceBinding(
    wire_type="azurerm_web_pubsub_custom_certificate",
    fields={
        "custom_certificate_id": ubx.FieldSpec(wire_name="custom_certificate_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "web_pubsub_id": ubx.FieldSpec(wire_name="web_pubsub_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PubsubCustomCertificate_TimeoutsFields,
        ),
    },
)
