# Code generated by `ubx sdk gen` from azurerm_web_pubsub. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Pubsub_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class Pubsub_LiveTrace:
    connectivity_logs_enabled: Any = None
    enabled: Any = None
    http_request_logs_enabled: Any = None
    messaging_logs_enabled: Any = None

@dataclasses.dataclass
class Pubsub_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Pubsub_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_Pubsub_LiveTraceFields = {
    "connectivity_logs_enabled": sdk.FieldSpec(wire_name="connectivity_logs_enabled"),
    "enabled": sdk.FieldSpec(wire_name="enabled"),
    "http_request_logs_enabled": sdk.FieldSpec(wire_name="http_request_logs_enabled"),
    "messaging_logs_enabled": sdk.FieldSpec(wire_name="messaging_logs_enabled"),
}

_Pubsub_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PubsubConfig:
    aad_auth_enabled: Any = None
    capacity: Any = None
    id: Any = None
    local_auth_enabled: Any = None
    location: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    sku: Any = None
    tags: Any = None
    tls_client_cert_enabled: Any = None
    identity: Any = None
    live_trace: Any = None
    timeouts: Any = None

Pubsub = sdk.ResourceBinding(
    wire_type="azurerm_web_pubsub",
    fields={
        "aad_auth_enabled": sdk.FieldSpec(wire_name="aad_auth_enabled"),
        "capacity": sdk.FieldSpec(wire_name="capacity"),
        "id": sdk.FieldSpec(wire_name="id"),
        "local_auth_enabled": sdk.FieldSpec(wire_name="local_auth_enabled"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "public_network_access_enabled": sdk.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "sku": sdk.FieldSpec(wire_name="sku"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "tls_client_cert_enabled": sdk.FieldSpec(wire_name="tls_client_cert_enabled"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_Pubsub_IdentityFields,
        ),
        "live_trace": sdk.FieldSpec(
            wire_name="live_trace",
            kind="list",
            fields=_Pubsub_LiveTraceFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Pubsub_TimeoutsFields,
        ),
    },
)
