# Code generated by `ubx sdk gen` from azurerm_web_pubsub_network_acl. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class PubsubNetworkAcl_PrivateEndpoint:
    allowed_request_types: Any = None
    denied_request_types: Any = None
    id: Any = None

@dataclasses.dataclass
class PubsubNetworkAcl_PublicNetwork:
    allowed_request_types: Any = None
    denied_request_types: Any = None

@dataclasses.dataclass
class PubsubNetworkAcl_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_PubsubNetworkAcl_PrivateEndpointFields = {
    "allowed_request_types": sdk.FieldSpec(wire_name="allowed_request_types"),
    "denied_request_types": sdk.FieldSpec(wire_name="denied_request_types"),
    "id": sdk.FieldSpec(wire_name="id"),
}

_PubsubNetworkAcl_PublicNetworkFields = {
    "allowed_request_types": sdk.FieldSpec(wire_name="allowed_request_types"),
    "denied_request_types": sdk.FieldSpec(wire_name="denied_request_types"),
}

_PubsubNetworkAcl_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PubsubNetworkAclConfig:
    default_action: Any = None
    id: Any = None
    web_pubsub_id: Any = None
    private_endpoint: Any = None
    public_network: Any = None
    timeouts: Any = None

PubsubNetworkAcl = sdk.ResourceBinding(
    wire_type="azurerm_web_pubsub_network_acl",
    fields={
        "default_action": sdk.FieldSpec(wire_name="default_action"),
        "id": sdk.FieldSpec(wire_name="id"),
        "web_pubsub_id": sdk.FieldSpec(wire_name="web_pubsub_id"),
        "private_endpoint": sdk.FieldSpec(
            wire_name="private_endpoint",
            kind="set",
            fields=_PubsubNetworkAcl_PrivateEndpointFields,
        ),
        "public_network": sdk.FieldSpec(
            wire_name="public_network",
            kind="list",
            fields=_PubsubNetworkAcl_PublicNetworkFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PubsubNetworkAcl_TimeoutsFields,
        ),
    },
)
