# Code generated by `ubx sdk gen` from azurerm_subscription. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Subscription_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Subscription_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SubscriptionConfig:
    alias: Any = None
    billing_scope_id: Any = None
    id: Any = None
    subscription_id: Any = None
    subscription_name: Any = None
    tags: Any = None
    workload: Any = None
    timeouts: Any = None

Subscription = ubx.ResourceBinding(
    wire_type="azurerm_subscription",
    fields={
        "alias": ubx.FieldSpec(wire_name="alias"),
        "billing_scope_id": ubx.FieldSpec(wire_name="billing_scope_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "subscription_id": ubx.FieldSpec(wire_name="subscription_id"),
        "subscription_name": ubx.FieldSpec(wire_name="subscription_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "workload": ubx.FieldSpec(wire_name="workload"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Subscription_TimeoutsFields,
        ),
    },
)
