# Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_cloud. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CenterVirtualMachineManagerCloud_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterVirtualMachineManagerCloud_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterVirtualMachineManagerCloudConfig:
    custom_location_id: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    system_center_virtual_machine_manager_server_inventory_item_id: Any = None
    tags: Any = None
    timeouts: Any = None

CenterVirtualMachineManagerCloud = ubx.ResourceBinding(
    wire_type="azurerm_system_center_virtual_machine_manager_cloud",
    fields={
        "custom_location_id": ubx.FieldSpec(wire_name="custom_location_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "system_center_virtual_machine_manager_server_inventory_item_id": ubx.FieldSpec(wire_name="system_center_virtual_machine_manager_server_inventory_item_id"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterVirtualMachineManagerCloud_TimeoutsFields,
        ),
    },
)
