# Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_availability_set. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CenterVirtualMachineManagerAvailabilitySet_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterVirtualMachineManagerAvailabilitySet_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterVirtualMachineManagerAvailabilitySetConfig:
    custom_location_id: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    system_center_virtual_machine_manager_server_id: Any = None
    tags: Any = None
    timeouts: Any = None

CenterVirtualMachineManagerAvailabilitySet = sdk.ResourceBinding(
    wire_type="azurerm_system_center_virtual_machine_manager_availability_set",
    fields={
        "custom_location_id": sdk.FieldSpec(wire_name="custom_location_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "system_center_virtual_machine_manager_server_id": sdk.FieldSpec(wire_name="system_center_virtual_machine_manager_server_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterVirtualMachineManagerAvailabilitySet_TimeoutsFields,
        ),
    },
)
