# Code generated by `ubx sdk gen` from azurerm_log_analytics_solution. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AnalyticsSolution_Plan:
    name: Any = None
    product: Any = None
    promotion_code: Any = None
    publisher: Any = None

@dataclasses.dataclass
class AnalyticsSolution_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AnalyticsSolution_PlanFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "product": sdk.FieldSpec(wire_name="product"),
    "promotion_code": sdk.FieldSpec(wire_name="promotion_code"),
    "publisher": sdk.FieldSpec(wire_name="publisher"),
}

_AnalyticsSolution_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AnalyticsSolutionConfig:
    id: Any = None
    location: Any = None
    resource_group_name: Any = None
    solution_name: Any = None
    tags: Any = None
    workspace_name: Any = None
    workspace_resource_id: Any = None
    plan: Any = None
    timeouts: Any = None

AnalyticsSolution = sdk.ResourceBinding(
    wire_type="azurerm_log_analytics_solution",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "solution_name": sdk.FieldSpec(wire_name="solution_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "workspace_name": sdk.FieldSpec(wire_name="workspace_name"),
        "workspace_resource_id": sdk.FieldSpec(wire_name="workspace_resource_id"),
        "plan": sdk.FieldSpec(
            wire_name="plan",
            kind="list",
            fields=_AnalyticsSolution_PlanFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AnalyticsSolution_TimeoutsFields,
        ),
    },
)
