# Code generated by `ubx sdk gen` from azurerm_logic_app_trigger_http_request. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AppTriggerHttpRequest_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppTriggerHttpRequest_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppTriggerHttpRequestConfig:
    id: Any = None
    logic_app_id: Any = None
    method: Any = None
    name: Any = None
    relative_path: Any = None
    schema: Any = None
    timeouts: Any = None

AppTriggerHttpRequest = ubx.ResourceBinding(
    wire_type="azurerm_logic_app_trigger_http_request",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "logic_app_id": ubx.FieldSpec(wire_name="logic_app_id"),
        "method": ubx.FieldSpec(wire_name="method"),
        "name": ubx.FieldSpec(wire_name="name"),
        "relative_path": ubx.FieldSpec(wire_name="relative_path"),
        "schema": ubx.FieldSpec(wire_name="schema"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppTriggerHttpRequest_TimeoutsFields,
        ),
    },
)
