# Code generated by `ubx sdk gen` from azurerm_logic_app_integration_account_map. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AppIntegrationAccountMap_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppIntegrationAccountMap_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppIntegrationAccountMapConfig:
    content: Any = None
    id: Any = None
    integration_account_name: Any = None
    map_type: Any = None
    metadata: Any = None
    name: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

AppIntegrationAccountMap = sdk.ResourceBinding(
    wire_type="azurerm_logic_app_integration_account_map",
    fields={
        "content": sdk.FieldSpec(wire_name="content"),
        "id": sdk.FieldSpec(wire_name="id"),
        "integration_account_name": sdk.FieldSpec(wire_name="integration_account_name"),
        "map_type": sdk.FieldSpec(wire_name="map_type"),
        "metadata": sdk.FieldSpec(wire_name="metadata"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppIntegrationAccountMap_TimeoutsFields,
        ),
    },
)
