# Code generated by `ubx sdk gen` from azurerm_synapse_workspace_aad_admin. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class WorkspaceAadAdmin_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_WorkspaceAadAdmin_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class WorkspaceAadAdminConfig:
    id: Any = None
    login: Any = None
    object_id: Any = None
    synapse_workspace_id: Any = None
    tenant_id: Any = None
    timeouts: Any = None

WorkspaceAadAdmin = sdk.ResourceBinding(
    wire_type="azurerm_synapse_workspace_aad_admin",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "login": sdk.FieldSpec(wire_name="login"),
        "object_id": sdk.FieldSpec(wire_name="object_id"),
        "synapse_workspace_id": sdk.FieldSpec(wire_name="synapse_workspace_id"),
        "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_WorkspaceAadAdmin_TimeoutsFields,
        ),
    },
)
