# Code generated by `ubx sdk gen` from azurerm_synapse_workspace_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class WorkspaceKey_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_WorkspaceKey_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class WorkspaceKeyConfig:
    active: Any = None
    customer_managed_key_name: Any = None
    customer_managed_key_versionless_id: Any = None
    id: Any = None
    synapse_workspace_id: Any = None
    timeouts: Any = None

WorkspaceKey = sdk.ResourceBinding(
    wire_type="azurerm_synapse_workspace_key",
    fields={
        "active": sdk.FieldSpec(wire_name="active"),
        "customer_managed_key_name": sdk.FieldSpec(wire_name="customer_managed_key_name"),
        "customer_managed_key_versionless_id": sdk.FieldSpec(wire_name="customer_managed_key_versionless_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "synapse_workspace_id": sdk.FieldSpec(wire_name="synapse_workspace_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_WorkspaceKey_TimeoutsFields,
        ),
    },
)
