# Code generated by `ubx sdk gen` from azurerm_dev_center_project. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CenterProject_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class CenterProject_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterProject_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_CenterProject_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterProjectConfig:
    description: Any = None
    dev_center_id: Any = None
    id: Any = None
    location: Any = None
    maximum_dev_boxes_per_user: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    identity: Any = None
    timeouts: Any = None

CenterProject = sdk.ResourceBinding(
    wire_type="azurerm_dev_center_project",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "dev_center_id": sdk.FieldSpec(wire_name="dev_center_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "maximum_dev_boxes_per_user": sdk.FieldSpec(wire_name="maximum_dev_boxes_per_user"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_CenterProject_IdentityFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterProject_TimeoutsFields,
        ),
    },
)
