# Code generated by `ubx sdk gen` from azurerm_app_configuration_feature. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConfigurationFeature_CustomFilter:
    name: Any = None
    parameters: Any = None

@dataclasses.dataclass
class ConfigurationFeature_TargetingFilter_Groups:
    name: Any = None
    rollout_percentage: Any = None

@dataclasses.dataclass
class ConfigurationFeature_TargetingFilter:
    default_rollout_percentage: Any = None
    users: Any = None
    groups: Any = None

@dataclasses.dataclass
class ConfigurationFeature_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class ConfigurationFeature_TimewindowFilter:
    end: Any = None
    start: Any = None

_ConfigurationFeature_CustomFilterFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "parameters": ubx.FieldSpec(wire_name="parameters"),
}

_ConfigurationFeature_TargetingFilter_GroupsFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "rollout_percentage": ubx.FieldSpec(wire_name="rollout_percentage"),
}

_ConfigurationFeature_TargetingFilterFields = {
    "default_rollout_percentage": ubx.FieldSpec(wire_name="default_rollout_percentage"),
    "users": ubx.FieldSpec(wire_name="users"),
    "groups": ubx.FieldSpec(
        wire_name="groups",
        kind="list",
        fields=_ConfigurationFeature_TargetingFilter_GroupsFields,
    ),
}

_ConfigurationFeature_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

_ConfigurationFeature_TimewindowFilterFields = {
    "end": ubx.FieldSpec(wire_name="end"),
    "start": ubx.FieldSpec(wire_name="start"),
}

@dataclasses.dataclass
class ConfigurationFeatureConfig:
    configuration_store_id: Any = None
    description: Any = None
    enabled: Any = None
    etag: Any = None
    id: Any = None
    key: Any = None
    label: Any = None
    locked: Any = None
    name: Any = None
    percentage_filter_value: Any = None
    tags: Any = None
    custom_filter: Any = None
    targeting_filter: Any = None
    timeouts: Any = None
    timewindow_filter: Any = None

ConfigurationFeature = ubx.ResourceBinding(
    wire_type="azurerm_app_configuration_feature",
    fields={
        "configuration_store_id": ubx.FieldSpec(wire_name="configuration_store_id"),
        "description": ubx.FieldSpec(wire_name="description"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "etag": ubx.FieldSpec(wire_name="etag"),
        "id": ubx.FieldSpec(wire_name="id"),
        "key": ubx.FieldSpec(wire_name="key"),
        "label": ubx.FieldSpec(wire_name="label"),
        "locked": ubx.FieldSpec(wire_name="locked"),
        "name": ubx.FieldSpec(wire_name="name"),
        "percentage_filter_value": ubx.FieldSpec(wire_name="percentage_filter_value"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "custom_filter": ubx.FieldSpec(
            wire_name="custom_filter",
            kind="list",
            fields=_ConfigurationFeature_CustomFilterFields,
        ),
        "targeting_filter": ubx.FieldSpec(
            wire_name="targeting_filter",
            kind="list",
            fields=_ConfigurationFeature_TargetingFilterFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ConfigurationFeature_TimeoutsFields,
        ),
        "timewindow_filter": ubx.FieldSpec(
            wire_name="timewindow_filter",
            kind="list",
            fields=_ConfigurationFeature_TimewindowFilterFields,
        ),
    },
)
