# Code generated by `ubx sdk gen` from azurerm_app_service_custom_hostname_binding. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceCustomHostnameBinding_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_ServiceCustomHostnameBinding_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class ServiceCustomHostnameBindingConfig:
    app_service_name: Any = None
    hostname: Any = None
    id: Any = None
    resource_group_name: Any = None
    ssl_state: Any = None
    thumbprint: Any = None
    timeouts: Any = None

ServiceCustomHostnameBinding = ubx.ResourceBinding(
    wire_type="azurerm_app_service_custom_hostname_binding",
    fields={
        "app_service_name": ubx.FieldSpec(wire_name="app_service_name"),
        "hostname": ubx.FieldSpec(wire_name="hostname"),
        "id": ubx.FieldSpec(wire_name="id"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "ssl_state": ubx.FieldSpec(wire_name="ssl_state"),
        "thumbprint": ubx.FieldSpec(wire_name="thumbprint"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ServiceCustomHostnameBinding_TimeoutsFields,
        ),
    },
)
