# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .subnet import Subnet, SubnetConfig
from .nat_gateway_association import NatGatewayAssociation, NatGatewayAssociationConfig
from .network_security_group_association import NetworkSecurityGroupAssociation, NetworkSecurityGroupAssociationConfig
from .route_table_association import RouteTableAssociation, RouteTableAssociationConfig
from .service_endpoint_storage_policy import ServiceEndpointStoragePolicy, ServiceEndpointStoragePolicyConfig
