# Code generated by `ubx sdk gen` from azurerm_subnet. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Subnet_Delegation_ServiceDelegation:
    actions: Any = None
    name: Any = None

@dataclasses.dataclass
class Subnet_Delegation:
    name: Any = None
    service_delegation: Any = None

@dataclasses.dataclass
class Subnet_IpAddressPool:
    allocated_ip_address_prefixes: Any = None
    id: Any = None
    number_of_ip_addresses: Any = None

@dataclasses.dataclass
class Subnet_ServiceEndpoint:
    network_identifier: Any = None
    service: Any = None

@dataclasses.dataclass
class Subnet_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Subnet_Delegation_ServiceDelegationFields = {
    "actions": ubx.FieldSpec(wire_name="actions"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_Subnet_DelegationFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "service_delegation": ubx.FieldSpec(
        wire_name="service_delegation",
        kind="list",
        fields=_Subnet_Delegation_ServiceDelegationFields,
    ),
}

_Subnet_IpAddressPoolFields = {
    "allocated_ip_address_prefixes": ubx.FieldSpec(wire_name="allocated_ip_address_prefixes"),
    "id": ubx.FieldSpec(wire_name="id"),
    "number_of_ip_addresses": ubx.FieldSpec(wire_name="number_of_ip_addresses"),
}

_Subnet_ServiceEndpointFields = {
    "network_identifier": ubx.FieldSpec(wire_name="network_identifier"),
    "service": ubx.FieldSpec(wire_name="service"),
}

_Subnet_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SubnetConfig:
    address_prefixes: Any = None
    default_outbound_access_enabled: Any = None
    id: Any = None
    name: Any = None
    network_security_group_id_wo: Any = None
    network_security_group_id_wo_version: Any = None
    private_endpoint_network_policies: Any = None
    private_link_service_network_policies_enabled: Any = None
    resource_group_name: Any = None
    route_table_id_wo: Any = None
    route_table_id_wo_version: Any = None
    service_endpoint_policy_ids: Any = None
    sharing_scope: Any = None
    virtual_network_name: Any = None
    delegation: Any = None
    ip_address_pool: Any = None
    service_endpoint: Any = None
    timeouts: Any = None

Subnet = ubx.ResourceBinding(
    wire_type="azurerm_subnet",
    fields={
        "address_prefixes": ubx.FieldSpec(wire_name="address_prefixes"),
        "default_outbound_access_enabled": ubx.FieldSpec(wire_name="default_outbound_access_enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "network_security_group_id_wo": ubx.FieldSpec(wire_name="network_security_group_id_wo"),
        "network_security_group_id_wo_version": ubx.FieldSpec(wire_name="network_security_group_id_wo_version"),
        "private_endpoint_network_policies": ubx.FieldSpec(wire_name="private_endpoint_network_policies"),
        "private_link_service_network_policies_enabled": ubx.FieldSpec(wire_name="private_link_service_network_policies_enabled"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "route_table_id_wo": ubx.FieldSpec(wire_name="route_table_id_wo"),
        "route_table_id_wo_version": ubx.FieldSpec(wire_name="route_table_id_wo_version"),
        "service_endpoint_policy_ids": ubx.FieldSpec(wire_name="service_endpoint_policy_ids"),
        "sharing_scope": ubx.FieldSpec(wire_name="sharing_scope"),
        "virtual_network_name": ubx.FieldSpec(wire_name="virtual_network_name"),
        "delegation": ubx.FieldSpec(
            wire_name="delegation",
            kind="list",
            fields=_Subnet_DelegationFields,
        ),
        "ip_address_pool": ubx.FieldSpec(
            wire_name="ip_address_pool",
            kind="list",
            fields=_Subnet_IpAddressPoolFields,
        ),
        "service_endpoint": ubx.FieldSpec(
            wire_name="service_endpoint",
            kind="list",
            fields=_Subnet_ServiceEndpointFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Subnet_TimeoutsFields,
        ),
    },
)
