# Code generated by `ubx sdk gen` from azurerm_synapse_sql_pool. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class SqlPool_Restore:
    point_in_time: Any = None
    source_database_id: Any = None

@dataclasses.dataclass
class SqlPool_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SqlPool_RestoreFields = {
    "point_in_time": sdk.FieldSpec(wire_name="point_in_time"),
    "source_database_id": sdk.FieldSpec(wire_name="source_database_id"),
}

_SqlPool_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SqlPoolConfig:
    collation: Any = None
    create_mode: Any = None
    data_encrypted: Any = None
    geo_backup_policy_enabled: Any = None
    id: Any = None
    name: Any = None
    recovery_database_id: Any = None
    sku_name: Any = None
    storage_account_type: Any = None
    synapse_workspace_id: Any = None
    tags: Any = None
    restore: Any = None
    timeouts: Any = None

SqlPool = sdk.ResourceBinding(
    wire_type="azurerm_synapse_sql_pool",
    fields={
        "collation": sdk.FieldSpec(wire_name="collation"),
        "create_mode": sdk.FieldSpec(wire_name="create_mode"),
        "data_encrypted": sdk.FieldSpec(wire_name="data_encrypted"),
        "geo_backup_policy_enabled": sdk.FieldSpec(wire_name="geo_backup_policy_enabled"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "recovery_database_id": sdk.FieldSpec(wire_name="recovery_database_id"),
        "sku_name": sdk.FieldSpec(wire_name="sku_name"),
        "storage_account_type": sdk.FieldSpec(wire_name="storage_account_type"),
        "synapse_workspace_id": sdk.FieldSpec(wire_name="synapse_workspace_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "restore": sdk.FieldSpec(
            wire_name="restore",
            kind="list",
            fields=_SqlPool_RestoreFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SqlPool_TimeoutsFields,
        ),
    },
)
