# Code generated by `ubx sdk gen` from azurerm_container_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Group_ExposedPort:
    port: Any = None
    protocol: Any = None

@dataclasses.dataclass
class Group_Container_LivenessProbe_HttpGet:
    http_headers: Any = None
    path: Any = None
    port: Any = None
    scheme: Any = None

@dataclasses.dataclass
class Group_Container_LivenessProbe:
    exec: Any = None
    failure_threshold: Any = None
    initial_delay_seconds: Any = None
    period_seconds: Any = None
    success_threshold: Any = None
    timeout_seconds: Any = None
    http_get: Any = None

@dataclasses.dataclass
class Group_Container_Security:
    privilege_enabled: Any = None

@dataclasses.dataclass
class Group_Container_Volume_GitRepo:
    directory: Any = None
    revision: Any = None
    url: Any = None

@dataclasses.dataclass
class Group_Container_Volume:
    empty_dir: Any = None
    mount_path: Any = None
    name: Any = None
    read_only: Any = None
    secret: Any = None
    share_name: Any = None
    storage_account_key: Any = None
    storage_account_name: Any = None
    git_repo: Any = None

@dataclasses.dataclass
class Group_Container:
    commands: Any = None
    cpu: Any = None
    cpu_limit: Any = None
    environment_variables: Any = None
    image: Any = None
    memory: Any = None
    memory_limit: Any = None
    name: Any = None
    secure_environment_variables: Any = None
    liveness_probe: Any = None
    ports: Any = None
    readiness_probe: Any = None
    security: Any = None
    volume: Any = None

@dataclasses.dataclass
class Group_Diagnostics_LogAnalytics:
    log_type: Any = None
    metadata: Any = None
    workspace_id: Any = None
    workspace_key: Any = None

@dataclasses.dataclass
class Group_Diagnostics:
    log_analytics: Any = None

@dataclasses.dataclass
class Group_DnsConfig:
    nameservers: Any = None
    options: Any = None
    search_domains: Any = None

@dataclasses.dataclass
class Group_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class Group_ImageRegistryCredential:
    password: Any = None
    server: Any = None
    user_assigned_identity_id: Any = None
    username: Any = None

@dataclasses.dataclass
class Group_InitContainer:
    commands: Any = None
    environment_variables: Any = None
    image: Any = None
    name: Any = None
    secure_environment_variables: Any = None
    security: Any = None
    volume: Any = None

@dataclasses.dataclass
class Group_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Group_ExposedPortFields = {
    "port": sdk.FieldSpec(wire_name="port"),
    "protocol": sdk.FieldSpec(wire_name="protocol"),
}

_Group_Container_LivenessProbe_HttpGetFields = {
    "http_headers": sdk.FieldSpec(wire_name="http_headers"),
    "path": sdk.FieldSpec(wire_name="path"),
    "port": sdk.FieldSpec(wire_name="port"),
    "scheme": sdk.FieldSpec(wire_name="scheme"),
}

_Group_Container_LivenessProbeFields = {
    "exec": sdk.FieldSpec(wire_name="exec"),
    "failure_threshold": sdk.FieldSpec(wire_name="failure_threshold"),
    "initial_delay_seconds": sdk.FieldSpec(wire_name="initial_delay_seconds"),
    "period_seconds": sdk.FieldSpec(wire_name="period_seconds"),
    "success_threshold": sdk.FieldSpec(wire_name="success_threshold"),
    "timeout_seconds": sdk.FieldSpec(wire_name="timeout_seconds"),
    "http_get": sdk.FieldSpec(
        wire_name="http_get",
        kind="list",
        fields=_Group_Container_LivenessProbe_HttpGetFields,
    ),
}

_Group_Container_SecurityFields = {
    "privilege_enabled": sdk.FieldSpec(wire_name="privilege_enabled"),
}

_Group_Container_Volume_GitRepoFields = {
    "directory": sdk.FieldSpec(wire_name="directory"),
    "revision": sdk.FieldSpec(wire_name="revision"),
    "url": sdk.FieldSpec(wire_name="url"),
}

_Group_Container_VolumeFields = {
    "empty_dir": sdk.FieldSpec(wire_name="empty_dir"),
    "mount_path": sdk.FieldSpec(wire_name="mount_path"),
    "name": sdk.FieldSpec(wire_name="name"),
    "read_only": sdk.FieldSpec(wire_name="read_only"),
    "secret": sdk.FieldSpec(wire_name="secret"),
    "share_name": sdk.FieldSpec(wire_name="share_name"),
    "storage_account_key": sdk.FieldSpec(wire_name="storage_account_key"),
    "storage_account_name": sdk.FieldSpec(wire_name="storage_account_name"),
    "git_repo": sdk.FieldSpec(
        wire_name="git_repo",
        kind="list",
        fields=_Group_Container_Volume_GitRepoFields,
    ),
}

_Group_ContainerFields = {
    "commands": sdk.FieldSpec(wire_name="commands"),
    "cpu": sdk.FieldSpec(wire_name="cpu"),
    "cpu_limit": sdk.FieldSpec(wire_name="cpu_limit"),
    "environment_variables": sdk.FieldSpec(wire_name="environment_variables"),
    "image": sdk.FieldSpec(wire_name="image"),
    "memory": sdk.FieldSpec(wire_name="memory"),
    "memory_limit": sdk.FieldSpec(wire_name="memory_limit"),
    "name": sdk.FieldSpec(wire_name="name"),
    "secure_environment_variables": sdk.FieldSpec(wire_name="secure_environment_variables"),
    "liveness_probe": sdk.FieldSpec(
        wire_name="liveness_probe",
        kind="list",
        fields=_Group_Container_LivenessProbeFields,
    ),
    "ports": sdk.FieldSpec(
        wire_name="ports",
        kind="set",
        fields=_Group_ExposedPortFields,
    ),
    "readiness_probe": sdk.FieldSpec(
        wire_name="readiness_probe",
        kind="list",
        fields=_Group_Container_LivenessProbeFields,
    ),
    "security": sdk.FieldSpec(
        wire_name="security",
        kind="list",
        fields=_Group_Container_SecurityFields,
    ),
    "volume": sdk.FieldSpec(
        wire_name="volume",
        kind="list",
        fields=_Group_Container_VolumeFields,
    ),
}

_Group_Diagnostics_LogAnalyticsFields = {
    "log_type": sdk.FieldSpec(wire_name="log_type"),
    "metadata": sdk.FieldSpec(wire_name="metadata"),
    "workspace_id": sdk.FieldSpec(wire_name="workspace_id"),
    "workspace_key": sdk.FieldSpec(wire_name="workspace_key"),
}

_Group_DiagnosticsFields = {
    "log_analytics": sdk.FieldSpec(
        wire_name="log_analytics",
        kind="list",
        fields=_Group_Diagnostics_LogAnalyticsFields,
    ),
}

_Group_DnsConfigFields = {
    "nameservers": sdk.FieldSpec(wire_name="nameservers"),
    "options": sdk.FieldSpec(wire_name="options"),
    "search_domains": sdk.FieldSpec(wire_name="search_domains"),
}

_Group_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_Group_ImageRegistryCredentialFields = {
    "password": sdk.FieldSpec(wire_name="password"),
    "server": sdk.FieldSpec(wire_name="server"),
    "user_assigned_identity_id": sdk.FieldSpec(wire_name="user_assigned_identity_id"),
    "username": sdk.FieldSpec(wire_name="username"),
}

_Group_InitContainerFields = {
    "commands": sdk.FieldSpec(wire_name="commands"),
    "environment_variables": sdk.FieldSpec(wire_name="environment_variables"),
    "image": sdk.FieldSpec(wire_name="image"),
    "name": sdk.FieldSpec(wire_name="name"),
    "secure_environment_variables": sdk.FieldSpec(wire_name="secure_environment_variables"),
    "security": sdk.FieldSpec(
        wire_name="security",
        kind="list",
        fields=_Group_Container_SecurityFields,
    ),
    "volume": sdk.FieldSpec(
        wire_name="volume",
        kind="list",
        fields=_Group_Container_VolumeFields,
    ),
}

_Group_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class GroupConfig:
    dns_name_label: Any = None
    dns_name_label_reuse_policy: Any = None
    exposed_port: Any = None
    id: Any = None
    ip_address_type: Any = None
    key_vault_key_id: Any = None
    key_vault_user_assigned_identity_id: Any = None
    location: Any = None
    name: Any = None
    network_profile_id: Any = None
    os_type: Any = None
    priority: Any = None
    resource_group_name: Any = None
    restart_policy: Any = None
    sku: Any = None
    subnet_ids: Any = None
    tags: Any = None
    zones: Any = None
    container: Any = None
    diagnostics: Any = None
    dns_config: Any = None
    identity: Any = None
    image_registry_credential: Any = None
    init_container: Any = None
    timeouts: Any = None

Group = sdk.ResourceBinding(
    wire_type="azurerm_container_group",
    fields={
        "dns_name_label": sdk.FieldSpec(wire_name="dns_name_label"),
        "dns_name_label_reuse_policy": sdk.FieldSpec(wire_name="dns_name_label_reuse_policy"),
        "exposed_port": sdk.FieldSpec(
            wire_name="exposed_port",
            kind="set",
            fields=_Group_ExposedPortFields,
        ),
        "id": sdk.FieldSpec(wire_name="id"),
        "ip_address_type": sdk.FieldSpec(wire_name="ip_address_type"),
        "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
        "key_vault_user_assigned_identity_id": sdk.FieldSpec(wire_name="key_vault_user_assigned_identity_id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "network_profile_id": sdk.FieldSpec(wire_name="network_profile_id"),
        "os_type": sdk.FieldSpec(wire_name="os_type"),
        "priority": sdk.FieldSpec(wire_name="priority"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "restart_policy": sdk.FieldSpec(wire_name="restart_policy"),
        "sku": sdk.FieldSpec(wire_name="sku"),
        "subnet_ids": sdk.FieldSpec(wire_name="subnet_ids"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "zones": sdk.FieldSpec(wire_name="zones"),
        "container": sdk.FieldSpec(
            wire_name="container",
            kind="list",
            fields=_Group_ContainerFields,
        ),
        "diagnostics": sdk.FieldSpec(
            wire_name="diagnostics",
            kind="list",
            fields=_Group_DiagnosticsFields,
        ),
        "dns_config": sdk.FieldSpec(
            wire_name="dns_config",
            kind="list",
            fields=_Group_DnsConfigFields,
        ),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_Group_IdentityFields,
        ),
        "image_registry_credential": sdk.FieldSpec(
            wire_name="image_registry_credential",
            kind="list",
            fields=_Group_ImageRegistryCredentialFields,
        ),
        "init_container": sdk.FieldSpec(
            wire_name="init_container",
            kind="list",
            fields=_Group_InitContainerFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Group_TimeoutsFields,
        ),
    },
)
