# Code generated by `ubx sdk gen` from azurerm_storage_account_customer_managed_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AccountCustomerManagedKey_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AccountCustomerManagedKey_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AccountCustomerManagedKeyConfig:
    federated_identity_client_id: Any = None
    id: Any = None
    key_vault_key_id: Any = None
    storage_account_id: Any = None
    user_assigned_identity_id: Any = None
    timeouts: Any = None

AccountCustomerManagedKey = sdk.ResourceBinding(
    wire_type="azurerm_storage_account_customer_managed_key",
    fields={
        "federated_identity_client_id": sdk.FieldSpec(wire_name="federated_identity_client_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
        "storage_account_id": sdk.FieldSpec(wire_name="storage_account_id"),
        "user_assigned_identity_id": sdk.FieldSpec(wire_name="user_assigned_identity_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AccountCustomerManagedKey_TimeoutsFields,
        ),
    },
)
