# Code generated by `ubx sdk gen` from azurerm_storage_sync_server_endpoint. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class SyncServerEndpoint_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SyncServerEndpoint_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SyncServerEndpointConfig:
    cloud_tiering_enabled: Any = None
    id: Any = None
    initial_download_policy: Any = None
    local_cache_mode: Any = None
    name: Any = None
    registered_server_id: Any = None
    server_local_path: Any = None
    storage_sync_group_id: Any = None
    tier_files_older_than_days: Any = None
    volume_free_space_percent: Any = None
    timeouts: Any = None

SyncServerEndpoint = sdk.ResourceBinding(
    wire_type="azurerm_storage_sync_server_endpoint",
    fields={
        "cloud_tiering_enabled": sdk.FieldSpec(wire_name="cloud_tiering_enabled"),
        "id": sdk.FieldSpec(wire_name="id"),
        "initial_download_policy": sdk.FieldSpec(wire_name="initial_download_policy"),
        "local_cache_mode": sdk.FieldSpec(wire_name="local_cache_mode"),
        "name": sdk.FieldSpec(wire_name="name"),
        "registered_server_id": sdk.FieldSpec(wire_name="registered_server_id"),
        "server_local_path": sdk.FieldSpec(wire_name="server_local_path"),
        "storage_sync_group_id": sdk.FieldSpec(wire_name="storage_sync_group_id"),
        "tier_files_older_than_days": sdk.FieldSpec(wire_name="tier_files_older_than_days"),
        "volume_free_space_percent": sdk.FieldSpec(wire_name="volume_free_space_percent"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SyncServerEndpoint_TimeoutsFields,
        ),
    },
)
