# Code generated by `ubx sdk gen` from azurerm_private_dns_resolver_virtual_network_link. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DnsResolverVirtualNetworkLink_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DnsResolverVirtualNetworkLink_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DnsResolverVirtualNetworkLinkConfig:
    dns_forwarding_ruleset_id: Any = None
    id: Any = None
    metadata: Any = None
    name: Any = None
    virtual_network_id: Any = None
    timeouts: Any = None

DnsResolverVirtualNetworkLink = sdk.ResourceBinding(
    wire_type="azurerm_private_dns_resolver_virtual_network_link",
    fields={
        "dns_forwarding_ruleset_id": sdk.FieldSpec(wire_name="dns_forwarding_ruleset_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "metadata": sdk.FieldSpec(wire_name="metadata"),
        "name": sdk.FieldSpec(wire_name="name"),
        "virtual_network_id": sdk.FieldSpec(wire_name="virtual_network_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DnsResolverVirtualNetworkLink_TimeoutsFields,
        ),
    },
)
