# Code generated by `ubx sdk gen` from azurerm_resource_deployment_script_azure_power_shell. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DeploymentScriptAzurePowerShell_Container:
    container_group_name: Any = None

@dataclasses.dataclass
class DeploymentScriptAzurePowerShell_EnvironmentVariable:
    name: Any = None
    secure_value: Any = None
    value: Any = None

@dataclasses.dataclass
class DeploymentScriptAzurePowerShell_Identity:
    identity_ids: Any = None
    type: Any = None

@dataclasses.dataclass
class DeploymentScriptAzurePowerShell_StorageAccount:
    key: Any = None
    name: Any = None

@dataclasses.dataclass
class DeploymentScriptAzurePowerShell_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DeploymentScriptAzurePowerShell_ContainerFields = {
    "container_group_name": sdk.FieldSpec(wire_name="container_group_name"),
}

_DeploymentScriptAzurePowerShell_EnvironmentVariableFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "secure_value": sdk.FieldSpec(wire_name="secure_value"),
    "value": sdk.FieldSpec(wire_name="value"),
}

_DeploymentScriptAzurePowerShell_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_DeploymentScriptAzurePowerShell_StorageAccountFields = {
    "key": sdk.FieldSpec(wire_name="key"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_DeploymentScriptAzurePowerShell_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DeploymentScriptAzurePowerShellConfig:
    cleanup_preference: Any = None
    command_line: Any = None
    force_update_tag: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    primary_script_uri: Any = None
    resource_group_name: Any = None
    retention_interval: Any = None
    script_content: Any = None
    supporting_script_uris: Any = None
    tags: Any = None
    timeout: Any = None
    version: Any = None
    container: Any = None
    environment_variable: Any = None
    identity: Any = None
    storage_account: Any = None
    timeouts: Any = None

DeploymentScriptAzurePowerShell = sdk.ResourceBinding(
    wire_type="azurerm_resource_deployment_script_azure_power_shell",
    fields={
        "cleanup_preference": sdk.FieldSpec(wire_name="cleanup_preference"),
        "command_line": sdk.FieldSpec(wire_name="command_line"),
        "force_update_tag": sdk.FieldSpec(wire_name="force_update_tag"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "primary_script_uri": sdk.FieldSpec(wire_name="primary_script_uri"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "retention_interval": sdk.FieldSpec(wire_name="retention_interval"),
        "script_content": sdk.FieldSpec(wire_name="script_content"),
        "supporting_script_uris": sdk.FieldSpec(wire_name="supporting_script_uris"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeout": sdk.FieldSpec(wire_name="timeout"),
        "version": sdk.FieldSpec(wire_name="version"),
        "container": sdk.FieldSpec(
            wire_name="container",
            kind="list",
            fields=_DeploymentScriptAzurePowerShell_ContainerFields,
        ),
        "environment_variable": sdk.FieldSpec(
            wire_name="environment_variable",
            kind="set",
            fields=_DeploymentScriptAzurePowerShell_EnvironmentVariableFields,
        ),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_DeploymentScriptAzurePowerShell_IdentityFields,
        ),
        "storage_account": sdk.FieldSpec(
            wire_name="storage_account",
            kind="list",
            fields=_DeploymentScriptAzurePowerShell_StorageAccountFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DeploymentScriptAzurePowerShell_TimeoutsFields,
        ),
    },
)
