# Code generated by `ubx sdk gen` from azurerm_resource_group_cost_management_view. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GroupCostManagementView_Dataset_Aggregation:
    column_name: Any = None
    name: Any = None

@dataclasses.dataclass
class GroupCostManagementView_Dataset_Grouping:
    name: Any = None
    type: Any = None

@dataclasses.dataclass
class GroupCostManagementView_Dataset_Sorting:
    direction: Any = None
    name: Any = None

@dataclasses.dataclass
class GroupCostManagementView_Dataset:
    granularity: Any = None
    aggregation: Any = None
    grouping: Any = None
    sorting: Any = None

@dataclasses.dataclass
class GroupCostManagementView_Kpi:
    type: Any = None

@dataclasses.dataclass
class GroupCostManagementView_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_GroupCostManagementView_Dataset_AggregationFields = {
    "column_name": ubx.FieldSpec(wire_name="column_name"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_GroupCostManagementView_Dataset_GroupingFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_GroupCostManagementView_Dataset_SortingFields = {
    "direction": ubx.FieldSpec(wire_name="direction"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_GroupCostManagementView_DatasetFields = {
    "granularity": ubx.FieldSpec(wire_name="granularity"),
    "aggregation": ubx.FieldSpec(
        wire_name="aggregation",
        kind="set",
        fields=_GroupCostManagementView_Dataset_AggregationFields,
    ),
    "grouping": ubx.FieldSpec(
        wire_name="grouping",
        kind="list",
        fields=_GroupCostManagementView_Dataset_GroupingFields,
    ),
    "sorting": ubx.FieldSpec(
        wire_name="sorting",
        kind="list",
        fields=_GroupCostManagementView_Dataset_SortingFields,
    ),
}

_GroupCostManagementView_KpiFields = {
    "type": ubx.FieldSpec(wire_name="type"),
}

_GroupCostManagementView_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class GroupCostManagementViewConfig:
    accumulated: Any = None
    chart_type: Any = None
    display_name: Any = None
    id: Any = None
    name: Any = None
    report_type: Any = None
    resource_group_id: Any = None
    timeframe: Any = None
    dataset: Any = None
    kpi: Any = None
    pivot: Any = None
    timeouts: Any = None

GroupCostManagementView = ubx.ResourceBinding(
    wire_type="azurerm_resource_group_cost_management_view",
    fields={
        "accumulated": ubx.FieldSpec(wire_name="accumulated"),
        "chart_type": ubx.FieldSpec(wire_name="chart_type"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "report_type": ubx.FieldSpec(wire_name="report_type"),
        "resource_group_id": ubx.FieldSpec(wire_name="resource_group_id"),
        "timeframe": ubx.FieldSpec(wire_name="timeframe"),
        "dataset": ubx.FieldSpec(
            wire_name="dataset",
            kind="list",
            fields=_GroupCostManagementView_DatasetFields,
        ),
        "kpi": ubx.FieldSpec(
            wire_name="kpi",
            kind="list",
            fields=_GroupCostManagementView_KpiFields,
        ),
        "pivot": ubx.FieldSpec(
            wire_name="pivot",
            kind="list",
            fields=_GroupCostManagementView_Dataset_GroupingFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_GroupCostManagementView_TimeoutsFields,
        ),
    },
)
