# Code generated by `ubx sdk gen` from azurerm_resource_provider_registration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ProviderRegistration_Feature:
    name: Any = None
    registered: Any = None

@dataclasses.dataclass
class ProviderRegistration_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ProviderRegistration_FeatureFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "registered": ubx.FieldSpec(wire_name="registered"),
}

_ProviderRegistration_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ProviderRegistrationConfig:
    id: Any = None
    name: Any = None
    feature: Any = None
    timeouts: Any = None

ProviderRegistration = ubx.ResourceBinding(
    wire_type="azurerm_resource_provider_registration",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "feature": ubx.FieldSpec(
            wire_name="feature",
            kind="set",
            fields=_ProviderRegistration_FeatureFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ProviderRegistration_TimeoutsFields,
        ),
    },
)
