# Code generated by `ubx sdk gen` from azurerm_relay_hybrid_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class HybridConnection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_HybridConnection_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class HybridConnectionConfig:
    id: Any = None
    name: Any = None
    relay_namespace_name: Any = None
    requires_client_authorization: Any = None
    resource_group_name: Any = None
    user_metadata: Any = None
    timeouts: Any = None

HybridConnection = ubx.ResourceBinding(
    wire_type="azurerm_relay_hybrid_connection",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "relay_namespace_name": ubx.FieldSpec(wire_name="relay_namespace_name"),
        "requires_client_authorization": ubx.FieldSpec(wire_name="requires_client_authorization"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "user_metadata": ubx.FieldSpec(wire_name="user_metadata"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_HybridConnection_TimeoutsFields,
        ),
    },
)
