# Code generated by `ubx sdk gen` from azurerm_relay_hybrid_connection_authorization_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class HybridConnectionAuthorizationRule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_HybridConnectionAuthorizationRule_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class HybridConnectionAuthorizationRuleConfig:
    hybrid_connection_name: Any = None
    id: Any = None
    listen: Any = None
    manage: Any = None
    name: Any = None
    namespace_name: Any = None
    resource_group_name: Any = None
    send: Any = None
    timeouts: Any = None

HybridConnectionAuthorizationRule = ubx.ResourceBinding(
    wire_type="azurerm_relay_hybrid_connection_authorization_rule",
    fields={
        "hybrid_connection_name": ubx.FieldSpec(wire_name="hybrid_connection_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "listen": ubx.FieldSpec(wire_name="listen"),
        "manage": ubx.FieldSpec(wire_name="manage"),
        "name": ubx.FieldSpec(wire_name="name"),
        "namespace_name": ubx.FieldSpec(wire_name="namespace_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "send": ubx.FieldSpec(wire_name="send"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_HybridConnectionAuthorizationRule_TimeoutsFields,
        ),
    },
)
