# Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_azure_security_center. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DataConnectorAzureSecurityCenter_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_DataConnectorAzureSecurityCenter_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class DataConnectorAzureSecurityCenterConfig:
    id: Any = None
    log_analytics_workspace_id: Any = None
    name: Any = None
    subscription_id: Any = None
    timeouts: Any = None

DataConnectorAzureSecurityCenter = ubx.ResourceBinding(
    wire_type="azurerm_sentinel_data_connector_azure_security_center",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "log_analytics_workspace_id": ubx.FieldSpec(wire_name="log_analytics_workspace_id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "subscription_id": ubx.FieldSpec(wire_name="subscription_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DataConnectorAzureSecurityCenter_TimeoutsFields,
        ),
    },
)
