# Code generated by `ubx sdk gen` from azurerm_sentinel_threat_intelligence_indicator. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ThreatIntelligenceIndicator_ExternalReference:
    description: Any = None
    hashes: Any = None
    id: Any = None
    source_name: Any = None
    url: Any = None

@dataclasses.dataclass
class ThreatIntelligenceIndicator_GranularMarking:
    language: Any = None
    marking_ref: Any = None
    selectors: Any = None

@dataclasses.dataclass
class ThreatIntelligenceIndicator_KillChainPhase:
    name: Any = None

@dataclasses.dataclass
class ThreatIntelligenceIndicator_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ThreatIntelligenceIndicator_ExternalReferenceFields = {
    "description": sdk.FieldSpec(wire_name="description"),
    "hashes": sdk.FieldSpec(wire_name="hashes"),
    "id": sdk.FieldSpec(wire_name="id"),
    "source_name": sdk.FieldSpec(wire_name="source_name"),
    "url": sdk.FieldSpec(wire_name="url"),
}

_ThreatIntelligenceIndicator_GranularMarkingFields = {
    "language": sdk.FieldSpec(wire_name="language"),
    "marking_ref": sdk.FieldSpec(wire_name="marking_ref"),
    "selectors": sdk.FieldSpec(wire_name="selectors"),
}

_ThreatIntelligenceIndicator_KillChainPhaseFields = {
    "name": sdk.FieldSpec(wire_name="name"),
}

_ThreatIntelligenceIndicator_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ThreatIntelligenceIndicatorConfig:
    confidence: Any = None
    created_by: Any = None
    description: Any = None
    display_name: Any = None
    extension: Any = None
    id: Any = None
    language: Any = None
    object_marking_refs: Any = None
    pattern: Any = None
    pattern_type: Any = None
    pattern_version: Any = None
    revoked: Any = None
    source: Any = None
    tags: Any = None
    threat_types: Any = None
    validate_from_utc: Any = None
    validate_until_utc: Any = None
    workspace_id: Any = None
    external_reference: Any = None
    granular_marking: Any = None
    kill_chain_phase: Any = None
    timeouts: Any = None

ThreatIntelligenceIndicator = sdk.ResourceBinding(
    wire_type="azurerm_sentinel_threat_intelligence_indicator",
    fields={
        "confidence": sdk.FieldSpec(wire_name="confidence"),
        "created_by": sdk.FieldSpec(wire_name="created_by"),
        "description": sdk.FieldSpec(wire_name="description"),
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "extension": sdk.FieldSpec(wire_name="extension"),
        "id": sdk.FieldSpec(wire_name="id"),
        "language": sdk.FieldSpec(wire_name="language"),
        "object_marking_refs": sdk.FieldSpec(wire_name="object_marking_refs"),
        "pattern": sdk.FieldSpec(wire_name="pattern"),
        "pattern_type": sdk.FieldSpec(wire_name="pattern_type"),
        "pattern_version": sdk.FieldSpec(wire_name="pattern_version"),
        "revoked": sdk.FieldSpec(wire_name="revoked"),
        "source": sdk.FieldSpec(wire_name="source"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "threat_types": sdk.FieldSpec(wire_name="threat_types"),
        "validate_from_utc": sdk.FieldSpec(wire_name="validate_from_utc"),
        "validate_until_utc": sdk.FieldSpec(wire_name="validate_until_utc"),
        "workspace_id": sdk.FieldSpec(wire_name="workspace_id"),
        "external_reference": sdk.FieldSpec(
            wire_name="external_reference",
            kind="list",
            fields=_ThreatIntelligenceIndicator_ExternalReferenceFields,
        ),
        "granular_marking": sdk.FieldSpec(
            wire_name="granular_marking",
            kind="list",
            fields=_ThreatIntelligenceIndicator_GranularMarkingFields,
        ),
        "kill_chain_phase": sdk.FieldSpec(
            wire_name="kill_chain_phase",
            kind="list",
            fields=_ThreatIntelligenceIndicator_KillChainPhaseFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ThreatIntelligenceIndicator_TimeoutsFields,
        ),
    },
)
