# Code generated by `ubx sdk gen` from azurerm_express_route_circuit_authorization. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class RouteCircuitAuthorization_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_RouteCircuitAuthorization_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class RouteCircuitAuthorizationConfig:
    express_route_circuit_name: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

RouteCircuitAuthorization = sdk.ResourceBinding(
    wire_type="azurerm_express_route_circuit_authorization",
    fields={
        "express_route_circuit_name": sdk.FieldSpec(wire_name="express_route_circuit_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RouteCircuitAuthorization_TimeoutsFields,
        ),
    },
)
