# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .recovery_fabric import RecoveryFabric, RecoveryFabricConfig
from .recovery_hyperv_network_mapping import RecoveryHypervNetworkMapping, RecoveryHypervNetworkMappingConfig
from .recovery_hyperv_replication_policy import RecoveryHypervReplicationPolicy, RecoveryHypervReplicationPolicyConfig
from .recovery_hyperv_replication_policy_association import RecoveryHypervReplicationPolicyAssociation, RecoveryHypervReplicationPolicyAssociationConfig
from .recovery_network_mapping import RecoveryNetworkMapping, RecoveryNetworkMappingConfig
from .recovery_protection_container import RecoveryProtectionContainer, RecoveryProtectionContainerConfig
from .recovery_protection_container_mapping import RecoveryProtectionContainerMapping, RecoveryProtectionContainerMappingConfig
from .recovery_replicated_vm import RecoveryReplicatedVm, RecoveryReplicatedVmConfig
from .recovery_replication_policy import RecoveryReplicationPolicy, RecoveryReplicationPolicyConfig
from .recovery_replication_recovery_plan import RecoveryReplicationRecoveryPlan, RecoveryReplicationRecoveryPlanConfig
from .recovery_services_vault_hyperv_site import RecoveryServicesVaultHypervSite, RecoveryServicesVaultHypervSiteConfig
from .recovery_vmware_replicated_vm import RecoveryVmwareReplicatedVm, RecoveryVmwareReplicatedVmConfig
from .recovery_vmware_replication_policy import RecoveryVmwareReplicationPolicy, RecoveryVmwareReplicationPolicyConfig
from .recovery_vmware_replication_policy_association import RecoveryVmwareReplicationPolicyAssociation, RecoveryVmwareReplicationPolicyAssociationConfig
