# Code generated by `ubx sdk gen` from azurerm_site_recovery_fabric. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class RecoveryFabric_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_RecoveryFabric_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class RecoveryFabricConfig:
    id: Any = None
    location: Any = None
    name: Any = None
    recovery_vault_name: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

RecoveryFabric = sdk.ResourceBinding(
    wire_type="azurerm_site_recovery_fabric",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "recovery_vault_name": sdk.FieldSpec(wire_name="recovery_vault_name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RecoveryFabric_TimeoutsFields,
        ),
    },
)
