# Code generated by `ubx sdk gen` from azurerm_site_recovery_vmware_replication_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RecoveryVmwareReplicationPolicy_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_RecoveryVmwareReplicationPolicy_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class RecoveryVmwareReplicationPolicyConfig:
    application_consistent_snapshot_frequency_in_minutes: Any = None
    id: Any = None
    name: Any = None
    recovery_point_retention_in_minutes: Any = None
    recovery_vault_id: Any = None
    timeouts: Any = None

RecoveryVmwareReplicationPolicy = ubx.ResourceBinding(
    wire_type="azurerm_site_recovery_vmware_replication_policy",
    fields={
        "application_consistent_snapshot_frequency_in_minutes": ubx.FieldSpec(wire_name="application_consistent_snapshot_frequency_in_minutes"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "recovery_point_retention_in_minutes": ubx.FieldSpec(wire_name="recovery_point_retention_in_minutes"),
        "recovery_vault_id": ubx.FieldSpec(wire_name="recovery_vault_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RecoveryVmwareReplicationPolicy_TimeoutsFields,
        ),
    },
)
