# Code generated by `ubx sdk gen` from azurerm_bastion_host. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Host_IpConfiguration:
    name: Any = None
    public_ip_address_id: Any = None
    subnet_id: Any = None

@dataclasses.dataclass
class Host_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Host_IpConfigurationFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "public_ip_address_id": ubx.FieldSpec(wire_name="public_ip_address_id"),
    "subnet_id": ubx.FieldSpec(wire_name="subnet_id"),
}

_Host_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class HostConfig:
    copy_paste_enabled: Any = None
    file_copy_enabled: Any = None
    id: Any = None
    ip_connect_enabled: Any = None
    kerberos_enabled: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    scale_units: Any = None
    session_recording_enabled: Any = None
    shareable_link_enabled: Any = None
    sku: Any = None
    tags: Any = None
    tunneling_enabled: Any = None
    virtual_network_id: Any = None
    zones: Any = None
    ip_configuration: Any = None
    timeouts: Any = None

Host = ubx.ResourceBinding(
    wire_type="azurerm_bastion_host",
    fields={
        "copy_paste_enabled": ubx.FieldSpec(wire_name="copy_paste_enabled"),
        "file_copy_enabled": ubx.FieldSpec(wire_name="file_copy_enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "ip_connect_enabled": ubx.FieldSpec(wire_name="ip_connect_enabled"),
        "kerberos_enabled": ubx.FieldSpec(wire_name="kerberos_enabled"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "scale_units": ubx.FieldSpec(wire_name="scale_units"),
        "session_recording_enabled": ubx.FieldSpec(wire_name="session_recording_enabled"),
        "shareable_link_enabled": ubx.FieldSpec(wire_name="shareable_link_enabled"),
        "sku": ubx.FieldSpec(wire_name="sku"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "tunneling_enabled": ubx.FieldSpec(wire_name="tunneling_enabled"),
        "virtual_network_id": ubx.FieldSpec(wire_name="virtual_network_id"),
        "zones": ubx.FieldSpec(wire_name="zones"),
        "ip_configuration": ubx.FieldSpec(
            wire_name="ip_configuration",
            kind="list",
            fields=_Host_IpConfigurationFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Host_TimeoutsFields,
        ),
    },
)
