# Code generated by `ubx sdk gen` from azurerm_disk_encryption_set. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class EncryptionSet_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class EncryptionSet_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_EncryptionSet_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_EncryptionSet_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class EncryptionSetConfig:
    auto_key_rotation_enabled: Any = None
    encryption_type: Any = None
    federated_client_id: Any = None
    id: Any = None
    key_vault_key_id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    identity: Any = None
    timeouts: Any = None

EncryptionSet = sdk.ResourceBinding(
    wire_type="azurerm_disk_encryption_set",
    fields={
        "auto_key_rotation_enabled": sdk.FieldSpec(wire_name="auto_key_rotation_enabled"),
        "encryption_type": sdk.FieldSpec(wire_name="encryption_type"),
        "federated_client_id": sdk.FieldSpec(wire_name="federated_client_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "key_vault_key_id": sdk.FieldSpec(wire_name="key_vault_key_id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_EncryptionSet_IdentityFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_EncryptionSet_TimeoutsFields,
        ),
    },
)
