# Code generated by `ubx sdk gen` from azurerm_app_service_certificate. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ServiceCertificate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ServiceCertificate_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ServiceCertificateConfig:
    app_service_plan_id: Any = None
    id: Any = None
    key_vault_id: Any = None
    key_vault_secret_id: Any = None
    location: Any = None
    name: Any = None
    password: Any = None
    pfx_blob: Any = None
    resource_group_name: Any = None
    tags: Any = None
    timeouts: Any = None

ServiceCertificate = sdk.ResourceBinding(
    wire_type="azurerm_app_service_certificate",
    fields={
        "app_service_plan_id": sdk.FieldSpec(wire_name="app_service_plan_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "key_vault_id": sdk.FieldSpec(wire_name="key_vault_id"),
        "key_vault_secret_id": sdk.FieldSpec(wire_name="key_vault_secret_id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "password": sdk.FieldSpec(wire_name="password"),
        "pfx_blob": sdk.FieldSpec(wire_name="pfx_blob"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ServiceCertificate_TimeoutsFields,
        ),
    },
)
