# Code generated by `ubx sdk gen` from azurerm_iotcentral_application_network_rule_set. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApplicationNetworkRuleSet_IpRule:
    ip_mask: Any = None
    name: Any = None

@dataclasses.dataclass
class ApplicationNetworkRuleSet_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ApplicationNetworkRuleSet_IpRuleFields = {
    "ip_mask": ubx.FieldSpec(wire_name="ip_mask"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_ApplicationNetworkRuleSet_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ApplicationNetworkRuleSetConfig:
    apply_to_device: Any = None
    default_action: Any = None
    id: Any = None
    iotcentral_application_id: Any = None
    ip_rule: Any = None
    timeouts: Any = None

ApplicationNetworkRuleSet = ubx.ResourceBinding(
    wire_type="azurerm_iotcentral_application_network_rule_set",
    fields={
        "apply_to_device": ubx.FieldSpec(wire_name="apply_to_device"),
        "default_action": ubx.FieldSpec(wire_name="default_action"),
        "id": ubx.FieldSpec(wire_name="id"),
        "iotcentral_application_id": ubx.FieldSpec(wire_name="iotcentral_application_id"),
        "ip_rule": ubx.FieldSpec(
            wire_name="ip_rule",
            kind="list",
            fields=_ApplicationNetworkRuleSet_IpRuleFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ApplicationNetworkRuleSet_TimeoutsFields,
        ),
    },
)
