# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .a_record import ARecord, ARecordConfig
from .aaaa_record import AaaaRecord, AaaaRecordConfig
from .caa_record import CaaRecord, CaaRecordConfig
from .cname_record import CnameRecord, CnameRecordConfig
from .mx_record import MxRecord, MxRecordConfig
from .ns_record import NsRecord, NsRecordConfig
from .ptr_record import PtrRecord, PtrRecordConfig
from .srv_record import SrvRecord, SrvRecordConfig
from .txt_record import TxtRecord, TxtRecordConfig
from .zone import Zone, ZoneConfig
