# Code generated by `ubx sdk gen` from azurerm_dns_ptr_record. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PtrRecord_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_PtrRecord_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PtrRecordConfig:
    id: Any = None
    name: Any = None
    records: Any = None
    resource_group_name: Any = None
    tags: Any = None
    ttl: Any = None
    zone_name: Any = None
    timeouts: Any = None

PtrRecord = ubx.ResourceBinding(
    wire_type="azurerm_dns_ptr_record",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "records": ubx.FieldSpec(wire_name="records"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "ttl": ubx.FieldSpec(wire_name="ttl"),
        "zone_name": ubx.FieldSpec(wire_name="zone_name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PtrRecord_TimeoutsFields,
        ),
    },
)
