# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .directory_domain_service import DirectoryDomainService, DirectoryDomainServiceConfig
from .directory_domain_service_replica_set import DirectoryDomainServiceReplicaSet, DirectoryDomainServiceReplicaSetConfig
from .directory_domain_service_trust import DirectoryDomainServiceTrust, DirectoryDomainServiceTrustConfig
