# Code generated by `ubx sdk gen` from azurerm_arc_kubernetes_cluster_extension. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class KubernetesClusterExtension_Identity:
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class KubernetesClusterExtension_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_KubernetesClusterExtension_IdentityFields = {
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_KubernetesClusterExtension_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class KubernetesClusterExtensionConfig:
    cluster_id: Any = None
    configuration_protected_settings: Any = None
    configuration_settings: Any = None
    extension_type: Any = None
    id: Any = None
    name: Any = None
    release_namespace: Any = None
    release_train: Any = None
    target_namespace: Any = None
    version: Any = None
    identity: Any = None
    timeouts: Any = None

KubernetesClusterExtension = ubx.ResourceBinding(
    wire_type="azurerm_arc_kubernetes_cluster_extension",
    fields={
        "cluster_id": ubx.FieldSpec(wire_name="cluster_id"),
        "configuration_protected_settings": ubx.FieldSpec(wire_name="configuration_protected_settings"),
        "configuration_settings": ubx.FieldSpec(wire_name="configuration_settings"),
        "extension_type": ubx.FieldSpec(wire_name="extension_type"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "release_namespace": ubx.FieldSpec(wire_name="release_namespace"),
        "release_train": ubx.FieldSpec(wire_name="release_train"),
        "target_namespace": ubx.FieldSpec(wire_name="target_namespace"),
        "version": ubx.FieldSpec(wire_name="version"),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_KubernetesClusterExtension_IdentityFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_KubernetesClusterExtension_TimeoutsFields,
        ),
    },
)
