# Code generated by `ubx sdk gen` from azurerm_arc_machine_extension. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MachineExtension_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_MachineExtension_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class MachineExtensionConfig:
    arc_machine_id: Any = None
    automatic_upgrade_enabled: Any = None
    force_update_tag: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    protected_settings: Any = None
    publisher: Any = None
    settings: Any = None
    tags: Any = None
    type: Any = None
    type_handler_version: Any = None
    timeouts: Any = None

MachineExtension = ubx.ResourceBinding(
    wire_type="azurerm_arc_machine_extension",
    fields={
        "arc_machine_id": ubx.FieldSpec(wire_name="arc_machine_id"),
        "automatic_upgrade_enabled": ubx.FieldSpec(wire_name="automatic_upgrade_enabled"),
        "force_update_tag": ubx.FieldSpec(wire_name="force_update_tag"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "protected_settings": ubx.FieldSpec(wire_name="protected_settings"),
        "publisher": ubx.FieldSpec(wire_name="publisher"),
        "settings": ubx.FieldSpec(wire_name="settings"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "type": ubx.FieldSpec(wire_name="type"),
        "type_handler_version": ubx.FieldSpec(wire_name="type_handler_version"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_MachineExtension_TimeoutsFields,
        ),
    },
)
