# Code generated by `ubx sdk gen` from azurerm_function_app_flex_consumption. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AppFlexConsumption_AlwaysReady:
    instance_count: Any = None
    name: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettings_ActiveDirectory:
    allowed_audiences: Any = None
    client_id: Any = None
    client_secret: Any = None
    client_secret_setting_name: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettings_Facebook:
    app_id: Any = None
    app_secret: Any = None
    app_secret_setting_name: Any = None
    oauth_scopes: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettings_Github:
    client_id: Any = None
    client_secret: Any = None
    client_secret_setting_name: Any = None
    oauth_scopes: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettings_Twitter:
    consumer_key: Any = None
    consumer_secret: Any = None
    consumer_secret_setting_name: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettings:
    additional_login_parameters: Any = None
    allowed_external_redirect_urls: Any = None
    default_provider: Any = None
    enabled: Any = None
    issuer: Any = None
    runtime_version: Any = None
    token_refresh_extension_hours: Any = None
    token_store_enabled: Any = None
    unauthenticated_client_action: Any = None
    active_directory: Any = None
    facebook: Any = None
    github: Any = None
    google: Any = None
    microsoft: Any = None
    twitter: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_ActiveDirectoryV2:
    allowed_applications: Any = None
    allowed_audiences: Any = None
    allowed_groups: Any = None
    allowed_identities: Any = None
    client_id: Any = None
    client_secret_certificate_thumbprint: Any = None
    client_secret_setting_name: Any = None
    jwt_allowed_client_applications: Any = None
    jwt_allowed_groups: Any = None
    login_parameters: Any = None
    tenant_auth_endpoint: Any = None
    www_authentication_disabled: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_AppleV2:
    client_id: Any = None
    client_secret_setting_name: Any = None
    login_scopes: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_AzureStaticWebAppV2:
    client_id: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_CustomOidcV2:
    authorisation_endpoint: Any = None
    certification_uri: Any = None
    client_credential_method: Any = None
    client_id: Any = None
    client_secret_setting_name: Any = None
    issuer_endpoint: Any = None
    name: Any = None
    name_claim_type: Any = None
    openid_configuration_endpoint: Any = None
    scopes: Any = None
    token_endpoint: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_FacebookV2:
    app_id: Any = None
    app_secret_setting_name: Any = None
    graph_api_version: Any = None
    login_scopes: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_GoogleV2:
    allowed_audiences: Any = None
    client_id: Any = None
    client_secret_setting_name: Any = None
    login_scopes: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_Login:
    allowed_external_redirect_urls: Any = None
    cookie_expiration_convention: Any = None
    cookie_expiration_time: Any = None
    logout_endpoint: Any = None
    nonce_expiration_time: Any = None
    preserve_url_fragments_for_logins: Any = None
    token_refresh_extension_time: Any = None
    token_store_enabled: Any = None
    token_store_path: Any = None
    token_store_sas_setting_name: Any = None
    validate_nonce: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2_TwitterV2:
    consumer_key: Any = None
    consumer_secret_setting_name: Any = None

@dataclasses.dataclass
class AppFlexConsumption_AuthSettingsV2:
    auth_enabled: Any = None
    config_file_path: Any = None
    default_provider: Any = None
    excluded_paths: Any = None
    forward_proxy_convention: Any = None
    forward_proxy_custom_host_header_name: Any = None
    forward_proxy_custom_scheme_header_name: Any = None
    http_route_api_prefix: Any = None
    require_authentication: Any = None
    require_https: Any = None
    runtime_version: Any = None
    unauthenticated_action: Any = None
    active_directory_v2: Any = None
    apple_v2: Any = None
    azure_static_web_app_v2: Any = None
    custom_oidc_v2: Any = None
    facebook_v2: Any = None
    github_v2: Any = None
    google_v2: Any = None
    login: Any = None
    microsoft_v2: Any = None
    twitter_v2: Any = None

@dataclasses.dataclass
class AppFlexConsumption_ConnectionString:
    name: Any = None
    type: Any = None
    value: Any = None

@dataclasses.dataclass
class AppFlexConsumption_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class AppFlexConsumption_SiteConfig_AppServiceLogs:
    disk_quota_mb: Any = None
    retention_period_days: Any = None

@dataclasses.dataclass
class AppFlexConsumption_SiteConfig_Cors:
    allowed_origins: Any = None
    support_credentials: Any = None

@dataclasses.dataclass
class AppFlexConsumption_SiteConfig_IpRestriction_Headers:
    x_azure_fdid: Any = None
    x_fd_health_probe: Any = None
    x_forwarded_for: Any = None
    x_forwarded_host: Any = None

@dataclasses.dataclass
class AppFlexConsumption_SiteConfig_IpRestriction:
    action: Any = None
    description: Any = None
    headers: Any = None
    ip_address: Any = None
    name: Any = None
    priority: Any = None
    service_tag: Any = None
    virtual_network_subnet_id: Any = None

@dataclasses.dataclass
class AppFlexConsumption_SiteConfig:
    api_definition_url: Any = None
    api_management_api_id: Any = None
    app_command_line: Any = None
    application_insights_connection_string: Any = None
    application_insights_key: Any = None
    container_registry_managed_identity_client_id: Any = None
    container_registry_use_managed_identity: Any = None
    default_documents: Any = None
    detailed_error_logging_enabled: Any = None
    elastic_instance_minimum: Any = None
    health_check_eviction_time_in_min: Any = None
    health_check_path: Any = None
    http2_enabled: Any = None
    ip_restriction_default_action: Any = None
    load_balancing_mode: Any = None
    managed_pipeline_mode: Any = None
    minimum_tls_version: Any = None
    remote_debugging_enabled: Any = None
    remote_debugging_version: Any = None
    runtime_scale_monitoring_enabled: Any = None
    scm_ip_restriction_default_action: Any = None
    scm_minimum_tls_version: Any = None
    scm_type: Any = None
    scm_use_main_ip_restriction: Any = None
    use_32_bit_worker: Any = None
    vnet_route_all_enabled: Any = None
    websockets_enabled: Any = None
    worker_count: Any = None
    app_service_logs: Any = None
    cors: Any = None
    ip_restriction: Any = None
    scm_ip_restriction: Any = None

@dataclasses.dataclass
class AppFlexConsumption_StickySettings:
    app_setting_names: Any = None
    connection_string_names: Any = None

@dataclasses.dataclass
class AppFlexConsumption_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppFlexConsumption_AlwaysReadyFields = {
    "instance_count": sdk.FieldSpec(wire_name="instance_count"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_AppFlexConsumption_AuthSettings_ActiveDirectoryFields = {
    "allowed_audiences": sdk.FieldSpec(wire_name="allowed_audiences"),
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret": sdk.FieldSpec(wire_name="client_secret"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
}

_AppFlexConsumption_AuthSettings_FacebookFields = {
    "app_id": sdk.FieldSpec(wire_name="app_id"),
    "app_secret": sdk.FieldSpec(wire_name="app_secret"),
    "app_secret_setting_name": sdk.FieldSpec(wire_name="app_secret_setting_name"),
    "oauth_scopes": sdk.FieldSpec(wire_name="oauth_scopes"),
}

_AppFlexConsumption_AuthSettings_GithubFields = {
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret": sdk.FieldSpec(wire_name="client_secret"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
    "oauth_scopes": sdk.FieldSpec(wire_name="oauth_scopes"),
}

_AppFlexConsumption_AuthSettings_TwitterFields = {
    "consumer_key": sdk.FieldSpec(wire_name="consumer_key"),
    "consumer_secret": sdk.FieldSpec(wire_name="consumer_secret"),
    "consumer_secret_setting_name": sdk.FieldSpec(wire_name="consumer_secret_setting_name"),
}

_AppFlexConsumption_AuthSettingsFields = {
    "additional_login_parameters": sdk.FieldSpec(wire_name="additional_login_parameters"),
    "allowed_external_redirect_urls": sdk.FieldSpec(wire_name="allowed_external_redirect_urls"),
    "default_provider": sdk.FieldSpec(wire_name="default_provider"),
    "enabled": sdk.FieldSpec(wire_name="enabled"),
    "issuer": sdk.FieldSpec(wire_name="issuer"),
    "runtime_version": sdk.FieldSpec(wire_name="runtime_version"),
    "token_refresh_extension_hours": sdk.FieldSpec(wire_name="token_refresh_extension_hours"),
    "token_store_enabled": sdk.FieldSpec(wire_name="token_store_enabled"),
    "unauthenticated_client_action": sdk.FieldSpec(wire_name="unauthenticated_client_action"),
    "active_directory": sdk.FieldSpec(
        wire_name="active_directory",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_ActiveDirectoryFields,
    ),
    "facebook": sdk.FieldSpec(
        wire_name="facebook",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_FacebookFields,
    ),
    "github": sdk.FieldSpec(
        wire_name="github",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_GithubFields,
    ),
    "google": sdk.FieldSpec(
        wire_name="google",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_GithubFields,
    ),
    "microsoft": sdk.FieldSpec(
        wire_name="microsoft",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_GithubFields,
    ),
    "twitter": sdk.FieldSpec(
        wire_name="twitter",
        kind="list",
        fields=_AppFlexConsumption_AuthSettings_TwitterFields,
    ),
}

_AppFlexConsumption_AuthSettingsV2_ActiveDirectoryV2Fields = {
    "allowed_applications": sdk.FieldSpec(wire_name="allowed_applications"),
    "allowed_audiences": sdk.FieldSpec(wire_name="allowed_audiences"),
    "allowed_groups": sdk.FieldSpec(wire_name="allowed_groups"),
    "allowed_identities": sdk.FieldSpec(wire_name="allowed_identities"),
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret_certificate_thumbprint": sdk.FieldSpec(wire_name="client_secret_certificate_thumbprint"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
    "jwt_allowed_client_applications": sdk.FieldSpec(wire_name="jwt_allowed_client_applications"),
    "jwt_allowed_groups": sdk.FieldSpec(wire_name="jwt_allowed_groups"),
    "login_parameters": sdk.FieldSpec(wire_name="login_parameters"),
    "tenant_auth_endpoint": sdk.FieldSpec(wire_name="tenant_auth_endpoint"),
    "www_authentication_disabled": sdk.FieldSpec(wire_name="www_authentication_disabled"),
}

_AppFlexConsumption_AuthSettingsV2_AppleV2Fields = {
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
    "login_scopes": sdk.FieldSpec(wire_name="login_scopes"),
}

_AppFlexConsumption_AuthSettingsV2_AzureStaticWebAppV2Fields = {
    "client_id": sdk.FieldSpec(wire_name="client_id"),
}

_AppFlexConsumption_AuthSettingsV2_CustomOidcV2Fields = {
    "authorisation_endpoint": sdk.FieldSpec(wire_name="authorisation_endpoint"),
    "certification_uri": sdk.FieldSpec(wire_name="certification_uri"),
    "client_credential_method": sdk.FieldSpec(wire_name="client_credential_method"),
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
    "issuer_endpoint": sdk.FieldSpec(wire_name="issuer_endpoint"),
    "name": sdk.FieldSpec(wire_name="name"),
    "name_claim_type": sdk.FieldSpec(wire_name="name_claim_type"),
    "openid_configuration_endpoint": sdk.FieldSpec(wire_name="openid_configuration_endpoint"),
    "scopes": sdk.FieldSpec(wire_name="scopes"),
    "token_endpoint": sdk.FieldSpec(wire_name="token_endpoint"),
}

_AppFlexConsumption_AuthSettingsV2_FacebookV2Fields = {
    "app_id": sdk.FieldSpec(wire_name="app_id"),
    "app_secret_setting_name": sdk.FieldSpec(wire_name="app_secret_setting_name"),
    "graph_api_version": sdk.FieldSpec(wire_name="graph_api_version"),
    "login_scopes": sdk.FieldSpec(wire_name="login_scopes"),
}

_AppFlexConsumption_AuthSettingsV2_GoogleV2Fields = {
    "allowed_audiences": sdk.FieldSpec(wire_name="allowed_audiences"),
    "client_id": sdk.FieldSpec(wire_name="client_id"),
    "client_secret_setting_name": sdk.FieldSpec(wire_name="client_secret_setting_name"),
    "login_scopes": sdk.FieldSpec(wire_name="login_scopes"),
}

_AppFlexConsumption_AuthSettingsV2_LoginFields = {
    "allowed_external_redirect_urls": sdk.FieldSpec(wire_name="allowed_external_redirect_urls"),
    "cookie_expiration_convention": sdk.FieldSpec(wire_name="cookie_expiration_convention"),
    "cookie_expiration_time": sdk.FieldSpec(wire_name="cookie_expiration_time"),
    "logout_endpoint": sdk.FieldSpec(wire_name="logout_endpoint"),
    "nonce_expiration_time": sdk.FieldSpec(wire_name="nonce_expiration_time"),
    "preserve_url_fragments_for_logins": sdk.FieldSpec(wire_name="preserve_url_fragments_for_logins"),
    "token_refresh_extension_time": sdk.FieldSpec(wire_name="token_refresh_extension_time"),
    "token_store_enabled": sdk.FieldSpec(wire_name="token_store_enabled"),
    "token_store_path": sdk.FieldSpec(wire_name="token_store_path"),
    "token_store_sas_setting_name": sdk.FieldSpec(wire_name="token_store_sas_setting_name"),
    "validate_nonce": sdk.FieldSpec(wire_name="validate_nonce"),
}

_AppFlexConsumption_AuthSettingsV2_TwitterV2Fields = {
    "consumer_key": sdk.FieldSpec(wire_name="consumer_key"),
    "consumer_secret_setting_name": sdk.FieldSpec(wire_name="consumer_secret_setting_name"),
}

_AppFlexConsumption_AuthSettingsV2Fields = {
    "auth_enabled": sdk.FieldSpec(wire_name="auth_enabled"),
    "config_file_path": sdk.FieldSpec(wire_name="config_file_path"),
    "default_provider": sdk.FieldSpec(wire_name="default_provider"),
    "excluded_paths": sdk.FieldSpec(wire_name="excluded_paths"),
    "forward_proxy_convention": sdk.FieldSpec(wire_name="forward_proxy_convention"),
    "forward_proxy_custom_host_header_name": sdk.FieldSpec(wire_name="forward_proxy_custom_host_header_name"),
    "forward_proxy_custom_scheme_header_name": sdk.FieldSpec(wire_name="forward_proxy_custom_scheme_header_name"),
    "http_route_api_prefix": sdk.FieldSpec(wire_name="http_route_api_prefix"),
    "require_authentication": sdk.FieldSpec(wire_name="require_authentication"),
    "require_https": sdk.FieldSpec(wire_name="require_https"),
    "runtime_version": sdk.FieldSpec(wire_name="runtime_version"),
    "unauthenticated_action": sdk.FieldSpec(wire_name="unauthenticated_action"),
    "active_directory_v2": sdk.FieldSpec(
        wire_name="active_directory_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_ActiveDirectoryV2Fields,
    ),
    "apple_v2": sdk.FieldSpec(
        wire_name="apple_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_AppleV2Fields,
    ),
    "azure_static_web_app_v2": sdk.FieldSpec(
        wire_name="azure_static_web_app_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_AzureStaticWebAppV2Fields,
    ),
    "custom_oidc_v2": sdk.FieldSpec(
        wire_name="custom_oidc_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_CustomOidcV2Fields,
    ),
    "facebook_v2": sdk.FieldSpec(
        wire_name="facebook_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_FacebookV2Fields,
    ),
    "github_v2": sdk.FieldSpec(
        wire_name="github_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_AppleV2Fields,
    ),
    "google_v2": sdk.FieldSpec(
        wire_name="google_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_GoogleV2Fields,
    ),
    "login": sdk.FieldSpec(
        wire_name="login",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_LoginFields,
    ),
    "microsoft_v2": sdk.FieldSpec(
        wire_name="microsoft_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_GoogleV2Fields,
    ),
    "twitter_v2": sdk.FieldSpec(
        wire_name="twitter_v2",
        kind="list",
        fields=_AppFlexConsumption_AuthSettingsV2_TwitterV2Fields,
    ),
}

_AppFlexConsumption_ConnectionStringFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "type": sdk.FieldSpec(wire_name="type"),
    "value": sdk.FieldSpec(wire_name="value"),
}

_AppFlexConsumption_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_AppFlexConsumption_SiteConfig_AppServiceLogsFields = {
    "disk_quota_mb": sdk.FieldSpec(wire_name="disk_quota_mb"),
    "retention_period_days": sdk.FieldSpec(wire_name="retention_period_days"),
}

_AppFlexConsumption_SiteConfig_CorsFields = {
    "allowed_origins": sdk.FieldSpec(wire_name="allowed_origins"),
    "support_credentials": sdk.FieldSpec(wire_name="support_credentials"),
}

_AppFlexConsumption_SiteConfig_IpRestriction_HeadersFields = {
    "x_azure_fdid": sdk.FieldSpec(wire_name="x_azure_fdid"),
    "x_fd_health_probe": sdk.FieldSpec(wire_name="x_fd_health_probe"),
    "x_forwarded_for": sdk.FieldSpec(wire_name="x_forwarded_for"),
    "x_forwarded_host": sdk.FieldSpec(wire_name="x_forwarded_host"),
}

_AppFlexConsumption_SiteConfig_IpRestrictionFields = {
    "action": sdk.FieldSpec(wire_name="action"),
    "description": sdk.FieldSpec(wire_name="description"),
    "headers": sdk.FieldSpec(
        wire_name="headers",
        kind="list",
        fields=_AppFlexConsumption_SiteConfig_IpRestriction_HeadersFields,
    ),
    "ip_address": sdk.FieldSpec(wire_name="ip_address"),
    "name": sdk.FieldSpec(wire_name="name"),
    "priority": sdk.FieldSpec(wire_name="priority"),
    "service_tag": sdk.FieldSpec(wire_name="service_tag"),
    "virtual_network_subnet_id": sdk.FieldSpec(wire_name="virtual_network_subnet_id"),
}

_AppFlexConsumption_SiteConfigFields = {
    "api_definition_url": sdk.FieldSpec(wire_name="api_definition_url"),
    "api_management_api_id": sdk.FieldSpec(wire_name="api_management_api_id"),
    "app_command_line": sdk.FieldSpec(wire_name="app_command_line"),
    "application_insights_connection_string": sdk.FieldSpec(wire_name="application_insights_connection_string"),
    "application_insights_key": sdk.FieldSpec(wire_name="application_insights_key"),
    "container_registry_managed_identity_client_id": sdk.FieldSpec(wire_name="container_registry_managed_identity_client_id"),
    "container_registry_use_managed_identity": sdk.FieldSpec(wire_name="container_registry_use_managed_identity"),
    "default_documents": sdk.FieldSpec(wire_name="default_documents"),
    "detailed_error_logging_enabled": sdk.FieldSpec(wire_name="detailed_error_logging_enabled"),
    "elastic_instance_minimum": sdk.FieldSpec(wire_name="elastic_instance_minimum"),
    "health_check_eviction_time_in_min": sdk.FieldSpec(wire_name="health_check_eviction_time_in_min"),
    "health_check_path": sdk.FieldSpec(wire_name="health_check_path"),
    "http2_enabled": sdk.FieldSpec(wire_name="http2_enabled"),
    "ip_restriction_default_action": sdk.FieldSpec(wire_name="ip_restriction_default_action"),
    "load_balancing_mode": sdk.FieldSpec(wire_name="load_balancing_mode"),
    "managed_pipeline_mode": sdk.FieldSpec(wire_name="managed_pipeline_mode"),
    "minimum_tls_version": sdk.FieldSpec(wire_name="minimum_tls_version"),
    "remote_debugging_enabled": sdk.FieldSpec(wire_name="remote_debugging_enabled"),
    "remote_debugging_version": sdk.FieldSpec(wire_name="remote_debugging_version"),
    "runtime_scale_monitoring_enabled": sdk.FieldSpec(wire_name="runtime_scale_monitoring_enabled"),
    "scm_ip_restriction_default_action": sdk.FieldSpec(wire_name="scm_ip_restriction_default_action"),
    "scm_minimum_tls_version": sdk.FieldSpec(wire_name="scm_minimum_tls_version"),
    "scm_type": sdk.FieldSpec(wire_name="scm_type"),
    "scm_use_main_ip_restriction": sdk.FieldSpec(wire_name="scm_use_main_ip_restriction"),
    "use_32_bit_worker": sdk.FieldSpec(wire_name="use_32_bit_worker"),
    "vnet_route_all_enabled": sdk.FieldSpec(wire_name="vnet_route_all_enabled"),
    "websockets_enabled": sdk.FieldSpec(wire_name="websockets_enabled"),
    "worker_count": sdk.FieldSpec(wire_name="worker_count"),
    "app_service_logs": sdk.FieldSpec(
        wire_name="app_service_logs",
        kind="list",
        fields=_AppFlexConsumption_SiteConfig_AppServiceLogsFields,
    ),
    "cors": sdk.FieldSpec(
        wire_name="cors",
        kind="list",
        fields=_AppFlexConsumption_SiteConfig_CorsFields,
    ),
    "ip_restriction": sdk.FieldSpec(
        wire_name="ip_restriction",
        kind="list",
        fields=_AppFlexConsumption_SiteConfig_IpRestrictionFields,
    ),
    "scm_ip_restriction": sdk.FieldSpec(
        wire_name="scm_ip_restriction",
        kind="list",
        fields=_AppFlexConsumption_SiteConfig_IpRestrictionFields,
    ),
}

_AppFlexConsumption_StickySettingsFields = {
    "app_setting_names": sdk.FieldSpec(wire_name="app_setting_names"),
    "connection_string_names": sdk.FieldSpec(wire_name="connection_string_names"),
}

_AppFlexConsumption_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppFlexConsumptionConfig:
    app_settings: Any = None
    client_certificate_enabled: Any = None
    client_certificate_exclusion_paths: Any = None
    client_certificate_mode: Any = None
    enabled: Any = None
    http_concurrency: Any = None
    https_only: Any = None
    id: Any = None
    instance_memory_in_mb: Any = None
    location: Any = None
    maximum_instance_count: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    runtime_name: Any = None
    runtime_version: Any = None
    service_plan_id: Any = None
    storage_access_key: Any = None
    storage_authentication_type: Any = None
    storage_container_endpoint: Any = None
    storage_container_type: Any = None
    storage_user_assigned_identity_id: Any = None
    tags: Any = None
    virtual_network_subnet_id: Any = None
    webdeploy_publish_basic_authentication_enabled: Any = None
    zip_deploy_file: Any = None
    always_ready: Any = None
    auth_settings: Any = None
    auth_settings_v2: Any = None
    connection_string: Any = None
    identity: Any = None
    site_config: Any = None
    sticky_settings: Any = None
    timeouts: Any = None

AppFlexConsumption = sdk.ResourceBinding(
    wire_type="azurerm_function_app_flex_consumption",
    fields={
        "app_settings": sdk.FieldSpec(wire_name="app_settings"),
        "client_certificate_enabled": sdk.FieldSpec(wire_name="client_certificate_enabled"),
        "client_certificate_exclusion_paths": sdk.FieldSpec(wire_name="client_certificate_exclusion_paths"),
        "client_certificate_mode": sdk.FieldSpec(wire_name="client_certificate_mode"),
        "enabled": sdk.FieldSpec(wire_name="enabled"),
        "http_concurrency": sdk.FieldSpec(wire_name="http_concurrency"),
        "https_only": sdk.FieldSpec(wire_name="https_only"),
        "id": sdk.FieldSpec(wire_name="id"),
        "instance_memory_in_mb": sdk.FieldSpec(wire_name="instance_memory_in_mb"),
        "location": sdk.FieldSpec(wire_name="location"),
        "maximum_instance_count": sdk.FieldSpec(wire_name="maximum_instance_count"),
        "name": sdk.FieldSpec(wire_name="name"),
        "public_network_access_enabled": sdk.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "runtime_name": sdk.FieldSpec(wire_name="runtime_name"),
        "runtime_version": sdk.FieldSpec(wire_name="runtime_version"),
        "service_plan_id": sdk.FieldSpec(wire_name="service_plan_id"),
        "storage_access_key": sdk.FieldSpec(wire_name="storage_access_key"),
        "storage_authentication_type": sdk.FieldSpec(wire_name="storage_authentication_type"),
        "storage_container_endpoint": sdk.FieldSpec(wire_name="storage_container_endpoint"),
        "storage_container_type": sdk.FieldSpec(wire_name="storage_container_type"),
        "storage_user_assigned_identity_id": sdk.FieldSpec(wire_name="storage_user_assigned_identity_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "virtual_network_subnet_id": sdk.FieldSpec(wire_name="virtual_network_subnet_id"),
        "webdeploy_publish_basic_authentication_enabled": sdk.FieldSpec(wire_name="webdeploy_publish_basic_authentication_enabled"),
        "zip_deploy_file": sdk.FieldSpec(wire_name="zip_deploy_file"),
        "always_ready": sdk.FieldSpec(
            wire_name="always_ready",
            kind="list",
            fields=_AppFlexConsumption_AlwaysReadyFields,
        ),
        "auth_settings": sdk.FieldSpec(
            wire_name="auth_settings",
            kind="list",
            fields=_AppFlexConsumption_AuthSettingsFields,
        ),
        "auth_settings_v2": sdk.FieldSpec(
            wire_name="auth_settings_v2",
            kind="list",
            fields=_AppFlexConsumption_AuthSettingsV2Fields,
        ),
        "connection_string": sdk.FieldSpec(
            wire_name="connection_string",
            kind="set",
            fields=_AppFlexConsumption_ConnectionStringFields,
        ),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_AppFlexConsumption_IdentityFields,
        ),
        "site_config": sdk.FieldSpec(
            wire_name="site_config",
            kind="list",
            fields=_AppFlexConsumption_SiteConfigFields,
        ),
        "sticky_settings": sdk.FieldSpec(
            wire_name="sticky_settings",
            kind="list",
            fields=_AppFlexConsumption_StickySettingsFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppFlexConsumption_TimeoutsFields,
        ),
    },
)
