# Code generated by `ubx sdk gen` from azurerm_availability_set. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Set_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Set_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SetConfig:
    id: Any = None
    location: Any = None
    managed: Any = None
    name: Any = None
    platform_fault_domain_count: Any = None
    platform_update_domain_count: Any = None
    proximity_placement_group_id: Any = None
    resource_group_name: Any = None
    tags: Any = None
    timeouts: Any = None

Set = ubx.ResourceBinding(
    wire_type="azurerm_availability_set",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "managed": ubx.FieldSpec(wire_name="managed"),
        "name": ubx.FieldSpec(wire_name="name"),
        "platform_fault_domain_count": ubx.FieldSpec(wire_name="platform_fault_domain_count"),
        "platform_update_domain_count": ubx.FieldSpec(wire_name="platform_update_domain_count"),
        "proximity_placement_group_id": ubx.FieldSpec(wire_name="proximity_placement_group_id"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Set_TimeoutsFields,
        ),
    },
)
