# Code generated by `ubx sdk gen` from azurerm_machine_learning_compute_cluster. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class LearningComputeCluster_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class LearningComputeCluster_ScaleSettings:
    max_node_count: Any = None
    min_node_count: Any = None
    scale_down_nodes_after_idle_duration: Any = None

@dataclasses.dataclass
class LearningComputeCluster_Ssh:
    admin_password: Any = None
    admin_username: Any = None
    key_value: Any = None

@dataclasses.dataclass
class LearningComputeCluster_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_LearningComputeCluster_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_LearningComputeCluster_ScaleSettingsFields = {
    "max_node_count": sdk.FieldSpec(wire_name="max_node_count"),
    "min_node_count": sdk.FieldSpec(wire_name="min_node_count"),
    "scale_down_nodes_after_idle_duration": sdk.FieldSpec(wire_name="scale_down_nodes_after_idle_duration"),
}

_LearningComputeCluster_SshFields = {
    "admin_password": sdk.FieldSpec(wire_name="admin_password"),
    "admin_username": sdk.FieldSpec(wire_name="admin_username"),
    "key_value": sdk.FieldSpec(wire_name="key_value"),
}

_LearningComputeCluster_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class LearningComputeClusterConfig:
    description: Any = None
    id: Any = None
    local_auth_enabled: Any = None
    location: Any = None
    machine_learning_workspace_id: Any = None
    name: Any = None
    node_public_ip_enabled: Any = None
    ssh_public_access_enabled: Any = None
    subnet_resource_id: Any = None
    tags: Any = None
    vm_priority: Any = None
    vm_size: Any = None
    identity: Any = None
    scale_settings: Any = None
    ssh: Any = None
    timeouts: Any = None

LearningComputeCluster = sdk.ResourceBinding(
    wire_type="azurerm_machine_learning_compute_cluster",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "local_auth_enabled": sdk.FieldSpec(wire_name="local_auth_enabled"),
        "location": sdk.FieldSpec(wire_name="location"),
        "machine_learning_workspace_id": sdk.FieldSpec(wire_name="machine_learning_workspace_id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "node_public_ip_enabled": sdk.FieldSpec(wire_name="node_public_ip_enabled"),
        "ssh_public_access_enabled": sdk.FieldSpec(wire_name="ssh_public_access_enabled"),
        "subnet_resource_id": sdk.FieldSpec(wire_name="subnet_resource_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "vm_priority": sdk.FieldSpec(wire_name="vm_priority"),
        "vm_size": sdk.FieldSpec(wire_name="vm_size"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_LearningComputeCluster_IdentityFields,
        ),
        "scale_settings": sdk.FieldSpec(
            wire_name="scale_settings",
            kind="list",
            fields=_LearningComputeCluster_ScaleSettingsFields,
        ),
        "ssh": sdk.FieldSpec(
            wire_name="ssh",
            kind="list",
            fields=_LearningComputeCluster_SshFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_LearningComputeCluster_TimeoutsFields,
        ),
    },
)
