# Code generated by `ubx sdk gen` from azurerm_windows_virtual_machine. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class VirtualMachine_AdditionalCapabilities:
    hibernation_enabled: Any = None
    ultra_ssd_enabled: Any = None

@dataclasses.dataclass
class VirtualMachine_AdditionalUnattendContent:
    content: Any = None
    setting: Any = None

@dataclasses.dataclass
class VirtualMachine_BootDiagnostics:
    storage_account_uri: Any = None

@dataclasses.dataclass
class VirtualMachine_GalleryApplication:
    automatic_upgrade_enabled: Any = None
    configuration_blob_uri: Any = None
    order: Any = None
    tag: Any = None
    treat_failure_as_deployment_failure_enabled: Any = None
    version_id: Any = None

@dataclasses.dataclass
class VirtualMachine_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class VirtualMachine_OsDisk_DiffDiskSettings:
    option: Any = None
    placement: Any = None

@dataclasses.dataclass
class VirtualMachine_OsDisk:
    caching: Any = None
    disk_encryption_set_id: Any = None
    disk_size_gb: Any = None
    id: Any = None
    name: Any = None
    secure_vm_disk_encryption_set_id: Any = None
    security_encryption_type: Any = None
    storage_account_type: Any = None
    write_accelerator_enabled: Any = None
    diff_disk_settings: Any = None

@dataclasses.dataclass
class VirtualMachine_OsImageNotification:
    timeout: Any = None

@dataclasses.dataclass
class VirtualMachine_Plan:
    name: Any = None
    product: Any = None
    publisher: Any = None

@dataclasses.dataclass
class VirtualMachine_Secret_Certificate:
    store: Any = None
    url: Any = None

@dataclasses.dataclass
class VirtualMachine_Secret:
    key_vault_id: Any = None
    certificate: Any = None

@dataclasses.dataclass
class VirtualMachine_SourceImageReference:
    offer: Any = None
    publisher: Any = None
    sku: Any = None
    version: Any = None

@dataclasses.dataclass
class VirtualMachine_TerminationNotification:
    enabled: Any = None
    timeout: Any = None

@dataclasses.dataclass
class VirtualMachine_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class VirtualMachine_WinrmListener:
    certificate_url: Any = None
    protocol: Any = None

_VirtualMachine_AdditionalCapabilitiesFields = {
    "hibernation_enabled": sdk.FieldSpec(wire_name="hibernation_enabled"),
    "ultra_ssd_enabled": sdk.FieldSpec(wire_name="ultra_ssd_enabled"),
}

_VirtualMachine_AdditionalUnattendContentFields = {
    "content": sdk.FieldSpec(wire_name="content"),
    "setting": sdk.FieldSpec(wire_name="setting"),
}

_VirtualMachine_BootDiagnosticsFields = {
    "storage_account_uri": sdk.FieldSpec(wire_name="storage_account_uri"),
}

_VirtualMachine_GalleryApplicationFields = {
    "automatic_upgrade_enabled": sdk.FieldSpec(wire_name="automatic_upgrade_enabled"),
    "configuration_blob_uri": sdk.FieldSpec(wire_name="configuration_blob_uri"),
    "order": sdk.FieldSpec(wire_name="order"),
    "tag": sdk.FieldSpec(wire_name="tag"),
    "treat_failure_as_deployment_failure_enabled": sdk.FieldSpec(wire_name="treat_failure_as_deployment_failure_enabled"),
    "version_id": sdk.FieldSpec(wire_name="version_id"),
}

_VirtualMachine_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_VirtualMachine_OsDisk_DiffDiskSettingsFields = {
    "option": sdk.FieldSpec(wire_name="option"),
    "placement": sdk.FieldSpec(wire_name="placement"),
}

_VirtualMachine_OsDiskFields = {
    "caching": sdk.FieldSpec(wire_name="caching"),
    "disk_encryption_set_id": sdk.FieldSpec(wire_name="disk_encryption_set_id"),
    "disk_size_gb": sdk.FieldSpec(wire_name="disk_size_gb"),
    "id": sdk.FieldSpec(wire_name="id"),
    "name": sdk.FieldSpec(wire_name="name"),
    "secure_vm_disk_encryption_set_id": sdk.FieldSpec(wire_name="secure_vm_disk_encryption_set_id"),
    "security_encryption_type": sdk.FieldSpec(wire_name="security_encryption_type"),
    "storage_account_type": sdk.FieldSpec(wire_name="storage_account_type"),
    "write_accelerator_enabled": sdk.FieldSpec(wire_name="write_accelerator_enabled"),
    "diff_disk_settings": sdk.FieldSpec(
        wire_name="diff_disk_settings",
        kind="list",
        fields=_VirtualMachine_OsDisk_DiffDiskSettingsFields,
    ),
}

_VirtualMachine_OsImageNotificationFields = {
    "timeout": sdk.FieldSpec(wire_name="timeout"),
}

_VirtualMachine_PlanFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "product": sdk.FieldSpec(wire_name="product"),
    "publisher": sdk.FieldSpec(wire_name="publisher"),
}

_VirtualMachine_Secret_CertificateFields = {
    "store": sdk.FieldSpec(wire_name="store"),
    "url": sdk.FieldSpec(wire_name="url"),
}

_VirtualMachine_SecretFields = {
    "key_vault_id": sdk.FieldSpec(wire_name="key_vault_id"),
    "certificate": sdk.FieldSpec(
        wire_name="certificate",
        kind="set",
        fields=_VirtualMachine_Secret_CertificateFields,
    ),
}

_VirtualMachine_SourceImageReferenceFields = {
    "offer": sdk.FieldSpec(wire_name="offer"),
    "publisher": sdk.FieldSpec(wire_name="publisher"),
    "sku": sdk.FieldSpec(wire_name="sku"),
    "version": sdk.FieldSpec(wire_name="version"),
}

_VirtualMachine_TerminationNotificationFields = {
    "enabled": sdk.FieldSpec(wire_name="enabled"),
    "timeout": sdk.FieldSpec(wire_name="timeout"),
}

_VirtualMachine_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

_VirtualMachine_WinrmListenerFields = {
    "certificate_url": sdk.FieldSpec(wire_name="certificate_url"),
    "protocol": sdk.FieldSpec(wire_name="protocol"),
}

@dataclasses.dataclass
class VirtualMachineConfig:
    admin_password: Any = None
    admin_username: Any = None
    allow_extension_operations: Any = None
    automatic_updates_enabled: Any = None
    availability_set_id: Any = None
    bypass_platform_safety_checks_on_user_schedule_enabled: Any = None
    capacity_reservation_group_id: Any = None
    computer_name: Any = None
    custom_data: Any = None
    dedicated_host_group_id: Any = None
    dedicated_host_id: Any = None
    disk_controller_type: Any = None
    edge_zone: Any = None
    encryption_at_host_enabled: Any = None
    eviction_policy: Any = None
    extensions_time_budget: Any = None
    hotpatching_enabled: Any = None
    id: Any = None
    license_type: Any = None
    location: Any = None
    max_bid_price: Any = None
    name: Any = None
    network_interface_ids: Any = None
    os_managed_disk_id: Any = None
    patch_assessment_mode: Any = None
    patch_mode: Any = None
    platform_fault_domain: Any = None
    priority: Any = None
    provision_vm_agent: Any = None
    proximity_placement_group_id: Any = None
    reboot_setting: Any = None
    resource_group_name: Any = None
    secure_boot_enabled: Any = None
    size: Any = None
    source_image_id: Any = None
    tags: Any = None
    timezone: Any = None
    user_data: Any = None
    virtual_machine_scale_set_id: Any = None
    vtpm_enabled: Any = None
    zone: Any = None
    additional_capabilities: Any = None
    additional_unattend_content: Any = None
    boot_diagnostics: Any = None
    gallery_application: Any = None
    identity: Any = None
    os_disk: Any = None
    os_image_notification: Any = None
    plan: Any = None
    secret: Any = None
    source_image_reference: Any = None
    termination_notification: Any = None
    timeouts: Any = None
    winrm_listener: Any = None

VirtualMachine = sdk.ResourceBinding(
    wire_type="azurerm_windows_virtual_machine",
    fields={
        "admin_password": sdk.FieldSpec(wire_name="admin_password"),
        "admin_username": sdk.FieldSpec(wire_name="admin_username"),
        "allow_extension_operations": sdk.FieldSpec(wire_name="allow_extension_operations"),
        "automatic_updates_enabled": sdk.FieldSpec(wire_name="automatic_updates_enabled"),
        "availability_set_id": sdk.FieldSpec(wire_name="availability_set_id"),
        "bypass_platform_safety_checks_on_user_schedule_enabled": sdk.FieldSpec(wire_name="bypass_platform_safety_checks_on_user_schedule_enabled"),
        "capacity_reservation_group_id": sdk.FieldSpec(wire_name="capacity_reservation_group_id"),
        "computer_name": sdk.FieldSpec(wire_name="computer_name"),
        "custom_data": sdk.FieldSpec(wire_name="custom_data"),
        "dedicated_host_group_id": sdk.FieldSpec(wire_name="dedicated_host_group_id"),
        "dedicated_host_id": sdk.FieldSpec(wire_name="dedicated_host_id"),
        "disk_controller_type": sdk.FieldSpec(wire_name="disk_controller_type"),
        "edge_zone": sdk.FieldSpec(wire_name="edge_zone"),
        "encryption_at_host_enabled": sdk.FieldSpec(wire_name="encryption_at_host_enabled"),
        "eviction_policy": sdk.FieldSpec(wire_name="eviction_policy"),
        "extensions_time_budget": sdk.FieldSpec(wire_name="extensions_time_budget"),
        "hotpatching_enabled": sdk.FieldSpec(wire_name="hotpatching_enabled"),
        "id": sdk.FieldSpec(wire_name="id"),
        "license_type": sdk.FieldSpec(wire_name="license_type"),
        "location": sdk.FieldSpec(wire_name="location"),
        "max_bid_price": sdk.FieldSpec(wire_name="max_bid_price"),
        "name": sdk.FieldSpec(wire_name="name"),
        "network_interface_ids": sdk.FieldSpec(wire_name="network_interface_ids"),
        "os_managed_disk_id": sdk.FieldSpec(wire_name="os_managed_disk_id"),
        "patch_assessment_mode": sdk.FieldSpec(wire_name="patch_assessment_mode"),
        "patch_mode": sdk.FieldSpec(wire_name="patch_mode"),
        "platform_fault_domain": sdk.FieldSpec(wire_name="platform_fault_domain"),
        "priority": sdk.FieldSpec(wire_name="priority"),
        "provision_vm_agent": sdk.FieldSpec(wire_name="provision_vm_agent"),
        "proximity_placement_group_id": sdk.FieldSpec(wire_name="proximity_placement_group_id"),
        "reboot_setting": sdk.FieldSpec(wire_name="reboot_setting"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "secure_boot_enabled": sdk.FieldSpec(wire_name="secure_boot_enabled"),
        "size": sdk.FieldSpec(wire_name="size"),
        "source_image_id": sdk.FieldSpec(wire_name="source_image_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timezone": sdk.FieldSpec(wire_name="timezone"),
        "user_data": sdk.FieldSpec(wire_name="user_data"),
        "virtual_machine_scale_set_id": sdk.FieldSpec(wire_name="virtual_machine_scale_set_id"),
        "vtpm_enabled": sdk.FieldSpec(wire_name="vtpm_enabled"),
        "zone": sdk.FieldSpec(wire_name="zone"),
        "additional_capabilities": sdk.FieldSpec(
            wire_name="additional_capabilities",
            kind="list",
            fields=_VirtualMachine_AdditionalCapabilitiesFields,
        ),
        "additional_unattend_content": sdk.FieldSpec(
            wire_name="additional_unattend_content",
            kind="list",
            fields=_VirtualMachine_AdditionalUnattendContentFields,
        ),
        "boot_diagnostics": sdk.FieldSpec(
            wire_name="boot_diagnostics",
            kind="list",
            fields=_VirtualMachine_BootDiagnosticsFields,
        ),
        "gallery_application": sdk.FieldSpec(
            wire_name="gallery_application",
            kind="list",
            fields=_VirtualMachine_GalleryApplicationFields,
        ),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_VirtualMachine_IdentityFields,
        ),
        "os_disk": sdk.FieldSpec(
            wire_name="os_disk",
            kind="list",
            fields=_VirtualMachine_OsDiskFields,
        ),
        "os_image_notification": sdk.FieldSpec(
            wire_name="os_image_notification",
            kind="list",
            fields=_VirtualMachine_OsImageNotificationFields,
        ),
        "plan": sdk.FieldSpec(
            wire_name="plan",
            kind="list",
            fields=_VirtualMachine_PlanFields,
        ),
        "secret": sdk.FieldSpec(
            wire_name="secret",
            kind="list",
            fields=_VirtualMachine_SecretFields,
        ),
        "source_image_reference": sdk.FieldSpec(
            wire_name="source_image_reference",
            kind="list",
            fields=_VirtualMachine_SourceImageReferenceFields,
        ),
        "termination_notification": sdk.FieldSpec(
            wire_name="termination_notification",
            kind="list",
            fields=_VirtualMachine_TerminationNotificationFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VirtualMachine_TimeoutsFields,
        ),
        "winrm_listener": sdk.FieldSpec(
            wire_name="winrm_listener",
            kind="set",
            fields=_VirtualMachine_WinrmListenerFields,
        ),
    },
)
