# Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_virtual_machine_instance_guest_agent. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CenterVirtualMachineManagerVirtualMachineInstanceGuestAgent_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_CenterVirtualMachineManagerVirtualMachineInstanceGuestAgent_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class CenterVirtualMachineManagerVirtualMachineInstanceGuestAgentConfig:
    id: Any = None
    password: Any = None
    provisioning_action: Any = None
    scoped_resource_id: Any = None
    username: Any = None
    timeouts: Any = None

CenterVirtualMachineManagerVirtualMachineInstanceGuestAgent = sdk.ResourceBinding(
    wire_type="azurerm_system_center_virtual_machine_manager_virtual_machine_instance_guest_agent",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "password": sdk.FieldSpec(wire_name="password"),
        "provisioning_action": sdk.FieldSpec(wire_name="provisioning_action"),
        "scoped_resource_id": sdk.FieldSpec(wire_name="scoped_resource_id"),
        "username": sdk.FieldSpec(wire_name="username"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterVirtualMachineManagerVirtualMachineInstanceGuestAgent_TimeoutsFields,
        ),
    },
)
