# Code generated by `ubx sdk gen` from azurerm_eventhub_consumer_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConsumerGroup_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ConsumerGroup_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConsumerGroupConfig:
    eventhub_name: Any = None
    id: Any = None
    name: Any = None
    namespace_name: Any = None
    resource_group_name: Any = None
    user_metadata: Any = None
    timeouts: Any = None

ConsumerGroup = ubx.ResourceBinding(
    wire_type="azurerm_eventhub_consumer_group",
    fields={
        "eventhub_name": ubx.FieldSpec(wire_name="eventhub_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "namespace_name": ubx.FieldSpec(wire_name="namespace_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "user_metadata": ubx.FieldSpec(wire_name="user_metadata"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ConsumerGroup_TimeoutsFields,
        ),
    },
)
