# Code generated by `ubx sdk gen` from azurerm_eventhub. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Eventhub_CaptureDescription_Destination:
    archive_name_format: Any = None
    blob_container_name: Any = None
    name: Any = None
    storage_account_id: Any = None
    storage_authentication_id: Any = None
    storage_authentication_type: Any = None

@dataclasses.dataclass
class Eventhub_CaptureDescription:
    enabled: Any = None
    encoding: Any = None
    interval_in_seconds: Any = None
    size_limit_in_bytes: Any = None
    skip_empty_archives: Any = None
    destination: Any = None

@dataclasses.dataclass
class Eventhub_RetentionDescription:
    cleanup_policy: Any = None
    retention_time_in_hours: Any = None
    tombstone_retention_time_in_hours: Any = None

@dataclasses.dataclass
class Eventhub_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Eventhub_CaptureDescription_DestinationFields = {
    "archive_name_format": sdk.FieldSpec(wire_name="archive_name_format"),
    "blob_container_name": sdk.FieldSpec(wire_name="blob_container_name"),
    "name": sdk.FieldSpec(wire_name="name"),
    "storage_account_id": sdk.FieldSpec(wire_name="storage_account_id"),
    "storage_authentication_id": sdk.FieldSpec(wire_name="storage_authentication_id"),
    "storage_authentication_type": sdk.FieldSpec(wire_name="storage_authentication_type"),
}

_Eventhub_CaptureDescriptionFields = {
    "enabled": sdk.FieldSpec(wire_name="enabled"),
    "encoding": sdk.FieldSpec(wire_name="encoding"),
    "interval_in_seconds": sdk.FieldSpec(wire_name="interval_in_seconds"),
    "size_limit_in_bytes": sdk.FieldSpec(wire_name="size_limit_in_bytes"),
    "skip_empty_archives": sdk.FieldSpec(wire_name="skip_empty_archives"),
    "destination": sdk.FieldSpec(
        wire_name="destination",
        kind="list",
        fields=_Eventhub_CaptureDescription_DestinationFields,
    ),
}

_Eventhub_RetentionDescriptionFields = {
    "cleanup_policy": sdk.FieldSpec(wire_name="cleanup_policy"),
    "retention_time_in_hours": sdk.FieldSpec(wire_name="retention_time_in_hours"),
    "tombstone_retention_time_in_hours": sdk.FieldSpec(wire_name="tombstone_retention_time_in_hours"),
}

_Eventhub_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class EventhubConfig:
    id: Any = None
    message_retention: Any = None
    name: Any = None
    namespace_id: Any = None
    partition_count: Any = None
    status: Any = None
    capture_description: Any = None
    retention_description: Any = None
    timeouts: Any = None

Eventhub = sdk.ResourceBinding(
    wire_type="azurerm_eventhub",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "message_retention": sdk.FieldSpec(wire_name="message_retention"),
        "name": sdk.FieldSpec(wire_name="name"),
        "namespace_id": sdk.FieldSpec(wire_name="namespace_id"),
        "partition_count": sdk.FieldSpec(wire_name="partition_count"),
        "status": sdk.FieldSpec(wire_name="status"),
        "capture_description": sdk.FieldSpec(
            wire_name="capture_description",
            kind="list",
            fields=_Eventhub_CaptureDescriptionFields,
        ),
        "retention_description": sdk.FieldSpec(
            wire_name="retention_description",
            kind="list",
            fields=_Eventhub_RetentionDescriptionFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Eventhub_TimeoutsFields,
        ),
    },
)
