# Code generated by `ubx sdk gen` from azurerm_eventhub_namespace_disaster_recovery_config. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class NamespaceDisasterRecoveryConfig_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_NamespaceDisasterRecoveryConfig_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class NamespaceDisasterRecoveryConfigConfig:
    id: Any = None
    name: Any = None
    namespace_name: Any = None
    partner_namespace_id: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

NamespaceDisasterRecoveryConfig = ubx.ResourceBinding(
    wire_type="azurerm_eventhub_namespace_disaster_recovery_config",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "namespace_name": ubx.FieldSpec(wire_name="namespace_name"),
        "partner_namespace_id": ubx.FieldSpec(wire_name="partner_namespace_id"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_NamespaceDisasterRecoveryConfig_TimeoutsFields,
        ),
    },
)
