# Code generated by `ubx sdk gen` from azurerm_eventgrid_partner_namespace. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class PartnerNamespace_InboundIpRule:
    action: Any = None
    ip_mask: Any = None

@dataclasses.dataclass
class PartnerNamespace_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_PartnerNamespace_InboundIpRuleFields = {
    "action": sdk.FieldSpec(wire_name="action"),
    "ip_mask": sdk.FieldSpec(wire_name="ip_mask"),
}

_PartnerNamespace_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PartnerNamespaceConfig:
    id: Any = None
    local_authentication_enabled: Any = None
    location: Any = None
    name: Any = None
    partner_registration_id: Any = None
    partner_topic_routing_mode: Any = None
    public_network_access: Any = None
    resource_group_name: Any = None
    tags: Any = None
    inbound_ip_rule: Any = None
    timeouts: Any = None

PartnerNamespace = sdk.ResourceBinding(
    wire_type="azurerm_eventgrid_partner_namespace",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "local_authentication_enabled": sdk.FieldSpec(wire_name="local_authentication_enabled"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "partner_registration_id": sdk.FieldSpec(wire_name="partner_registration_id"),
        "partner_topic_routing_mode": sdk.FieldSpec(wire_name="partner_topic_routing_mode"),
        "public_network_access": sdk.FieldSpec(wire_name="public_network_access"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "inbound_ip_rule": sdk.FieldSpec(
            wire_name="inbound_ip_rule",
            kind="list",
            fields=_PartnerNamespace_InboundIpRuleFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PartnerNamespace_TimeoutsFields,
        ),
    },
)
