# Code generated by `ubx sdk gen` from azurerm_vpn_gateway_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class GatewayConnection_Routing_PropagatedRouteTable:
    labels: Any = None
    route_table_ids: Any = None

@dataclasses.dataclass
class GatewayConnection_Routing:
    associated_route_table: Any = None
    inbound_route_map_id: Any = None
    outbound_route_map_id: Any = None
    propagated_route_table: Any = None

@dataclasses.dataclass
class GatewayConnection_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class GatewayConnection_TrafficSelectorPolicy:
    local_address_ranges: Any = None
    remote_address_ranges: Any = None

@dataclasses.dataclass
class GatewayConnection_VpnLink_CustomBgpAddress:
    ip_address: Any = None
    ip_configuration_id: Any = None

@dataclasses.dataclass
class GatewayConnection_VpnLink_IpsecPolicy:
    dh_group: Any = None
    encryption_algorithm: Any = None
    ike_encryption_algorithm: Any = None
    ike_integrity_algorithm: Any = None
    integrity_algorithm: Any = None
    pfs_group: Any = None
    sa_data_size_kb: Any = None
    sa_lifetime_sec: Any = None

@dataclasses.dataclass
class GatewayConnection_VpnLink:
    bandwidth_mbps: Any = None
    bgp_enabled: Any = None
    connection_mode: Any = None
    dpd_timeout_seconds: Any = None
    egress_nat_rule_ids: Any = None
    ingress_nat_rule_ids: Any = None
    local_azure_ip_address_enabled: Any = None
    name: Any = None
    policy_based_traffic_selector_enabled: Any = None
    protocol: Any = None
    ratelimit_enabled: Any = None
    route_weight: Any = None
    shared_key: Any = None
    vpn_site_link_id: Any = None
    custom_bgp_address: Any = None
    ipsec_policy: Any = None

_GatewayConnection_Routing_PropagatedRouteTableFields = {
    "labels": sdk.FieldSpec(wire_name="labels"),
    "route_table_ids": sdk.FieldSpec(wire_name="route_table_ids"),
}

_GatewayConnection_RoutingFields = {
    "associated_route_table": sdk.FieldSpec(wire_name="associated_route_table"),
    "inbound_route_map_id": sdk.FieldSpec(wire_name="inbound_route_map_id"),
    "outbound_route_map_id": sdk.FieldSpec(wire_name="outbound_route_map_id"),
    "propagated_route_table": sdk.FieldSpec(
        wire_name="propagated_route_table",
        kind="list",
        fields=_GatewayConnection_Routing_PropagatedRouteTableFields,
    ),
}

_GatewayConnection_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

_GatewayConnection_TrafficSelectorPolicyFields = {
    "local_address_ranges": sdk.FieldSpec(wire_name="local_address_ranges"),
    "remote_address_ranges": sdk.FieldSpec(wire_name="remote_address_ranges"),
}

_GatewayConnection_VpnLink_CustomBgpAddressFields = {
    "ip_address": sdk.FieldSpec(wire_name="ip_address"),
    "ip_configuration_id": sdk.FieldSpec(wire_name="ip_configuration_id"),
}

_GatewayConnection_VpnLink_IpsecPolicyFields = {
    "dh_group": sdk.FieldSpec(wire_name="dh_group"),
    "encryption_algorithm": sdk.FieldSpec(wire_name="encryption_algorithm"),
    "ike_encryption_algorithm": sdk.FieldSpec(wire_name="ike_encryption_algorithm"),
    "ike_integrity_algorithm": sdk.FieldSpec(wire_name="ike_integrity_algorithm"),
    "integrity_algorithm": sdk.FieldSpec(wire_name="integrity_algorithm"),
    "pfs_group": sdk.FieldSpec(wire_name="pfs_group"),
    "sa_data_size_kb": sdk.FieldSpec(wire_name="sa_data_size_kb"),
    "sa_lifetime_sec": sdk.FieldSpec(wire_name="sa_lifetime_sec"),
}

_GatewayConnection_VpnLinkFields = {
    "bandwidth_mbps": sdk.FieldSpec(wire_name="bandwidth_mbps"),
    "bgp_enabled": sdk.FieldSpec(wire_name="bgp_enabled"),
    "connection_mode": sdk.FieldSpec(wire_name="connection_mode"),
    "dpd_timeout_seconds": sdk.FieldSpec(wire_name="dpd_timeout_seconds"),
    "egress_nat_rule_ids": sdk.FieldSpec(wire_name="egress_nat_rule_ids"),
    "ingress_nat_rule_ids": sdk.FieldSpec(wire_name="ingress_nat_rule_ids"),
    "local_azure_ip_address_enabled": sdk.FieldSpec(wire_name="local_azure_ip_address_enabled"),
    "name": sdk.FieldSpec(wire_name="name"),
    "policy_based_traffic_selector_enabled": sdk.FieldSpec(wire_name="policy_based_traffic_selector_enabled"),
    "protocol": sdk.FieldSpec(wire_name="protocol"),
    "ratelimit_enabled": sdk.FieldSpec(wire_name="ratelimit_enabled"),
    "route_weight": sdk.FieldSpec(wire_name="route_weight"),
    "shared_key": sdk.FieldSpec(wire_name="shared_key"),
    "vpn_site_link_id": sdk.FieldSpec(wire_name="vpn_site_link_id"),
    "custom_bgp_address": sdk.FieldSpec(
        wire_name="custom_bgp_address",
        kind="set",
        fields=_GatewayConnection_VpnLink_CustomBgpAddressFields,
    ),
    "ipsec_policy": sdk.FieldSpec(
        wire_name="ipsec_policy",
        kind="list",
        fields=_GatewayConnection_VpnLink_IpsecPolicyFields,
    ),
}

@dataclasses.dataclass
class GatewayConnectionConfig:
    id: Any = None
    internet_security_enabled: Any = None
    name: Any = None
    remote_vpn_site_id: Any = None
    vpn_gateway_id: Any = None
    routing: Any = None
    timeouts: Any = None
    traffic_selector_policy: Any = None
    vpn_link: Any = None

GatewayConnection = sdk.ResourceBinding(
    wire_type="azurerm_vpn_gateway_connection",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "internet_security_enabled": sdk.FieldSpec(wire_name="internet_security_enabled"),
        "name": sdk.FieldSpec(wire_name="name"),
        "remote_vpn_site_id": sdk.FieldSpec(wire_name="remote_vpn_site_id"),
        "vpn_gateway_id": sdk.FieldSpec(wire_name="vpn_gateway_id"),
        "routing": sdk.FieldSpec(
            wire_name="routing",
            kind="list",
            fields=_GatewayConnection_RoutingFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_GatewayConnection_TimeoutsFields,
        ),
        "traffic_selector_policy": sdk.FieldSpec(
            wire_name="traffic_selector_policy",
            kind="set",
            fields=_GatewayConnection_TrafficSelectorPolicyFields,
        ),
        "vpn_link": sdk.FieldSpec(
            wire_name="vpn_link",
            kind="list",
            fields=_GatewayConnection_VpnLinkFields,
        ),
    },
)
