# Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_custom_domain. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FrontdoorCustomDomain_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphers:
    tls12: Any = None
    tls13: Any = None

@dataclasses.dataclass
class FrontdoorCustomDomain_Tls_CipherSuite:
    type: Any = None
    custom_ciphers: Any = None

@dataclasses.dataclass
class FrontdoorCustomDomain_Tls:
    cdn_frontdoor_secret_id: Any = None
    certificate_type: Any = None
    minimum_version: Any = None
    cipher_suite: Any = None

_FrontdoorCustomDomain_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

_FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphersFields = {
    "tls12": ubx.FieldSpec(wire_name="tls12"),
    "tls13": ubx.FieldSpec(wire_name="tls13"),
}

_FrontdoorCustomDomain_Tls_CipherSuiteFields = {
    "type": ubx.FieldSpec(wire_name="type"),
    "custom_ciphers": ubx.FieldSpec(
        wire_name="custom_ciphers",
        kind="list",
        fields=_FrontdoorCustomDomain_Tls_CipherSuite_CustomCiphersFields,
    ),
}

_FrontdoorCustomDomain_TlsFields = {
    "cdn_frontdoor_secret_id": ubx.FieldSpec(wire_name="cdn_frontdoor_secret_id"),
    "certificate_type": ubx.FieldSpec(wire_name="certificate_type"),
    "minimum_version": ubx.FieldSpec(wire_name="minimum_version"),
    "cipher_suite": ubx.FieldSpec(
        wire_name="cipher_suite",
        kind="list",
        fields=_FrontdoorCustomDomain_Tls_CipherSuiteFields,
    ),
}

@dataclasses.dataclass
class FrontdoorCustomDomainConfig:
    cdn_frontdoor_profile_id: Any = None
    dns_zone_id: Any = None
    host_name: Any = None
    id: Any = None
    name: Any = None
    timeouts: Any = None
    tls: Any = None

FrontdoorCustomDomain = ubx.ResourceBinding(
    wire_type="azurerm_cdn_frontdoor_custom_domain",
    fields={
        "cdn_frontdoor_profile_id": ubx.FieldSpec(wire_name="cdn_frontdoor_profile_id"),
        "dns_zone_id": ubx.FieldSpec(wire_name="dns_zone_id"),
        "host_name": ubx.FieldSpec(wire_name="host_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FrontdoorCustomDomain_TimeoutsFields,
        ),
        "tls": ubx.FieldSpec(
            wire_name="tls",
            kind="list",
            fields=_FrontdoorCustomDomain_TlsFields,
        ),
    },
)
