# Code generated by `ubx sdk gen` from azurerm_image. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Image_DataDisk:
    blob_uri: Any = None
    caching: Any = None
    disk_encryption_set_id: Any = None
    lun: Any = None
    managed_disk_id: Any = None
    size_gb: Any = None
    storage_type: Any = None

@dataclasses.dataclass
class Image_OsDisk:
    blob_uri: Any = None
    caching: Any = None
    disk_encryption_set_id: Any = None
    managed_disk_id: Any = None
    os_state: Any = None
    os_type: Any = None
    size_gb: Any = None
    storage_type: Any = None

@dataclasses.dataclass
class Image_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Image_DataDiskFields = {
    "blob_uri": ubx.FieldSpec(wire_name="blob_uri"),
    "caching": ubx.FieldSpec(wire_name="caching"),
    "disk_encryption_set_id": ubx.FieldSpec(wire_name="disk_encryption_set_id"),
    "lun": ubx.FieldSpec(wire_name="lun"),
    "managed_disk_id": ubx.FieldSpec(wire_name="managed_disk_id"),
    "size_gb": ubx.FieldSpec(wire_name="size_gb"),
    "storage_type": ubx.FieldSpec(wire_name="storage_type"),
}

_Image_OsDiskFields = {
    "blob_uri": ubx.FieldSpec(wire_name="blob_uri"),
    "caching": ubx.FieldSpec(wire_name="caching"),
    "disk_encryption_set_id": ubx.FieldSpec(wire_name="disk_encryption_set_id"),
    "managed_disk_id": ubx.FieldSpec(wire_name="managed_disk_id"),
    "os_state": ubx.FieldSpec(wire_name="os_state"),
    "os_type": ubx.FieldSpec(wire_name="os_type"),
    "size_gb": ubx.FieldSpec(wire_name="size_gb"),
    "storage_type": ubx.FieldSpec(wire_name="storage_type"),
}

_Image_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ImageConfig:
    hyper_v_generation: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    source_virtual_machine_id: Any = None
    tags: Any = None
    zone_resilient: Any = None
    data_disk: Any = None
    os_disk: Any = None
    timeouts: Any = None

Image = ubx.ResourceBinding(
    wire_type="azurerm_image",
    fields={
        "hyper_v_generation": ubx.FieldSpec(wire_name="hyper_v_generation"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "source_virtual_machine_id": ubx.FieldSpec(wire_name="source_virtual_machine_id"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "zone_resilient": ubx.FieldSpec(wire_name="zone_resilient"),
        "data_disk": ubx.FieldSpec(
            wire_name="data_disk",
            kind="list",
            fields=_Image_DataDiskFields,
        ),
        "os_disk": ubx.FieldSpec(
            wire_name="os_disk",
            kind="list",
            fields=_Image_OsDiskFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Image_TimeoutsFields,
        ),
    },
)
