# Code generated by `ubx sdk gen` from azurerm_route_filter. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Filter_Rule:
    access: Any = None
    communities: Any = None
    name: Any = None
    rule_type: Any = None

@dataclasses.dataclass
class Filter_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Filter_RuleFields = {
    "access": sdk.FieldSpec(wire_name="access"),
    "communities": sdk.FieldSpec(wire_name="communities"),
    "name": sdk.FieldSpec(wire_name="name"),
    "rule_type": sdk.FieldSpec(wire_name="rule_type"),
}

_Filter_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FilterConfig:
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    rule: Any = None
    tags: Any = None
    timeouts: Any = None

Filter = sdk.ResourceBinding(
    wire_type="azurerm_route_filter",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "rule": sdk.FieldSpec(
            wire_name="rule",
            kind="list",
            fields=_Filter_RuleFields,
        ),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Filter_TimeoutsFields,
        ),
    },
)
