# Code generated by `ubx sdk gen` from azurerm_stack_hci_deployment_setting. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_Cluster:
    azure_service_endpoint: Any = None
    cloud_account_name: Any = None
    name: Any = None
    witness_path: Any = None
    witness_type: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverride:
    jumbo_packet: Any = None
    network_direct: Any = None
    network_direct_technology: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverride:
    bandwidth_percentage_smb: Any = None
    priority_value8021_action_cluster: Any = None
    priority_value8021_action_smb: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverride:
    enable_iov: Any = None
    load_balancing_algorithm: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork_Intent:
    adapter: Any = None
    adapter_property_override_enabled: Any = None
    name: Any = None
    qos_policy_override_enabled: Any = None
    traffic_type: Any = None
    virtual_switch_configuration_override_enabled: Any = None
    adapter_property_override: Any = None
    qos_policy_override: Any = None
    virtual_switch_configuration_override: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetwork:
    name: Any = None
    network_adapter_name: Any = None
    vlan_id: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_HostNetwork:
    storage_auto_ip_enabled: Any = None
    storage_connectivity_switchless_enabled: Any = None
    intent: Any = None
    storage_network: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPool:
    ending_address: Any = None
    starting_address: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_InfrastructureNetwork:
    dhcp_enabled: Any = None
    dns_server: Any = None
    gateway: Any = None
    subnet_mask: Any = None
    ip_pool: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_OptionalService:
    custom_location: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_PhysicalNode:
    ipv4_address: Any = None
    name: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit_Storage:
    configuration_mode: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_ScaleUnit:
    active_directory_organizational_unit_path: Any = None
    bitlocker_boot_volume_enabled: Any = None
    bitlocker_data_volume_enabled: Any = None
    credential_guard_enabled: Any = None
    domain_fqdn: Any = None
    drift_control_enabled: Any = None
    drtm_protection_enabled: Any = None
    episodic_data_upload_enabled: Any = None
    eu_location_enabled: Any = None
    hvci_protection_enabled: Any = None
    name_prefix: Any = None
    secrets_location: Any = None
    side_channel_mitigation_enabled: Any = None
    smb_cluster_encryption_enabled: Any = None
    smb_signing_enabled: Any = None
    streaming_data_client_enabled: Any = None
    wdac_enabled: Any = None
    cluster: Any = None
    host_network: Any = None
    infrastructure_network: Any = None
    optional_service: Any = None
    physical_node: Any = None
    storage: Any = None

@dataclasses.dataclass
class HciDeploymentSetting_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_HciDeploymentSetting_ScaleUnit_ClusterFields = {
    "azure_service_endpoint": ubx.FieldSpec(wire_name="azure_service_endpoint"),
    "cloud_account_name": ubx.FieldSpec(wire_name="cloud_account_name"),
    "name": ubx.FieldSpec(wire_name="name"),
    "witness_path": ubx.FieldSpec(wire_name="witness_path"),
    "witness_type": ubx.FieldSpec(wire_name="witness_type"),
}

_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverrideFields = {
    "jumbo_packet": ubx.FieldSpec(wire_name="jumbo_packet"),
    "network_direct": ubx.FieldSpec(wire_name="network_direct"),
    "network_direct_technology": ubx.FieldSpec(wire_name="network_direct_technology"),
}

_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverrideFields = {
    "bandwidth_percentage_smb": ubx.FieldSpec(wire_name="bandwidth_percentage_smb"),
    "priority_value8021_action_cluster": ubx.FieldSpec(wire_name="priority_value8021_action_cluster"),
    "priority_value8021_action_smb": ubx.FieldSpec(wire_name="priority_value8021_action_smb"),
}

_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverrideFields = {
    "enable_iov": ubx.FieldSpec(wire_name="enable_iov"),
    "load_balancing_algorithm": ubx.FieldSpec(wire_name="load_balancing_algorithm"),
}

_HciDeploymentSetting_ScaleUnit_HostNetwork_IntentFields = {
    "adapter": ubx.FieldSpec(wire_name="adapter"),
    "adapter_property_override_enabled": ubx.FieldSpec(wire_name="adapter_property_override_enabled"),
    "name": ubx.FieldSpec(wire_name="name"),
    "qos_policy_override_enabled": ubx.FieldSpec(wire_name="qos_policy_override_enabled"),
    "traffic_type": ubx.FieldSpec(wire_name="traffic_type"),
    "virtual_switch_configuration_override_enabled": ubx.FieldSpec(wire_name="virtual_switch_configuration_override_enabled"),
    "adapter_property_override": ubx.FieldSpec(
        wire_name="adapter_property_override",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_AdapterPropertyOverrideFields,
    ),
    "qos_policy_override": ubx.FieldSpec(
        wire_name="qos_policy_override",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_QosPolicyOverrideFields,
    ),
    "virtual_switch_configuration_override": ubx.FieldSpec(
        wire_name="virtual_switch_configuration_override",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetwork_Intent_VirtualSwitchConfigurationOverrideFields,
    ),
}

_HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetworkFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "network_adapter_name": ubx.FieldSpec(wire_name="network_adapter_name"),
    "vlan_id": ubx.FieldSpec(wire_name="vlan_id"),
}

_HciDeploymentSetting_ScaleUnit_HostNetworkFields = {
    "storage_auto_ip_enabled": ubx.FieldSpec(wire_name="storage_auto_ip_enabled"),
    "storage_connectivity_switchless_enabled": ubx.FieldSpec(wire_name="storage_connectivity_switchless_enabled"),
    "intent": ubx.FieldSpec(
        wire_name="intent",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetwork_IntentFields,
    ),
    "storage_network": ubx.FieldSpec(
        wire_name="storage_network",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetwork_StorageNetworkFields,
    ),
}

_HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPoolFields = {
    "ending_address": ubx.FieldSpec(wire_name="ending_address"),
    "starting_address": ubx.FieldSpec(wire_name="starting_address"),
}

_HciDeploymentSetting_ScaleUnit_InfrastructureNetworkFields = {
    "dhcp_enabled": ubx.FieldSpec(wire_name="dhcp_enabled"),
    "dns_server": ubx.FieldSpec(wire_name="dns_server"),
    "gateway": ubx.FieldSpec(wire_name="gateway"),
    "subnet_mask": ubx.FieldSpec(wire_name="subnet_mask"),
    "ip_pool": ubx.FieldSpec(
        wire_name="ip_pool",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_InfrastructureNetwork_IpPoolFields,
    ),
}

_HciDeploymentSetting_ScaleUnit_OptionalServiceFields = {
    "custom_location": ubx.FieldSpec(wire_name="custom_location"),
}

_HciDeploymentSetting_ScaleUnit_PhysicalNodeFields = {
    "ipv4_address": ubx.FieldSpec(wire_name="ipv4_address"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_HciDeploymentSetting_ScaleUnit_StorageFields = {
    "configuration_mode": ubx.FieldSpec(wire_name="configuration_mode"),
}

_HciDeploymentSetting_ScaleUnitFields = {
    "active_directory_organizational_unit_path": ubx.FieldSpec(wire_name="active_directory_organizational_unit_path"),
    "bitlocker_boot_volume_enabled": ubx.FieldSpec(wire_name="bitlocker_boot_volume_enabled"),
    "bitlocker_data_volume_enabled": ubx.FieldSpec(wire_name="bitlocker_data_volume_enabled"),
    "credential_guard_enabled": ubx.FieldSpec(wire_name="credential_guard_enabled"),
    "domain_fqdn": ubx.FieldSpec(wire_name="domain_fqdn"),
    "drift_control_enabled": ubx.FieldSpec(wire_name="drift_control_enabled"),
    "drtm_protection_enabled": ubx.FieldSpec(wire_name="drtm_protection_enabled"),
    "episodic_data_upload_enabled": ubx.FieldSpec(wire_name="episodic_data_upload_enabled"),
    "eu_location_enabled": ubx.FieldSpec(wire_name="eu_location_enabled"),
    "hvci_protection_enabled": ubx.FieldSpec(wire_name="hvci_protection_enabled"),
    "name_prefix": ubx.FieldSpec(wire_name="name_prefix"),
    "secrets_location": ubx.FieldSpec(wire_name="secrets_location"),
    "side_channel_mitigation_enabled": ubx.FieldSpec(wire_name="side_channel_mitigation_enabled"),
    "smb_cluster_encryption_enabled": ubx.FieldSpec(wire_name="smb_cluster_encryption_enabled"),
    "smb_signing_enabled": ubx.FieldSpec(wire_name="smb_signing_enabled"),
    "streaming_data_client_enabled": ubx.FieldSpec(wire_name="streaming_data_client_enabled"),
    "wdac_enabled": ubx.FieldSpec(wire_name="wdac_enabled"),
    "cluster": ubx.FieldSpec(
        wire_name="cluster",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_ClusterFields,
    ),
    "host_network": ubx.FieldSpec(
        wire_name="host_network",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_HostNetworkFields,
    ),
    "infrastructure_network": ubx.FieldSpec(
        wire_name="infrastructure_network",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_InfrastructureNetworkFields,
    ),
    "optional_service": ubx.FieldSpec(
        wire_name="optional_service",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_OptionalServiceFields,
    ),
    "physical_node": ubx.FieldSpec(
        wire_name="physical_node",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_PhysicalNodeFields,
    ),
    "storage": ubx.FieldSpec(
        wire_name="storage",
        kind="list",
        fields=_HciDeploymentSetting_ScaleUnit_StorageFields,
    ),
}

_HciDeploymentSetting_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class HciDeploymentSettingConfig:
    arc_resource_ids: Any = None
    id: Any = None
    stack_hci_cluster_id: Any = None
    version: Any = None
    scale_unit: Any = None
    timeouts: Any = None

HciDeploymentSetting = ubx.ResourceBinding(
    wire_type="azurerm_stack_hci_deployment_setting",
    fields={
        "arc_resource_ids": ubx.FieldSpec(wire_name="arc_resource_ids"),
        "id": ubx.FieldSpec(wire_name="id"),
        "stack_hci_cluster_id": ubx.FieldSpec(wire_name="stack_hci_cluster_id"),
        "version": ubx.FieldSpec(wire_name="version"),
        "scale_unit": ubx.FieldSpec(
            wire_name="scale_unit",
            kind="list",
            fields=_HciDeploymentSetting_ScaleUnitFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_HciDeploymentSetting_TimeoutsFields,
        ),
    },
)
