# Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_prefix_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AltoLocalRulestackPrefixList_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AltoLocalRulestackPrefixList_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AltoLocalRulestackPrefixListConfig:
    audit_comment: Any = None
    description: Any = None
    id: Any = None
    name: Any = None
    prefix_list: Any = None
    rulestack_id: Any = None
    timeouts: Any = None

AltoLocalRulestackPrefixList = sdk.ResourceBinding(
    wire_type="azurerm_palo_alto_local_rulestack_prefix_list",
    fields={
        "audit_comment": sdk.FieldSpec(wire_name="audit_comment"),
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "prefix_list": sdk.FieldSpec(wire_name="prefix_list"),
        "rulestack_id": sdk.FieldSpec(wire_name="rulestack_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AltoLocalRulestackPrefixList_TimeoutsFields,
        ),
    },
)
