# Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_outbound_untrust_certificate_association. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class AltoLocalRulestackOutboundUntrustCertificateAssociation_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_AltoLocalRulestackOutboundUntrustCertificateAssociation_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class AltoLocalRulestackOutboundUntrustCertificateAssociationConfig:
    certificate_id: Any = None
    id: Any = None
    timeouts: Any = None

AltoLocalRulestackOutboundUntrustCertificateAssociation = sdk.ResourceBinding(
    wire_type="azurerm_palo_alto_local_rulestack_outbound_untrust_certificate_association",
    fields={
        "certificate_id": sdk.FieldSpec(wire_name="certificate_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AltoLocalRulestackOutboundUntrustCertificateAssociation_TimeoutsFields,
        ),
    },
)
