# Code generated by `ubx sdk gen` from azurerm_dev_center_project_pool. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CenterProjectPool_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CenterProjectPool_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CenterProjectPoolConfig:
    dev_box_definition_name: Any = None
    dev_center_attached_network_name: Any = None
    dev_center_project_id: Any = None
    id: Any = None
    local_administrator_enabled: Any = None
    location: Any = None
    managed_virtual_network_regions: Any = None
    name: Any = None
    single_sign_on_enabled: Any = None
    stop_on_disconnect_grace_period_minutes: Any = None
    tags: Any = None
    timeouts: Any = None

CenterProjectPool = sdk.ResourceBinding(
    wire_type="azurerm_dev_center_project_pool",
    fields={
        "dev_box_definition_name": sdk.FieldSpec(wire_name="dev_box_definition_name"),
        "dev_center_attached_network_name": sdk.FieldSpec(wire_name="dev_center_attached_network_name"),
        "dev_center_project_id": sdk.FieldSpec(wire_name="dev_center_project_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "local_administrator_enabled": sdk.FieldSpec(wire_name="local_administrator_enabled"),
        "location": sdk.FieldSpec(wire_name="location"),
        "managed_virtual_network_regions": sdk.FieldSpec(wire_name="managed_virtual_network_regions"),
        "name": sdk.FieldSpec(wire_name="name"),
        "single_sign_on_enabled": sdk.FieldSpec(wire_name="single_sign_on_enabled"),
        "stop_on_disconnect_grace_period_minutes": sdk.FieldSpec(wire_name="stop_on_disconnect_grace_period_minutes"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CenterProjectPool_TimeoutsFields,
        ),
    },
)
