# Code generated by `ubx sdk gen` from azurerm_dev_test_schedule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class TestSchedule_DailyRecurrence:
    time: Any = None

@dataclasses.dataclass
class TestSchedule_HourlyRecurrence:
    minute: Any = None

@dataclasses.dataclass
class TestSchedule_NotificationSettings:
    status: Any = None
    time_in_minutes: Any = None
    webhook_url: Any = None

@dataclasses.dataclass
class TestSchedule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

@dataclasses.dataclass
class TestSchedule_WeeklyRecurrence:
    time: Any = None
    week_days: Any = None

_TestSchedule_DailyRecurrenceFields = {
    "time": sdk.FieldSpec(wire_name="time"),
}

_TestSchedule_HourlyRecurrenceFields = {
    "minute": sdk.FieldSpec(wire_name="minute"),
}

_TestSchedule_NotificationSettingsFields = {
    "status": sdk.FieldSpec(wire_name="status"),
    "time_in_minutes": sdk.FieldSpec(wire_name="time_in_minutes"),
    "webhook_url": sdk.FieldSpec(wire_name="webhook_url"),
}

_TestSchedule_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

_TestSchedule_WeeklyRecurrenceFields = {
    "time": sdk.FieldSpec(wire_name="time"),
    "week_days": sdk.FieldSpec(wire_name="week_days"),
}

@dataclasses.dataclass
class TestScheduleConfig:
    id: Any = None
    lab_name: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    status: Any = None
    tags: Any = None
    task_type: Any = None
    time_zone_id: Any = None
    daily_recurrence: Any = None
    hourly_recurrence: Any = None
    notification_settings: Any = None
    timeouts: Any = None
    weekly_recurrence: Any = None

TestSchedule = sdk.ResourceBinding(
    wire_type="azurerm_dev_test_schedule",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "lab_name": sdk.FieldSpec(wire_name="lab_name"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "status": sdk.FieldSpec(wire_name="status"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "task_type": sdk.FieldSpec(wire_name="task_type"),
        "time_zone_id": sdk.FieldSpec(wire_name="time_zone_id"),
        "daily_recurrence": sdk.FieldSpec(
            wire_name="daily_recurrence",
            kind="list",
            fields=_TestSchedule_DailyRecurrenceFields,
        ),
        "hourly_recurrence": sdk.FieldSpec(
            wire_name="hourly_recurrence",
            kind="list",
            fields=_TestSchedule_HourlyRecurrenceFields,
        ),
        "notification_settings": sdk.FieldSpec(
            wire_name="notification_settings",
            kind="list",
            fields=_TestSchedule_NotificationSettingsFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_TestSchedule_TimeoutsFields,
        ),
        "weekly_recurrence": sdk.FieldSpec(
            wire_name="weekly_recurrence",
            kind="list",
            fields=_TestSchedule_WeeklyRecurrenceFields,
        ),
    },
)
