# Code generated by `ubx sdk gen` from azurerm_storage_account_network_rules. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AccountNetworkRules_PrivateLinkAccess:
    endpoint_resource_id: Any = None
    endpoint_tenant_id: Any = None

@dataclasses.dataclass
class AccountNetworkRules_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AccountNetworkRules_PrivateLinkAccessFields = {
    "endpoint_resource_id": ubx.FieldSpec(wire_name="endpoint_resource_id"),
    "endpoint_tenant_id": ubx.FieldSpec(wire_name="endpoint_tenant_id"),
}

_AccountNetworkRules_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AccountNetworkRulesConfig:
    bypass: Any = None
    default_action: Any = None
    id: Any = None
    ip_rules: Any = None
    storage_account_id: Any = None
    virtual_network_subnet_ids: Any = None
    private_link_access: Any = None
    timeouts: Any = None

AccountNetworkRules = ubx.ResourceBinding(
    wire_type="azurerm_storage_account_network_rules",
    fields={
        "bypass": ubx.FieldSpec(wire_name="bypass"),
        "default_action": ubx.FieldSpec(wire_name="default_action"),
        "id": ubx.FieldSpec(wire_name="id"),
        "ip_rules": ubx.FieldSpec(wire_name="ip_rules"),
        "storage_account_id": ubx.FieldSpec(wire_name="storage_account_id"),
        "virtual_network_subnet_ids": ubx.FieldSpec(wire_name="virtual_network_subnet_ids"),
        "private_link_access": ubx.FieldSpec(
            wire_name="private_link_access",
            kind="list",
            fields=_AccountNetworkRules_PrivateLinkAccessFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AccountNetworkRules_TimeoutsFields,
        ),
    },
)
