# Code generated by `ubx sdk gen` from azurerm_storage_container. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Container_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Container_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ContainerConfig:
    container_access_type: Any = None
    default_encryption_scope: Any = None
    encryption_scope_override_enabled: Any = None
    id: Any = None
    metadata: Any = None
    name: Any = None
    storage_account_id: Any = None
    timeouts: Any = None

Container = ubx.ResourceBinding(
    wire_type="azurerm_storage_container",
    fields={
        "container_access_type": ubx.FieldSpec(wire_name="container_access_type"),
        "default_encryption_scope": ubx.FieldSpec(wire_name="default_encryption_scope"),
        "encryption_scope_override_enabled": ubx.FieldSpec(wire_name="encryption_scope_override_enabled"),
        "id": ubx.FieldSpec(wire_name="id"),
        "metadata": ubx.FieldSpec(wire_name="metadata"),
        "name": ubx.FieldSpec(wire_name="name"),
        "storage_account_id": ubx.FieldSpec(wire_name="storage_account_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Container_TimeoutsFields,
        ),
    },
)
