# Code generated by `ubx sdk gen` from azurerm_storage_object_replication. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ObjectReplication_Rules:
    copy_blobs_created_after: Any = None
    destination_container_name: Any = None
    filter_out_blobs_with_prefix: Any = None
    name: Any = None
    source_container_name: Any = None

@dataclasses.dataclass
class ObjectReplication_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ObjectReplication_RulesFields = {
    "copy_blobs_created_after": ubx.FieldSpec(wire_name="copy_blobs_created_after"),
    "destination_container_name": ubx.FieldSpec(wire_name="destination_container_name"),
    "filter_out_blobs_with_prefix": ubx.FieldSpec(wire_name="filter_out_blobs_with_prefix"),
    "name": ubx.FieldSpec(wire_name="name"),
    "source_container_name": ubx.FieldSpec(wire_name="source_container_name"),
}

_ObjectReplication_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ObjectReplicationConfig:
    destination_storage_account_id: Any = None
    id: Any = None
    metrics_enabled: Any = None
    source_storage_account_id: Any = None
    rules: Any = None
    timeouts: Any = None

ObjectReplication = ubx.ResourceBinding(
    wire_type="azurerm_storage_object_replication",
    fields={
        "destination_storage_account_id": ubx.FieldSpec(wire_name="destination_storage_account_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "metrics_enabled": ubx.FieldSpec(wire_name="metrics_enabled"),
        "source_storage_account_id": ubx.FieldSpec(wire_name="source_storage_account_id"),
        "rules": ubx.FieldSpec(
            wire_name="rules",
            kind="set",
            fields=_ObjectReplication_RulesFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ObjectReplication_TimeoutsFields,
        ),
    },
)
