# Code generated by `ubx sdk gen` from azurerm_data_factory_trigger_schedule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class FactoryTriggerSchedule_Pipeline:
    name: Any = None
    parameters: Any = None

@dataclasses.dataclass
class FactoryTriggerSchedule_Schedule_Monthly:
    week: Any = None
    weekday: Any = None

@dataclasses.dataclass
class FactoryTriggerSchedule_Schedule:
    days_of_month: Any = None
    days_of_week: Any = None
    hours: Any = None
    minutes: Any = None
    monthly: Any = None

@dataclasses.dataclass
class FactoryTriggerSchedule_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_FactoryTriggerSchedule_PipelineFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "parameters": sdk.FieldSpec(wire_name="parameters"),
}

_FactoryTriggerSchedule_Schedule_MonthlyFields = {
    "week": sdk.FieldSpec(wire_name="week"),
    "weekday": sdk.FieldSpec(wire_name="weekday"),
}

_FactoryTriggerSchedule_ScheduleFields = {
    "days_of_month": sdk.FieldSpec(wire_name="days_of_month"),
    "days_of_week": sdk.FieldSpec(wire_name="days_of_week"),
    "hours": sdk.FieldSpec(wire_name="hours"),
    "minutes": sdk.FieldSpec(wire_name="minutes"),
    "monthly": sdk.FieldSpec(
        wire_name="monthly",
        kind="list",
        fields=_FactoryTriggerSchedule_Schedule_MonthlyFields,
    ),
}

_FactoryTriggerSchedule_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FactoryTriggerScheduleConfig:
    activated: Any = None
    annotations: Any = None
    data_factory_id: Any = None
    description: Any = None
    end_time: Any = None
    frequency: Any = None
    id: Any = None
    interval: Any = None
    name: Any = None
    pipeline_name: Any = None
    pipeline_parameters: Any = None
    start_time: Any = None
    time_zone: Any = None
    pipeline: Any = None
    schedule: Any = None
    timeouts: Any = None

FactoryTriggerSchedule = sdk.ResourceBinding(
    wire_type="azurerm_data_factory_trigger_schedule",
    fields={
        "activated": sdk.FieldSpec(wire_name="activated"),
        "annotations": sdk.FieldSpec(wire_name="annotations"),
        "data_factory_id": sdk.FieldSpec(wire_name="data_factory_id"),
        "description": sdk.FieldSpec(wire_name="description"),
        "end_time": sdk.FieldSpec(wire_name="end_time"),
        "frequency": sdk.FieldSpec(wire_name="frequency"),
        "id": sdk.FieldSpec(wire_name="id"),
        "interval": sdk.FieldSpec(wire_name="interval"),
        "name": sdk.FieldSpec(wire_name="name"),
        "pipeline_name": sdk.FieldSpec(wire_name="pipeline_name"),
        "pipeline_parameters": sdk.FieldSpec(wire_name="pipeline_parameters"),
        "start_time": sdk.FieldSpec(wire_name="start_time"),
        "time_zone": sdk.FieldSpec(wire_name="time_zone"),
        "pipeline": sdk.FieldSpec(
            wire_name="pipeline",
            kind="list",
            fields=_FactoryTriggerSchedule_PipelineFields,
        ),
        "schedule": sdk.FieldSpec(
            wire_name="schedule",
            kind="list",
            fields=_FactoryTriggerSchedule_ScheduleFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FactoryTriggerSchedule_TimeoutsFields,
        ),
    },
)
