# Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_security_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class FrontdoorSecurityPolicy_SecurityPolicies_Firewall_Association_Domain:
    active: Any = None
    cdn_frontdoor_domain_id: Any = None

@dataclasses.dataclass
class FrontdoorSecurityPolicy_SecurityPolicies_Firewall_Association:
    patterns_to_match: Any = None
    domain: Any = None

@dataclasses.dataclass
class FrontdoorSecurityPolicy_SecurityPolicies_Firewall:
    cdn_frontdoor_firewall_policy_id: Any = None
    association: Any = None

@dataclasses.dataclass
class FrontdoorSecurityPolicy_SecurityPolicies:
    firewall: Any = None

@dataclasses.dataclass
class FrontdoorSecurityPolicy_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_FrontdoorSecurityPolicy_SecurityPolicies_Firewall_Association_DomainFields = {
    "active": sdk.FieldSpec(wire_name="active"),
    "cdn_frontdoor_domain_id": sdk.FieldSpec(wire_name="cdn_frontdoor_domain_id"),
}

_FrontdoorSecurityPolicy_SecurityPolicies_Firewall_AssociationFields = {
    "patterns_to_match": sdk.FieldSpec(wire_name="patterns_to_match"),
    "domain": sdk.FieldSpec(
        wire_name="domain",
        kind="list",
        fields=_FrontdoorSecurityPolicy_SecurityPolicies_Firewall_Association_DomainFields,
    ),
}

_FrontdoorSecurityPolicy_SecurityPolicies_FirewallFields = {
    "cdn_frontdoor_firewall_policy_id": sdk.FieldSpec(wire_name="cdn_frontdoor_firewall_policy_id"),
    "association": sdk.FieldSpec(
        wire_name="association",
        kind="list",
        fields=_FrontdoorSecurityPolicy_SecurityPolicies_Firewall_AssociationFields,
    ),
}

_FrontdoorSecurityPolicy_SecurityPoliciesFields = {
    "firewall": sdk.FieldSpec(
        wire_name="firewall",
        kind="list",
        fields=_FrontdoorSecurityPolicy_SecurityPolicies_FirewallFields,
    ),
}

_FrontdoorSecurityPolicy_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FrontdoorSecurityPolicyConfig:
    cdn_frontdoor_profile_id: Any = None
    id: Any = None
    name: Any = None
    security_policies: Any = None
    timeouts: Any = None

FrontdoorSecurityPolicy = sdk.ResourceBinding(
    wire_type="azurerm_cdn_frontdoor_security_policy",
    fields={
        "cdn_frontdoor_profile_id": sdk.FieldSpec(wire_name="cdn_frontdoor_profile_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "security_policies": sdk.FieldSpec(
            wire_name="security_policies",
            kind="list",
            fields=_FrontdoorSecurityPolicy_SecurityPoliciesFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FrontdoorSecurityPolicy_TimeoutsFields,
        ),
    },
)
