# Code generated by `ubx sdk gen` from azurerm_container_app_environment_certificate. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AppEnvironmentCertificate_CertificateKeyVault:
    identity: Any = None
    key_vault_secret_id: Any = None

@dataclasses.dataclass
class AppEnvironmentCertificate_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_AppEnvironmentCertificate_CertificateKeyVaultFields = {
    "identity": ubx.FieldSpec(wire_name="identity"),
    "key_vault_secret_id": ubx.FieldSpec(wire_name="key_vault_secret_id"),
}

_AppEnvironmentCertificate_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class AppEnvironmentCertificateConfig:
    certificate_blob_base64: Any = None
    certificate_password: Any = None
    container_app_environment_id: Any = None
    id: Any = None
    name: Any = None
    tags: Any = None
    certificate_key_vault: Any = None
    timeouts: Any = None

AppEnvironmentCertificate = ubx.ResourceBinding(
    wire_type="azurerm_container_app_environment_certificate",
    fields={
        "certificate_blob_base64": ubx.FieldSpec(wire_name="certificate_blob_base64"),
        "certificate_password": ubx.FieldSpec(wire_name="certificate_password"),
        "container_app_environment_id": ubx.FieldSpec(wire_name="container_app_environment_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "certificate_key_vault": ubx.FieldSpec(
            wire_name="certificate_key_vault",
            kind="list",
            fields=_AppEnvironmentCertificate_CertificateKeyVaultFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_AppEnvironmentCertificate_TimeoutsFields,
        ),
    },
)
