# Code generated by `ubx sdk gen` from azurerm_container_connected_registry. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConnectedRegistry_Notification:
    action: Any = None
    digest: Any = None
    name: Any = None
    tag: Any = None

@dataclasses.dataclass
class ConnectedRegistry_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ConnectedRegistry_NotificationFields = {
    "action": ubx.FieldSpec(wire_name="action"),
    "digest": ubx.FieldSpec(wire_name="digest"),
    "name": ubx.FieldSpec(wire_name="name"),
    "tag": ubx.FieldSpec(wire_name="tag"),
}

_ConnectedRegistry_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ConnectedRegistryConfig:
    audit_log_enabled: Any = None
    client_token_ids: Any = None
    container_registry_id: Any = None
    id: Any = None
    log_level: Any = None
    mode: Any = None
    name: Any = None
    parent_registry_id: Any = None
    sync_message_ttl: Any = None
    sync_schedule: Any = None
    sync_token_id: Any = None
    sync_window: Any = None
    notification: Any = None
    timeouts: Any = None

ConnectedRegistry = ubx.ResourceBinding(
    wire_type="azurerm_container_connected_registry",
    fields={
        "audit_log_enabled": ubx.FieldSpec(wire_name="audit_log_enabled"),
        "client_token_ids": ubx.FieldSpec(wire_name="client_token_ids"),
        "container_registry_id": ubx.FieldSpec(wire_name="container_registry_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "log_level": ubx.FieldSpec(wire_name="log_level"),
        "mode": ubx.FieldSpec(wire_name="mode"),
        "name": ubx.FieldSpec(wire_name="name"),
        "parent_registry_id": ubx.FieldSpec(wire_name="parent_registry_id"),
        "sync_message_ttl": ubx.FieldSpec(wire_name="sync_message_ttl"),
        "sync_schedule": ubx.FieldSpec(wire_name="sync_schedule"),
        "sync_token_id": ubx.FieldSpec(wire_name="sync_token_id"),
        "sync_window": ubx.FieldSpec(wire_name="sync_window"),
        "notification": ubx.FieldSpec(
            wire_name="notification",
            kind="list",
            fields=_ConnectedRegistry_NotificationFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ConnectedRegistry_TimeoutsFields,
        ),
    },
)
