# Code generated by `ubx sdk gen` from azurerm_healthcare_medtech_service. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MedtechService_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class MedtechService_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_MedtechService_IdentityFields = {
    "identity_ids": ubx.FieldSpec(wire_name="identity_ids"),
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_MedtechService_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class MedtechServiceConfig:
    device_mapping_json: Any = None
    eventhub_consumer_group_name: Any = None
    eventhub_name: Any = None
    eventhub_namespace_name: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    tags: Any = None
    workspace_id: Any = None
    identity: Any = None
    timeouts: Any = None

MedtechService = ubx.ResourceBinding(
    wire_type="azurerm_healthcare_medtech_service",
    fields={
        "device_mapping_json": ubx.FieldSpec(wire_name="device_mapping_json"),
        "eventhub_consumer_group_name": ubx.FieldSpec(wire_name="eventhub_consumer_group_name"),
        "eventhub_name": ubx.FieldSpec(wire_name="eventhub_name"),
        "eventhub_namespace_name": ubx.FieldSpec(wire_name="eventhub_namespace_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "workspace_id": ubx.FieldSpec(wire_name="workspace_id"),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_MedtechService_IdentityFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_MedtechService_TimeoutsFields,
        ),
    },
)
