# Code generated by `ubx sdk gen` from azurerm_iothub_device_update_account. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DeviceUpdateAccount_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class DeviceUpdateAccount_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DeviceUpdateAccount_IdentityFields = {
    "identity_ids": sdk.FieldSpec(wire_name="identity_ids"),
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_DeviceUpdateAccount_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DeviceUpdateAccountConfig:
    id: Any = None
    location: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    sku: Any = None
    tags: Any = None
    identity: Any = None
    timeouts: Any = None

DeviceUpdateAccount = sdk.ResourceBinding(
    wire_type="azurerm_iothub_device_update_account",
    fields={
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "public_network_access_enabled": sdk.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "sku": sdk.FieldSpec(wire_name="sku"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_DeviceUpdateAccount_IdentityFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DeviceUpdateAccount_TimeoutsFields,
        ),
    },
)
