# Code generated by `ubx sdk gen` from azurerm_iotcentral_organization. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Organization_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Organization_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class OrganizationConfig:
    display_name: Any = None
    id: Any = None
    iotcentral_application_id: Any = None
    organization_id: Any = None
    parent_organization_id: Any = None
    timeouts: Any = None

Organization = sdk.ResourceBinding(
    wire_type="azurerm_iotcentral_organization",
    fields={
        "display_name": sdk.FieldSpec(wire_name="display_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "iotcentral_application_id": sdk.FieldSpec(wire_name="iotcentral_application_id"),
        "organization_id": sdk.FieldSpec(wire_name="organization_id"),
        "parent_organization_id": sdk.FieldSpec(wire_name="parent_organization_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Organization_TimeoutsFields,
        ),
    },
)
