# Code generated by `ubx sdk gen` from azurerm_cosmosdb_cassandra_cluster. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class CassandraCluster_Identity:
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class CassandraCluster_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CassandraCluster_IdentityFields = {
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_CassandraCluster_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CassandraClusterConfig:
    authentication_method: Any = None
    client_certificate_pems: Any = None
    default_admin_password: Any = None
    delegated_management_subnet_id: Any = None
    external_gossip_certificate_pems: Any = None
    external_seed_node_ip_addresses: Any = None
    hours_between_backups: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    repair_enabled: Any = None
    resource_group_name: Any = None
    tags: Any = None
    version: Any = None
    identity: Any = None
    timeouts: Any = None

CassandraCluster = sdk.ResourceBinding(
    wire_type="azurerm_cosmosdb_cassandra_cluster",
    fields={
        "authentication_method": sdk.FieldSpec(wire_name="authentication_method"),
        "client_certificate_pems": sdk.FieldSpec(wire_name="client_certificate_pems"),
        "default_admin_password": sdk.FieldSpec(wire_name="default_admin_password"),
        "delegated_management_subnet_id": sdk.FieldSpec(wire_name="delegated_management_subnet_id"),
        "external_gossip_certificate_pems": sdk.FieldSpec(wire_name="external_gossip_certificate_pems"),
        "external_seed_node_ip_addresses": sdk.FieldSpec(wire_name="external_seed_node_ip_addresses"),
        "hours_between_backups": sdk.FieldSpec(wire_name="hours_between_backups"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "repair_enabled": sdk.FieldSpec(wire_name="repair_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "version": sdk.FieldSpec(wire_name="version"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_CassandraCluster_IdentityFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CassandraCluster_TimeoutsFields,
        ),
    },
)
