# Code generated by `ubx sdk gen` from azurerm_cosmosdb_sql_database. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SqlDatabase_AutoscaleSettings:
    max_throughput: Any = None

@dataclasses.dataclass
class SqlDatabase_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SqlDatabase_AutoscaleSettingsFields = {
    "max_throughput": ubx.FieldSpec(wire_name="max_throughput"),
}

_SqlDatabase_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SqlDatabaseConfig:
    account_name: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    throughput: Any = None
    autoscale_settings: Any = None
    timeouts: Any = None

SqlDatabase = ubx.ResourceBinding(
    wire_type="azurerm_cosmosdb_sql_database",
    fields={
        "account_name": ubx.FieldSpec(wire_name="account_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "throughput": ubx.FieldSpec(wire_name="throughput"),
        "autoscale_settings": ubx.FieldSpec(
            wire_name="autoscale_settings",
            kind="list",
            fields=_SqlDatabase_AutoscaleSettingsFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SqlDatabase_TimeoutsFields,
        ),
    },
)
