# Code generated by `ubx sdk gen` from azurerm_cosmosdb_sql_dedicated_gateway. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SqlDedicatedGateway_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SqlDedicatedGateway_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SqlDedicatedGatewayConfig:
    cosmosdb_account_id: Any = None
    id: Any = None
    instance_count: Any = None
    instance_size: Any = None
    timeouts: Any = None

SqlDedicatedGateway = ubx.ResourceBinding(
    wire_type="azurerm_cosmosdb_sql_dedicated_gateway",
    fields={
        "cosmosdb_account_id": ubx.FieldSpec(wire_name="cosmosdb_account_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "instance_count": ubx.FieldSpec(wire_name="instance_count"),
        "instance_size": ubx.FieldSpec(wire_name="instance_size"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SqlDedicatedGateway_TimeoutsFields,
        ),
    },
)
