# Code generated by `ubx sdk gen` from azurerm_cosmosdb_sql_role_definition. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class SqlRoleDefinition_Permissions:
    data_actions: Any = None

@dataclasses.dataclass
class SqlRoleDefinition_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_SqlRoleDefinition_PermissionsFields = {
    "data_actions": sdk.FieldSpec(wire_name="data_actions"),
}

_SqlRoleDefinition_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SqlRoleDefinitionConfig:
    account_name: Any = None
    assignable_scopes: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    role_definition_id: Any = None
    type: Any = None
    permissions: Any = None
    timeouts: Any = None

SqlRoleDefinition = sdk.ResourceBinding(
    wire_type="azurerm_cosmosdb_sql_role_definition",
    fields={
        "account_name": sdk.FieldSpec(wire_name="account_name"),
        "assignable_scopes": sdk.FieldSpec(wire_name="assignable_scopes"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "role_definition_id": sdk.FieldSpec(wire_name="role_definition_id"),
        "type": sdk.FieldSpec(wire_name="type"),
        "permissions": sdk.FieldSpec(
            wire_name="permissions",
            kind="set",
            fields=_SqlRoleDefinition_PermissionsFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_SqlRoleDefinition_TimeoutsFields,
        ),
    },
)
