# Code generated by `ubx sdk gen` from azurerm_key_vault_managed_hardware_security_module_key_rotation_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class VaultManagedHardwareSecurityModuleKeyRotationPolicy_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VaultManagedHardwareSecurityModuleKeyRotationPolicy_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VaultManagedHardwareSecurityModuleKeyRotationPolicyConfig:
    expire_after: Any = None
    id: Any = None
    managed_hsm_key_id: Any = None
    time_after_creation: Any = None
    time_before_expiry: Any = None
    timeouts: Any = None

VaultManagedHardwareSecurityModuleKeyRotationPolicy = sdk.ResourceBinding(
    wire_type="azurerm_key_vault_managed_hardware_security_module_key_rotation_policy",
    fields={
        "expire_after": sdk.FieldSpec(wire_name="expire_after"),
        "id": sdk.FieldSpec(wire_name="id"),
        "managed_hsm_key_id": sdk.FieldSpec(wire_name="managed_hsm_key_id"),
        "time_after_creation": sdk.FieldSpec(wire_name="time_after_creation"),
        "time_before_expiry": sdk.FieldSpec(wire_name="time_before_expiry"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VaultManagedHardwareSecurityModuleKeyRotationPolicy_TimeoutsFields,
        ),
    },
)
