# Code generated by `ubx sdk gen` from azurerm_key_vault_secret. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VaultSecret_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VaultSecret_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VaultSecretConfig:
    content_type: Any = None
    expiration_date: Any = None
    id: Any = None
    key_vault_id: Any = None
    name: Any = None
    not_before_date: Any = None
    tags: Any = None
    value: Any = None
    value_wo: Any = None
    value_wo_version: Any = None
    timeouts: Any = None

VaultSecret = ubx.ResourceBinding(
    wire_type="azurerm_key_vault_secret",
    fields={
        "content_type": ubx.FieldSpec(wire_name="content_type"),
        "expiration_date": ubx.FieldSpec(wire_name="expiration_date"),
        "id": ubx.FieldSpec(wire_name="id"),
        "key_vault_id": ubx.FieldSpec(wire_name="key_vault_id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "not_before_date": ubx.FieldSpec(wire_name="not_before_date"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "value": ubx.FieldSpec(wire_name="value"),
        "value_wo": ubx.FieldSpec(wire_name="value_wo"),
        "value_wo_version": ubx.FieldSpec(wire_name="value_wo_version"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VaultSecret_TimeoutsFields,
        ),
    },
)
