# Code generated by `ubx sdk gen` from azurerm_key_vault_certificate_contacts. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VaultCertificateContacts_Contact:
    email: Any = None
    name: Any = None
    phone: Any = None

@dataclasses.dataclass
class VaultCertificateContacts_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VaultCertificateContacts_ContactFields = {
    "email": ubx.FieldSpec(wire_name="email"),
    "name": ubx.FieldSpec(wire_name="name"),
    "phone": ubx.FieldSpec(wire_name="phone"),
}

_VaultCertificateContacts_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VaultCertificateContactsConfig:
    id: Any = None
    key_vault_id: Any = None
    contact: Any = None
    timeouts: Any = None

VaultCertificateContacts = ubx.ResourceBinding(
    wire_type="azurerm_key_vault_certificate_contacts",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "key_vault_id": ubx.FieldSpec(wire_name="key_vault_id"),
        "contact": ubx.FieldSpec(
            wire_name="contact",
            kind="set",
            fields=_VaultCertificateContacts_ContactFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VaultCertificateContacts_TimeoutsFields,
        ),
    },
)
