# Code generated by `ubx sdk gen` from azurerm_automation_dsc_nodeconfiguration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DscNodeconfiguration_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DscNodeconfiguration_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DscNodeconfigurationConfig:
    automation_account_name: Any = None
    content_embedded: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    timeouts: Any = None

DscNodeconfiguration = sdk.ResourceBinding(
    wire_type="azurerm_automation_dsc_nodeconfiguration",
    fields={
        "automation_account_name": sdk.FieldSpec(wire_name="automation_account_name"),
        "content_embedded": sdk.FieldSpec(wire_name="content_embedded"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DscNodeconfiguration_TimeoutsFields,
        ),
    },
)
