# Code generated by `ubx sdk gen` from azurerm_automation_runtime_environment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class RuntimeEnvironment_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_RuntimeEnvironment_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class RuntimeEnvironmentConfig:
    automation_account_id: Any = None
    description: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    runtime_default_packages: Any = None
    runtime_language: Any = None
    runtime_version: Any = None
    tags: Any = None
    timeouts: Any = None

RuntimeEnvironment = sdk.ResourceBinding(
    wire_type="azurerm_automation_runtime_environment",
    fields={
        "automation_account_id": sdk.FieldSpec(wire_name="automation_account_id"),
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "runtime_default_packages": sdk.FieldSpec(wire_name="runtime_default_packages"),
        "runtime_language": sdk.FieldSpec(wire_name="runtime_language"),
        "runtime_version": sdk.FieldSpec(wire_name="runtime_version"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RuntimeEnvironment_TimeoutsFields,
        ),
    },
)
