# Code generated by `ubx sdk gen` from azurerm_automation_variable_datetime. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class VariableDatetime_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_VariableDatetime_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class VariableDatetimeConfig:
    automation_account_name: Any = None
    description: Any = None
    encrypted: Any = None
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    value: Any = None
    timeouts: Any = None

VariableDatetime = sdk.ResourceBinding(
    wire_type="azurerm_automation_variable_datetime",
    fields={
        "automation_account_name": sdk.FieldSpec(wire_name="automation_account_name"),
        "description": sdk.FieldSpec(wire_name="description"),
        "encrypted": sdk.FieldSpec(wire_name="encrypted"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "value": sdk.FieldSpec(wire_name="value"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_VariableDatetime_TimeoutsFields,
        ),
    },
)
