# Code generated by `ubx sdk gen` from azurerm_notification_hub. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Hub_ApnsCredential:
    application_mode: Any = None
    bundle_id: Any = None
    key_id: Any = None
    team_id: Any = None
    token: Any = None

@dataclasses.dataclass
class Hub_BrowserCredential:
    subject: Any = None
    vapid_private_key: Any = None
    vapid_public_key: Any = None

@dataclasses.dataclass
class Hub_GcmCredential:
    api_key: Any = None

@dataclasses.dataclass
class Hub_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Hub_ApnsCredentialFields = {
    "application_mode": ubx.FieldSpec(wire_name="application_mode"),
    "bundle_id": ubx.FieldSpec(wire_name="bundle_id"),
    "key_id": ubx.FieldSpec(wire_name="key_id"),
    "team_id": ubx.FieldSpec(wire_name="team_id"),
    "token": ubx.FieldSpec(wire_name="token"),
}

_Hub_BrowserCredentialFields = {
    "subject": ubx.FieldSpec(wire_name="subject"),
    "vapid_private_key": ubx.FieldSpec(wire_name="vapid_private_key"),
    "vapid_public_key": ubx.FieldSpec(wire_name="vapid_public_key"),
}

_Hub_GcmCredentialFields = {
    "api_key": ubx.FieldSpec(wire_name="api_key"),
}

_Hub_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class HubConfig:
    id: Any = None
    location: Any = None
    name: Any = None
    namespace_name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    apns_credential: Any = None
    browser_credential: Any = None
    gcm_credential: Any = None
    timeouts: Any = None

Hub = ubx.ResourceBinding(
    wire_type="azurerm_notification_hub",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "namespace_name": ubx.FieldSpec(wire_name="namespace_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "apns_credential": ubx.FieldSpec(
            wire_name="apns_credential",
            kind="list",
            fields=_Hub_ApnsCredentialFields,
        ),
        "browser_credential": ubx.FieldSpec(
            wire_name="browser_credential",
            kind="list",
            fields=_Hub_BrowserCredentialFields,
        ),
        "gcm_credential": ubx.FieldSpec(
            wire_name="gcm_credential",
            kind="list",
            fields=_Hub_GcmCredentialFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Hub_TimeoutsFields,
        ),
    },
)
