# Code generated by `ubx sdk gen` from azurerm_new_relic_monitor. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class RelicMonitor_Identity:
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class RelicMonitor_Plan:
    billing_cycle: Any = None
    effective_date: Any = None
    plan_id: Any = None
    usage_type: Any = None

@dataclasses.dataclass
class RelicMonitor_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

@dataclasses.dataclass
class RelicMonitor_User:
    email: Any = None
    first_name: Any = None
    last_name: Any = None
    phone_number: Any = None

_RelicMonitor_IdentityFields = {
    "principal_id": sdk.FieldSpec(wire_name="principal_id"),
    "tenant_id": sdk.FieldSpec(wire_name="tenant_id"),
    "type": sdk.FieldSpec(wire_name="type"),
}

_RelicMonitor_PlanFields = {
    "billing_cycle": sdk.FieldSpec(wire_name="billing_cycle"),
    "effective_date": sdk.FieldSpec(wire_name="effective_date"),
    "plan_id": sdk.FieldSpec(wire_name="plan_id"),
    "usage_type": sdk.FieldSpec(wire_name="usage_type"),
}

_RelicMonitor_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
}

_RelicMonitor_UserFields = {
    "email": sdk.FieldSpec(wire_name="email"),
    "first_name": sdk.FieldSpec(wire_name="first_name"),
    "last_name": sdk.FieldSpec(wire_name="last_name"),
    "phone_number": sdk.FieldSpec(wire_name="phone_number"),
}

@dataclasses.dataclass
class RelicMonitorConfig:
    account_creation_source: Any = None
    account_id: Any = None
    id: Any = None
    ingestion_key: Any = None
    location: Any = None
    name: Any = None
    org_creation_source: Any = None
    organization_id: Any = None
    resource_group_name: Any = None
    user_id: Any = None
    identity: Any = None
    plan: Any = None
    timeouts: Any = None
    user: Any = None

RelicMonitor = sdk.ResourceBinding(
    wire_type="azurerm_new_relic_monitor",
    fields={
        "account_creation_source": sdk.FieldSpec(wire_name="account_creation_source"),
        "account_id": sdk.FieldSpec(wire_name="account_id"),
        "id": sdk.FieldSpec(wire_name="id"),
        "ingestion_key": sdk.FieldSpec(wire_name="ingestion_key"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "org_creation_source": sdk.FieldSpec(wire_name="org_creation_source"),
        "organization_id": sdk.FieldSpec(wire_name="organization_id"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "user_id": sdk.FieldSpec(wire_name="user_id"),
        "identity": sdk.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_RelicMonitor_IdentityFields,
        ),
        "plan": sdk.FieldSpec(
            wire_name="plan",
            kind="list",
            fields=_RelicMonitor_PlanFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_RelicMonitor_TimeoutsFields,
        ),
        "user": sdk.FieldSpec(
            wire_name="user",
            kind="list",
            fields=_RelicMonitor_UserFields,
        ),
    },
)
