# Code generated by `ubx sdk gen` from azurerm_virtual_desktop_workspace. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DesktopWorkspace_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DesktopWorkspace_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DesktopWorkspaceConfig:
    description: Any = None
    friendly_name: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    tags: Any = None
    timeouts: Any = None

DesktopWorkspace = sdk.ResourceBinding(
    wire_type="azurerm_virtual_desktop_workspace",
    fields={
        "description": sdk.FieldSpec(wire_name="description"),
        "friendly_name": sdk.FieldSpec(wire_name="friendly_name"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "public_network_access_enabled": sdk.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DesktopWorkspace_TimeoutsFields,
        ),
    },
)
