# Code generated by `ubx sdk gen` from azurerm_virtual_hub. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Hub_Route:
    address_prefixes: Any = None
    next_hop_ip_address: Any = None

@dataclasses.dataclass
class Hub_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Hub_RouteFields = {
    "address_prefixes": ubx.FieldSpec(wire_name="address_prefixes"),
    "next_hop_ip_address": ubx.FieldSpec(wire_name="next_hop_ip_address"),
}

_Hub_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class HubConfig:
    address_prefix: Any = None
    branch_to_branch_traffic_enabled: Any = None
    hub_routing_preference: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    sku: Any = None
    tags: Any = None
    virtual_router_auto_scale_min_capacity: Any = None
    virtual_wan_id: Any = None
    route: Any = None
    timeouts: Any = None

Hub = ubx.ResourceBinding(
    wire_type="azurerm_virtual_hub",
    fields={
        "address_prefix": ubx.FieldSpec(wire_name="address_prefix"),
        "branch_to_branch_traffic_enabled": ubx.FieldSpec(wire_name="branch_to_branch_traffic_enabled"),
        "hub_routing_preference": ubx.FieldSpec(wire_name="hub_routing_preference"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "sku": ubx.FieldSpec(wire_name="sku"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "virtual_router_auto_scale_min_capacity": ubx.FieldSpec(wire_name="virtual_router_auto_scale_min_capacity"),
        "virtual_wan_id": ubx.FieldSpec(wire_name="virtual_wan_id"),
        "route": ubx.FieldSpec(
            wire_name="route",
            kind="set",
            fields=_Hub_RouteFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Hub_TimeoutsFields,
        ),
    },
)
