# Code generated by `ubx sdk gen` from azurerm_virtual_network. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class Network_Subnet_Delegation_ServiceDelegation:
    actions: Any = None
    name: Any = None

@dataclasses.dataclass
class Network_Subnet_Delegation:
    name: Any = None
    service_delegation: Any = None

@dataclasses.dataclass
class Network_Subnet_ServiceEndpoint:
    network_identifier: Any = None
    service: Any = None

@dataclasses.dataclass
class Network_Subnet:
    address_prefixes: Any = None
    default_outbound_access_enabled: Any = None
    delegation: Any = None
    id: Any = None
    name: Any = None
    private_endpoint_network_policies: Any = None
    private_link_service_network_policies_enabled: Any = None
    route_table_id: Any = None
    security_group: Any = None
    service_endpoint: Any = None
    service_endpoint_policy_ids: Any = None

@dataclasses.dataclass
class Network_DdosProtectionPlan:
    enable: Any = None
    id: Any = None

@dataclasses.dataclass
class Network_Encryption:
    enforcement: Any = None

@dataclasses.dataclass
class Network_IpAddressPool:
    allocated_ip_address_prefixes: Any = None
    id: Any = None
    number_of_ip_addresses: Any = None

@dataclasses.dataclass
class Network_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Network_Subnet_Delegation_ServiceDelegationFields = {
    "actions": sdk.FieldSpec(wire_name="actions"),
    "name": sdk.FieldSpec(wire_name="name"),
}

_Network_Subnet_DelegationFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "service_delegation": sdk.FieldSpec(
        wire_name="service_delegation",
        kind="list",
        fields=_Network_Subnet_Delegation_ServiceDelegationFields,
    ),
}

_Network_Subnet_ServiceEndpointFields = {
    "network_identifier": sdk.FieldSpec(wire_name="network_identifier"),
    "service": sdk.FieldSpec(wire_name="service"),
}

_Network_SubnetFields = {
    "address_prefixes": sdk.FieldSpec(wire_name="address_prefixes"),
    "default_outbound_access_enabled": sdk.FieldSpec(wire_name="default_outbound_access_enabled"),
    "delegation": sdk.FieldSpec(
        wire_name="delegation",
        kind="list",
        fields=_Network_Subnet_DelegationFields,
    ),
    "id": sdk.FieldSpec(wire_name="id"),
    "name": sdk.FieldSpec(wire_name="name"),
    "private_endpoint_network_policies": sdk.FieldSpec(wire_name="private_endpoint_network_policies"),
    "private_link_service_network_policies_enabled": sdk.FieldSpec(wire_name="private_link_service_network_policies_enabled"),
    "route_table_id": sdk.FieldSpec(wire_name="route_table_id"),
    "security_group": sdk.FieldSpec(wire_name="security_group"),
    "service_endpoint": sdk.FieldSpec(
        wire_name="service_endpoint",
        kind="list",
        fields=_Network_Subnet_ServiceEndpointFields,
    ),
    "service_endpoint_policy_ids": sdk.FieldSpec(wire_name="service_endpoint_policy_ids"),
}

_Network_DdosProtectionPlanFields = {
    "enable": sdk.FieldSpec(wire_name="enable"),
    "id": sdk.FieldSpec(wire_name="id"),
}

_Network_EncryptionFields = {
    "enforcement": sdk.FieldSpec(wire_name="enforcement"),
}

_Network_IpAddressPoolFields = {
    "allocated_ip_address_prefixes": sdk.FieldSpec(wire_name="allocated_ip_address_prefixes"),
    "id": sdk.FieldSpec(wire_name="id"),
    "number_of_ip_addresses": sdk.FieldSpec(wire_name="number_of_ip_addresses"),
}

_Network_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class NetworkConfig:
    address_space: Any = None
    bgp_community: Any = None
    dns_servers: Any = None
    edge_zone: Any = None
    flow_timeout_in_minutes: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    private_endpoint_vnet_policies: Any = None
    resource_group_name: Any = None
    subnet: Any = None
    tags: Any = None
    ddos_protection_plan: Any = None
    encryption: Any = None
    ip_address_pool: Any = None
    timeouts: Any = None

Network = sdk.ResourceBinding(
    wire_type="azurerm_virtual_network",
    fields={
        "address_space": sdk.FieldSpec(wire_name="address_space"),
        "bgp_community": sdk.FieldSpec(wire_name="bgp_community"),
        "dns_servers": sdk.FieldSpec(wire_name="dns_servers"),
        "edge_zone": sdk.FieldSpec(wire_name="edge_zone"),
        "flow_timeout_in_minutes": sdk.FieldSpec(wire_name="flow_timeout_in_minutes"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "private_endpoint_vnet_policies": sdk.FieldSpec(wire_name="private_endpoint_vnet_policies"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "subnet": sdk.FieldSpec(
            wire_name="subnet",
            kind="set",
            fields=_Network_SubnetFields,
        ),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "ddos_protection_plan": sdk.FieldSpec(
            wire_name="ddos_protection_plan",
            kind="list",
            fields=_Network_DdosProtectionPlanFields,
        ),
        "encryption": sdk.FieldSpec(
            wire_name="encryption",
            kind="list",
            fields=_Network_EncryptionFields,
        ),
        "ip_address_pool": sdk.FieldSpec(
            wire_name="ip_address_pool",
            kind="list",
            fields=_Network_IpAddressPoolFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Network_TimeoutsFields,
        ),
    },
)
