# Code generated by `ubx sdk gen` from azurerm_private_dns_mx_record. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DnsMxRecord_Record:
    exchange: Any = None
    preference: Any = None

@dataclasses.dataclass
class DnsMxRecord_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DnsMxRecord_RecordFields = {
    "exchange": ubx.FieldSpec(wire_name="exchange"),
    "preference": ubx.FieldSpec(wire_name="preference"),
}

_DnsMxRecord_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DnsMxRecordConfig:
    id: Any = None
    name: Any = None
    private_dns_zone_id: Any = None
    tags: Any = None
    ttl: Any = None
    record: Any = None
    timeouts: Any = None

DnsMxRecord = ubx.ResourceBinding(
    wire_type="azurerm_private_dns_mx_record",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "private_dns_zone_id": ubx.FieldSpec(wire_name="private_dns_zone_id"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "ttl": ubx.FieldSpec(wire_name="ttl"),
        "record": ubx.FieldSpec(
            wire_name="record",
            kind="set",
            fields=_DnsMxRecord_RecordFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DnsMxRecord_TimeoutsFields,
        ),
    },
)
