# Code generated by `ubx sdk gen` from azurerm_private_dns_ptr_record. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DnsPtrRecord_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DnsPtrRecord_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DnsPtrRecordConfig:
    id: Any = None
    name: Any = None
    private_dns_zone_id: Any = None
    records: Any = None
    tags: Any = None
    ttl: Any = None
    timeouts: Any = None

DnsPtrRecord = ubx.ResourceBinding(
    wire_type="azurerm_private_dns_ptr_record",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "private_dns_zone_id": ubx.FieldSpec(wire_name="private_dns_zone_id"),
        "records": ubx.FieldSpec(wire_name="records"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "ttl": ubx.FieldSpec(wire_name="ttl"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DnsPtrRecord_TimeoutsFields,
        ),
    },
)
