# Code generated by `ubx sdk gen` from hashicorp/azurerm@5.0.1. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "hashicorp/azurerm", "version": "5.0.1"}

from .sap_discovery_virtual_instance import SapDiscoveryVirtualInstance, SapDiscoveryVirtualInstanceConfig
from .sap_single_node_virtual_instance import SapSingleNodeVirtualInstance, SapSingleNodeVirtualInstanceConfig
from .sap_three_tier_virtual_instance import SapThreeTierVirtualInstance, SapThreeTierVirtualInstanceConfig
