# Code generated by `ubx sdk gen` from azurerm_postgresql_flexible_server_backup. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FlexibleServerBackup_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None

_FlexibleServerBackup_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
}

@dataclasses.dataclass
class FlexibleServerBackupConfig:
    id: Any = None
    name: Any = None
    server_id: Any = None
    timeouts: Any = None

FlexibleServerBackup = ubx.ResourceBinding(
    wire_type="azurerm_postgresql_flexible_server_backup",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "server_id": ubx.FieldSpec(wire_name="server_id"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FlexibleServerBackup_TimeoutsFields,
        ),
    },
)
