# Code generated by `ubx sdk gen` from azurerm_mssql_failover_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class FailoverGroup_PartnerServer:
    id: Any = None
    location: Any = None
    role: Any = None

@dataclasses.dataclass
class FailoverGroup_ReadWriteEndpointFailoverPolicy:
    grace_minutes: Any = None
    mode: Any = None

@dataclasses.dataclass
class FailoverGroup_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_FailoverGroup_PartnerServerFields = {
    "id": sdk.FieldSpec(wire_name="id"),
    "location": sdk.FieldSpec(wire_name="location"),
    "role": sdk.FieldSpec(wire_name="role"),
}

_FailoverGroup_ReadWriteEndpointFailoverPolicyFields = {
    "grace_minutes": sdk.FieldSpec(wire_name="grace_minutes"),
    "mode": sdk.FieldSpec(wire_name="mode"),
}

_FailoverGroup_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FailoverGroupConfig:
    databases: Any = None
    id: Any = None
    name: Any = None
    readonly_endpoint_failover_policy_enabled: Any = None
    server_id: Any = None
    tags: Any = None
    partner_server: Any = None
    read_write_endpoint_failover_policy: Any = None
    timeouts: Any = None

FailoverGroup = sdk.ResourceBinding(
    wire_type="azurerm_mssql_failover_group",
    fields={
        "databases": sdk.FieldSpec(wire_name="databases"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "readonly_endpoint_failover_policy_enabled": sdk.FieldSpec(wire_name="readonly_endpoint_failover_policy_enabled"),
        "server_id": sdk.FieldSpec(wire_name="server_id"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "partner_server": sdk.FieldSpec(
            wire_name="partner_server",
            kind="list",
            fields=_FailoverGroup_PartnerServerFields,
        ),
        "read_write_endpoint_failover_policy": sdk.FieldSpec(
            wire_name="read_write_endpoint_failover_policy",
            kind="list",
            fields=_FailoverGroup_ReadWriteEndpointFailoverPolicyFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FailoverGroup_TimeoutsFields,
        ),
    },
)
