# Code generated by `ubx sdk gen` from azurerm_load_test. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Test_Encryption_Identity:
    identity_id: Any = None
    type: Any = None

@dataclasses.dataclass
class Test_Encryption:
    key_url: Any = None
    identity: Any = None

@dataclasses.dataclass
class Test_Identity:
    identity_ids: Any = None
    principal_id: Any = None
    tenant_id: Any = None
    type: Any = None

@dataclasses.dataclass
class Test_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_Test_Encryption_IdentityFields = {
    "identity_id": ubx.FieldSpec(wire_name="identity_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_Test_EncryptionFields = {
    "key_url": ubx.FieldSpec(wire_name="key_url"),
    "identity": ubx.FieldSpec(
        wire_name="identity",
        kind="list",
        fields=_Test_Encryption_IdentityFields,
    ),
}

_Test_IdentityFields = {
    "identity_ids": ubx.FieldSpec(wire_name="identity_ids"),
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_Test_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class TestConfig:
    description: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    encryption: Any = None
    identity: Any = None
    timeouts: Any = None

Test = ubx.ResourceBinding(
    wire_type="azurerm_load_test",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "encryption": ubx.FieldSpec(
            wire_name="encryption",
            kind="list",
            fields=_Test_EncryptionFields,
        ),
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="list",
            fields=_Test_IdentityFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Test_TimeoutsFields,
        ),
    },
)
