# Code generated by `ubx sdk gen` from azurerm_bot_channel_facebook. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class ChannelFacebook_Page:
    access_token: Any = None
    id: Any = None

@dataclasses.dataclass
class ChannelFacebook_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ChannelFacebook_PageFields = {
    "access_token": sdk.FieldSpec(wire_name="access_token"),
    "id": sdk.FieldSpec(wire_name="id"),
}

_ChannelFacebook_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ChannelFacebookConfig:
    bot_name: Any = None
    facebook_application_id: Any = None
    facebook_application_secret: Any = None
    id: Any = None
    location: Any = None
    resource_group_name: Any = None
    page: Any = None
    timeouts: Any = None

ChannelFacebook = sdk.ResourceBinding(
    wire_type="azurerm_bot_channel_facebook",
    fields={
        "bot_name": sdk.FieldSpec(wire_name="bot_name"),
        "facebook_application_id": sdk.FieldSpec(wire_name="facebook_application_id"),
        "facebook_application_secret": sdk.FieldSpec(wire_name="facebook_application_secret"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "page": sdk.FieldSpec(
            wire_name="page",
            kind="set",
            fields=_ChannelFacebook_PageFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ChannelFacebook_TimeoutsFields,
        ),
    },
)
