# Code generated by `ubx sdk gen` from azurerm_bot_channel_directline. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ChannelDirectline_Site:
    enabled: Any = None
    endpoint_parameters_enabled: Any = None
    enhanced_authentication_enabled: Any = None
    id: Any = None
    key: Any = None
    key2: Any = None
    name: Any = None
    storage_enabled: Any = None
    trusted_origins: Any = None
    user_upload_enabled: Any = None
    v1_allowed: Any = None
    v3_allowed: Any = None

@dataclasses.dataclass
class ChannelDirectline_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ChannelDirectline_SiteFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "endpoint_parameters_enabled": ubx.FieldSpec(wire_name="endpoint_parameters_enabled"),
    "enhanced_authentication_enabled": ubx.FieldSpec(wire_name="enhanced_authentication_enabled"),
    "id": ubx.FieldSpec(wire_name="id"),
    "key": ubx.FieldSpec(wire_name="key"),
    "key2": ubx.FieldSpec(wire_name="key2"),
    "name": ubx.FieldSpec(wire_name="name"),
    "storage_enabled": ubx.FieldSpec(wire_name="storage_enabled"),
    "trusted_origins": ubx.FieldSpec(wire_name="trusted_origins"),
    "user_upload_enabled": ubx.FieldSpec(wire_name="user_upload_enabled"),
    "v1_allowed": ubx.FieldSpec(wire_name="v1_allowed"),
    "v3_allowed": ubx.FieldSpec(wire_name="v3_allowed"),
}

_ChannelDirectline_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ChannelDirectlineConfig:
    bot_name: Any = None
    id: Any = None
    location: Any = None
    resource_group_name: Any = None
    site: Any = None
    timeouts: Any = None

ChannelDirectline = ubx.ResourceBinding(
    wire_type="azurerm_bot_channel_directline",
    fields={
        "bot_name": ubx.FieldSpec(wire_name="bot_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "site": ubx.FieldSpec(
            wire_name="site",
            kind="set",
            fields=_ChannelDirectline_SiteFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ChannelDirectline_TimeoutsFields,
        ),
    },
)
