# Code generated by `ubx sdk gen` from azurerm_bot_service_azure_bot. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceAzureBot_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_ServiceAzureBot_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class ServiceAzureBotConfig:
    cmk_key_vault_key_url: Any = None
    developer_app_insights_api_key: Any = None
    developer_app_insights_application_id: Any = None
    developer_app_insights_key: Any = None
    display_name: Any = None
    endpoint: Any = None
    icon_url: Any = None
    id: Any = None
    local_authentication_enabled: Any = None
    location: Any = None
    luis_app_ids: Any = None
    luis_key: Any = None
    microsoft_app_id: Any = None
    microsoft_app_msi_id: Any = None
    microsoft_app_tenant_id: Any = None
    microsoft_app_type: Any = None
    name: Any = None
    public_network_access_enabled: Any = None
    resource_group_name: Any = None
    sku: Any = None
    streaming_endpoint_enabled: Any = None
    tags: Any = None
    timeouts: Any = None

ServiceAzureBot = ubx.ResourceBinding(
    wire_type="azurerm_bot_service_azure_bot",
    fields={
        "cmk_key_vault_key_url": ubx.FieldSpec(wire_name="cmk_key_vault_key_url"),
        "developer_app_insights_api_key": ubx.FieldSpec(wire_name="developer_app_insights_api_key"),
        "developer_app_insights_application_id": ubx.FieldSpec(wire_name="developer_app_insights_application_id"),
        "developer_app_insights_key": ubx.FieldSpec(wire_name="developer_app_insights_key"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "endpoint": ubx.FieldSpec(wire_name="endpoint"),
        "icon_url": ubx.FieldSpec(wire_name="icon_url"),
        "id": ubx.FieldSpec(wire_name="id"),
        "local_authentication_enabled": ubx.FieldSpec(wire_name="local_authentication_enabled"),
        "location": ubx.FieldSpec(wire_name="location"),
        "luis_app_ids": ubx.FieldSpec(wire_name="luis_app_ids"),
        "luis_key": ubx.FieldSpec(wire_name="luis_key"),
        "microsoft_app_id": ubx.FieldSpec(wire_name="microsoft_app_id"),
        "microsoft_app_msi_id": ubx.FieldSpec(wire_name="microsoft_app_msi_id"),
        "microsoft_app_tenant_id": ubx.FieldSpec(wire_name="microsoft_app_tenant_id"),
        "microsoft_app_type": ubx.FieldSpec(wire_name="microsoft_app_type"),
        "name": ubx.FieldSpec(wire_name="name"),
        "public_network_access_enabled": ubx.FieldSpec(wire_name="public_network_access_enabled"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "sku": ubx.FieldSpec(wire_name="sku"),
        "streaming_endpoint_enabled": ubx.FieldSpec(wire_name="streaming_endpoint_enabled"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_ServiceAzureBot_TimeoutsFields,
        ),
    },
)
