# Code generated by `ubx sdk gen` from azurerm_mysql_flexible_server_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FlexibleServerConfiguration_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_FlexibleServerConfiguration_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class FlexibleServerConfigurationConfig:
    id: Any = None
    name: Any = None
    resource_group_name: Any = None
    server_name: Any = None
    value: Any = None
    timeouts: Any = None

FlexibleServerConfiguration = ubx.ResourceBinding(
    wire_type="azurerm_mysql_flexible_server_configuration",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "server_name": ubx.FieldSpec(wire_name="server_name"),
        "value": ubx.FieldSpec(wire_name="value"),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_FlexibleServerConfiguration_TimeoutsFields,
        ),
    },
)
