# Code generated by `ubx sdk gen` from azurerm_elastic_cloud_elasticsearch. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CloudElasticsearch_Logs_FilteringTag:
    action: Any = None
    name: Any = None
    value: Any = None

@dataclasses.dataclass
class CloudElasticsearch_Logs:
    send_activity_logs: Any = None
    send_azuread_logs: Any = None
    send_subscription_logs: Any = None
    filtering_tag: Any = None

@dataclasses.dataclass
class CloudElasticsearch_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_CloudElasticsearch_Logs_FilteringTagFields = {
    "action": ubx.FieldSpec(wire_name="action"),
    "name": ubx.FieldSpec(wire_name="name"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_CloudElasticsearch_LogsFields = {
    "send_activity_logs": ubx.FieldSpec(wire_name="send_activity_logs"),
    "send_azuread_logs": ubx.FieldSpec(wire_name="send_azuread_logs"),
    "send_subscription_logs": ubx.FieldSpec(wire_name="send_subscription_logs"),
    "filtering_tag": ubx.FieldSpec(
        wire_name="filtering_tag",
        kind="list",
        fields=_CloudElasticsearch_Logs_FilteringTagFields,
    ),
}

_CloudElasticsearch_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "read": ubx.FieldSpec(wire_name="read"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class CloudElasticsearchConfig:
    elastic_cloud_email_address: Any = None
    id: Any = None
    location: Any = None
    monitoring_enabled: Any = None
    name: Any = None
    resource_group_name: Any = None
    sku_name: Any = None
    tags: Any = None
    logs: Any = None
    timeouts: Any = None

CloudElasticsearch = ubx.ResourceBinding(
    wire_type="azurerm_elastic_cloud_elasticsearch",
    fields={
        "elastic_cloud_email_address": ubx.FieldSpec(wire_name="elastic_cloud_email_address"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "monitoring_enabled": ubx.FieldSpec(wire_name="monitoring_enabled"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "sku_name": ubx.FieldSpec(wire_name="sku_name"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "logs": ubx.FieldSpec(
            wire_name="logs",
            kind="list",
            fields=_CloudElasticsearch_LogsFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_CloudElasticsearch_TimeoutsFields,
        ),
    },
)
