# Code generated by `ubx sdk gen` from azurerm_elastic_san. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class San_Sku:
    name: Any = None
    tier: Any = None

@dataclasses.dataclass
class San_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_San_SkuFields = {
    "name": sdk.FieldSpec(wire_name="name"),
    "tier": sdk.FieldSpec(wire_name="tier"),
}

_San_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SanConfig:
    base_size_in_tib: Any = None
    extended_size_in_tib: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    resource_group_name: Any = None
    tags: Any = None
    zones: Any = None
    sku: Any = None
    timeouts: Any = None

San = sdk.ResourceBinding(
    wire_type="azurerm_elastic_san",
    fields={
        "base_size_in_tib": sdk.FieldSpec(wire_name="base_size_in_tib"),
        "extended_size_in_tib": sdk.FieldSpec(wire_name="extended_size_in_tib"),
        "id": sdk.FieldSpec(wire_name="id"),
        "location": sdk.FieldSpec(wire_name="location"),
        "name": sdk.FieldSpec(wire_name="name"),
        "resource_group_name": sdk.FieldSpec(wire_name="resource_group_name"),
        "tags": sdk.FieldSpec(wire_name="tags"),
        "zones": sdk.FieldSpec(wire_name="zones"),
        "sku": sdk.FieldSpec(
            wire_name="sku",
            kind="list",
            fields=_San_SkuFields,
        ),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_San_TimeoutsFields,
        ),
    },
)
