# Code generated by `ubx sdk gen` from azurerm_monitor_data_collection_rule_association. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as sdk

@dataclasses.dataclass
class DataCollectionRuleAssociation_Timeouts:
    create: Any = None
    delete: Any = None
    read: Any = None
    update: Any = None

_DataCollectionRuleAssociation_TimeoutsFields = {
    "create": sdk.FieldSpec(wire_name="create"),
    "delete": sdk.FieldSpec(wire_name="delete"),
    "read": sdk.FieldSpec(wire_name="read"),
    "update": sdk.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class DataCollectionRuleAssociationConfig:
    data_collection_endpoint_id: Any = None
    data_collection_rule_id: Any = None
    description: Any = None
    id: Any = None
    name: Any = None
    target_resource_id: Any = None
    timeouts: Any = None

DataCollectionRuleAssociation = sdk.ResourceBinding(
    wire_type="azurerm_monitor_data_collection_rule_association",
    fields={
        "data_collection_endpoint_id": sdk.FieldSpec(wire_name="data_collection_endpoint_id"),
        "data_collection_rule_id": sdk.FieldSpec(wire_name="data_collection_rule_id"),
        "description": sdk.FieldSpec(wire_name="description"),
        "id": sdk.FieldSpec(wire_name="id"),
        "name": sdk.FieldSpec(wire_name="name"),
        "target_resource_id": sdk.FieldSpec(wire_name="target_resource_id"),
        "timeouts": sdk.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_DataCollectionRuleAssociation_TimeoutsFields,
        ),
    },
)
